### PR TITLE
automate extension-api generation

### PR DESCRIPTION
**Pull request by aruniverse**
add extract-api to core-extension which calls the generate api
generate api script depends on extract-api having been run on core-frontend and core-common so change extract-api to follow dependency order

### CODE REVIEW

**Review by calebmshafer — CHANGES_REQUESTED** [review]
There's an issue on windows with the script. Trying to dig into that now. Otherwise the change looks right.

**Review by calebmshafer — APPROVED** [review]
thanks! working now on windows too.

**Comment by calebmshafer** [comment]
@pmconne mind approving?

**Comment by calebmshafer** [comment]
@aruniverse do we need to backport the changes to the API to 3.4?

**Review by pmconne — APPROVED** [review]

**Pull request merged**
