### PR TITLE
update reality-data-client and browser-authorization

### PR DESCRIPTION
**Pull request by mcote01**
reality-data-client is not updated yet in display-test-app due tu another clashing dependency : 

- @iTwin/service-authorization/0.3.0 still depending on @itwin/core-common 3.0.0-extension.1_f2c[....]

### CODE REVIEW

**Review by MarcBedard8 — APPROVED** [review]

**Comment by pmconne** [comment]
I'd like someone involved with the performance testing (@markschlosseratbentley @MarcNeely?) to see how/whether this affects performance.
I still have no good theories as to why the previous PR that switched us to the new reality-data-client apparently negatively impacted those tests.

**Review by MarcNeely — APPROVED** [review]
Looks like this did it!  Tests are running back up to speed.

**Review by calebmshafer — APPROVED** [review]

**Comment by mcote01** [comment]
@Mergifyio update

**Comment by pmconne** [comment]
@bsteinbk @NancyMcCallB please review trivial change to ui-test-app.

**Review by bsteinbk — APPROVED** [review]

**Pull request merged**
