### PR TITLE
Support epsg 4326 map layer projections + ESRI tilemap fixes

### PR DESCRIPTION
**Pull request by mdastous-bentley**
Added support EPSG:4326 in WMTS
Rework and fixes bugs in child availability.
Added new ArcGisTileMap class to deal with tilemap requests.

### CODE REVIEW

**Comment by pmconne** [comment]
@RBBentley @mdastous-bentley ImageTests produced a large number of differences. I will email some examples.

**Comment by mdastous-bentley** [comment]
@pmconne can you approve please.

**Comment by pmconne** [comment]
> @pmconne can you approve please.

Looking at it. Please do not resolve other people's comments on your PRs.

**Comment by pmconne** [comment]
Has a full ImageTests run proven all the regressions are fixed? Are there any differences that were considered improvements?

**Comment by mdastous-bentley** [comment]
> Has a full ImageTests run proven all the regressions are fixed? Are there any differences that were considered improvements?

@RBBentley said it was ready to go.  Should we make a final test run?

**Comment by pmconne** [comment]
> @RBBentley said it was ready to go. Should we make a final test run?

No, it doesn't look like any further functional changes have been pushed.

**Review by pmconne — APPROVED** [review]

**Pull request merged**
