### PR TITLE
use latest electron auth client pkg that uses export map

### PR DESCRIPTION
**Pull request by aruniverse**
itwin/electron-authoorization@0.15 supports [package.json export map](https://medium.com/swlh/npm-new-package-json-exports-field-1a7d1f489ccf)

Update to use the following recommended tsconfigs:

Frontend: 

``` 
    "module": "ESNext",
    "moduleResolution": "Bundler",
```

[ESNext](https://www.typescriptlang.org/tsconfig#esnext)
[Bundler](https://www.typescriptlang.org/tsconfig#moduleResolution)

Backend:

``` 
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
```

[NodeNext](https://www.typescriptlang.org/tsconfig#node16nodenext-nightly-builds)
[NodeNext](https://www.typescriptlang.org/tsconfig#moduleResolution)

Everything should compile fine; I will note, vscode intellisense will still complain about being unable to resolve / traverse the fields from the export map

### CODE REVIEW

**Review by nick4598 — APPROVED** [review]

**Comment by aruniverse** [comment]
used https://twitter.com/wesbos/status/1615738911380078592 to help with rewriting esm import

**Comment by aruniverse** [comment]
rush cover locally failing on trying to resolve export map subpath which does exist:
image

**Comment by aruniverse** [comment]
abandoning in favor of #6739

**Pull request closed without merging**
