### PR TITLE
ESLint nonblock-statement-body-position

### PR DESCRIPTION
**Pull request by pmconne**
Per our [TypeScript coding guidelines](https://www.itwinjs.org/learning/guidelines/typescript-coding-guidelines/#make-judicious-use-of-vertical-screen-space):
> The body of an if statement or a loop should be on a separate line, even if the body contains only a single line of code.

Use [ESLint](https://eslint.org/docs/latest/rules/nonblock-statement-body-position) [rules](https://eslint.org/docs/latest/rules/max-statements-per-line) to enforce this so we can stop wasting time on it in PR review and so we can set breakpoints without having to edit+rebuild.

UI packages exempted to avoid conflicts with long-lived appui 4.0 branch.

### CODE REVIEW

**Review by kabentley — APPROVED** [review]

**Review by bbastings — APPROVED** [review]

**Review by mgooding — APPROVED** [review]

**Review by calebmshafer — APPROVED** [review]

**Review by ben-polinsky — APPROVED** [review]
Ran into the alphabetize issue myself - very annoying :)

**Comment by pmconne** [comment]
@aruniverse magic comments plugin tests failed again.

**Review by dassaf4 — APPROVED** [review]

**Comment by pmconne** [comment]
@khanaffan restart query test failed again.

**Comment by pmconne** [comment]
@calebmshafer @tcobbs-bentley @toddsouthenbentley it seems like dta iOS build fails intermittently.
Looks like parallel builds may be trying to write to the same output directory `/AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/`?

```
> display-test-app@1.8.0 build:ios-app
> cd ios/imodeljs-test-app && SYMROOT=`xcodebuild -showBuildSettings 2>/dev/null | egrep '^[ ]+BUILD_DIR' | sed 's/.Products$//; s/^[ ]*BUILD_DIR = //'` && xcodebuild build SYMROOT=${SYMROOT} CODE_SIGN_STYLE='Manual' CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO PROVISIONING_PROFILE_SPECIFIER='' -arch x86_64 -sdk iphonesimulator -configuration Debug

Command line invocation:
    /Applications/Xcode-12.4.app/Contents/Developer/usr/bin/xcodebuild build SYMROOT= CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO PROVISIONING_PROFILE_SPECIFIER= -arch x86_64 -sdk iphonesimulator -configuration Debug

Build settings from command line:
    ARCHS = x86_64
    CODE_SIGN_IDENTITY = 
    CODE_SIGN_STYLE = Manual
    CODE_SIGNING_REQUIRED = NO
    PROVISIONING_PROFILE_SPECIFIER = 
    SDKROOT = iphonesimulator14.4
    SYMROOT = 

Resolve Package Graph

Resolved source packages:
  AppAuth: https://github.com/openid/AppAuth-iOS.git @ 1.6.0
  itwin-mobile-native: https://github.com/iTwin/mobile-native-ios @ 3.4.15


note: Using new build system
note: Using codesigning identity override: 
note: Planning build
note: Constructing build description
CreateBuildDirectory /Users/platform-bld/Library/Developer/Xcode/DerivedData/imodeljs-test-app-bhlwsrmhanwezuhhrciejzdennda/SourcePackages/checkouts/AppAuth-iOS (in target 'AppAuthCore' from project 'AppAuth')
    cd /Users/platform-bld/Library/Developer/Xcode/DerivedData/imodeljs-test-app-bhlwsrmhanwezuhhrciejzdennda/SourcePackages/checkouts/AppAuth-iOS
    builtin-create-build-directory /Users/platform-bld/Library/Developer/Xcode/DerivedData/imodeljs-test-app-bhlwsrmhanwezuhhrciejzdennda/SourcePackages/checkouts/AppAuth-iOS

WriteAuxiliaryFile /AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/AppAuthCore.modulemap (in target 'AppAuthCore' from project 'AppAuth')
    cd /Users/platform-bld/Library/Developer/Xcode/DerivedData/imodeljs-test-app-bhlwsrmhanwezuhhrciejzdennda/SourcePackages/checkouts/AppAuth-iOS
    write-file /AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/AppAuthCore.modulemap
error: unable to write file '/AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/AppAuthCore.modulemap': fopen(/AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/AppAuthCore.modulemap, wb): No such file or directory (2) (in target 'AppAuthCore' from project 'AppAuth')

WriteAuxiliaryFile /AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/Objects-normal/x86_64/AppAuthCore.o.LinkFileList (in target 'AppAuthCore' from project 'AppAuth')
    cd /Users/platform-bld/Library/Developer/Xcode/DerivedData/imodeljs-test-app-bhlwsrmhanwezuhhrciejzdennda/SourcePackages/checkouts/AppAuth-iOS
    write-file /AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/Objects-normal/x86_64/AppAuthCore.o.LinkFileList
error: unable to write file '/AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/Objects-normal/x86_64/AppAuthCore.o.LinkFileList': fopen(/AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/Objects-normal/x86_64/AppAuthCore.o.LinkFileList, wb): No such file or directory (2) (in target 'AppAuthCore' from project 'AppAuth')

** BUILD FAILED **


The following build commands failed:
	WriteAuxiliaryFile /AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/AppAuthCore.modulemap
	WriteAuxiliaryFile /AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/Objects-normal/x86_64/AppAuthCore.o.LinkFileList
(2 failures)
##[error]Bash exited with code '65'.
```

**Comment by calebmshafer** [comment]
> @calebmshafer @tcobbs-bentley @toddsouthenbentley it seems like dta iOS build fails intermittently. Looks like parallel builds may be trying to write to the same output directory `/AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/`?
> 
> ```
> > display-test-app@1.8.0 build:ios-app
> > cd ios/imodeljs-test-app && SYMROOT=`xcodebuild -showBuildSettings 2>/dev/null | egrep '^[ ]+BUILD_DIR' | sed 's/.Products$//; s/^[ ]*BUILD_DIR = //'` && xcodebuild build SYMROOT=${SYMROOT} CODE_SIGN_STYLE='Manual' CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO PROVISIONING_PROFILE_SPECIFIER='' -arch x86_64 -sdk iphonesimulator -configuration Debug
> 
> Command line invocation:
>     /Applications/Xcode-12.4.app/Contents/Developer/usr/bin/xcodebuild build SYMROOT= CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO PROVISIONING_PROFILE_SPECIFIER= -arch x86_64 -sdk iphonesimulator -configuration Debug
> 
> Build settings from command line:
>     ARCHS = x86_64
>     CODE_SIGN_IDENTITY = 
>     CODE_SIGN_STYLE = Manual
>     CODE_SIGNING_REQUIRED = NO
>     PROVISIONING_PROFILE_SPECIFIER = 
>     SDKROOT = iphonesimulator14.4
>     SYMROOT = 
> 
> Resolve Package Graph
> 
> Resolved source packages:
>   AppAuth: https://github.com/openid/AppAuth-iOS.git @ 1.6.0
>   itwin-mobile-native: https://github.com/iTwin/mobile-native-ios @ 3.4.15
> 
> 
> note: Using new build system
> note: Using codesigning identity override: 
> note: Planning build
> note: Constructing build description
> CreateBuildDirectory /Users/platform-bld/Library/Developer/Xcode/DerivedData/imodeljs-test-app-bhlwsrmhanwezuhhrciejzdennda/SourcePackages/checkouts/AppAuth-iOS (in target 'AppAuthCore' from project 'AppAuth')
>     cd /Users/platform-bld/Library/Developer/Xcode/DerivedData/imodeljs-test-app-bhlwsrmhanwezuhhrciejzdennda/SourcePackages/checkouts/AppAuth-iOS
>     builtin-create-build-directory /Users/platform-bld/Library/Developer/Xcode/DerivedData/imodeljs-test-app-bhlwsrmhanwezuhhrciejzdennda/SourcePackages/checkouts/AppAuth-iOS
> 
> WriteAuxiliaryFile /AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/AppAuthCore.modulemap (in target 'AppAuthCore' from project 'AppAuth')
>     cd /Users/platform-bld/Library/Developer/Xcode/DerivedData/imodeljs-test-app-bhlwsrmhanwezuhhrciejzdennda/SourcePackages/checkouts/AppAuth-iOS
>     write-file /AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/AppAuthCore.modulemap
> error: unable to write file '/AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/AppAuthCore.modulemap': fopen(/AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/AppAuthCore.modulemap, wb): No such file or directory (2) (in target 'AppAuthCore' from project 'AppAuth')
> 
> WriteAuxiliaryFile /AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/Objects-normal/x86_64/AppAuthCore.o.LinkFileList (in target 'AppAuthCore' from project 'AppAuth')
>     cd /Users/platform-bld/Library/Developer/Xcode/DerivedData/imodeljs-test-app-bhlwsrmhanwezuhhrciejzdennda/SourcePackages/checkouts/AppAuth-iOS
>     write-file /AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/Objects-normal/x86_64/AppAuthCore.o.LinkFileList
> error: unable to write file '/AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/Objects-normal/x86_64/AppAuthCore.o.LinkFileList': fopen(/AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/Objects-normal/x86_64/AppAuthCore.o.LinkFileList, wb): No such file or directory (2) (in target 'AppAuthCore' from project 'AppAuth')
> 
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	WriteAuxiliaryFile /AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/AppAuthCore.modulemap
> 	WriteAuxiliaryFile /AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/Objects-normal/x86_64/AppAuthCore.o.LinkFileList
> (2 failures)
> ##[error]Bash exited with code '65'.
> ```

@pmconne not sure. There shouldn't be anything running in parallel with that specific stage step so not sure why it's happening. I'll take a look but let's for now skip this part to get the rest of these changes going. Too many things are blocked at the moment.

**Comment by pmconne** [comment]
> let's for now skip this part to get the rest of these changes going. Too many things are blocked at the moment.

I'll do that in #4318 unless you object, that one's otherwise ready to merge.

**Comment by calebmshafer** [comment]
> > let's for now skip this part to get the rest of these changes going. Too many things are blocked at the moment.
> 
> I'll do that in #4318 unless you object, that one's otherwise ready to merge.

@pmconne that's fine with me.

**Pull request merged**
