### PR TITLE
exportGraphics: new option to export raw uv-parameters

### PR DESCRIPTION
**Pull request by dassaf4**
Add `ExportGraphicsOptions.exportRawParameters` and `ExportPartGraphicsOptions.exportRawParameters` to enable export of "raw" uv-parameters, unmodified by texture-controlled scaling and v-inversion.

imodel-native: https://github.com/iTwin/imodel-native/tree/da4/export-graphics-raw-uv

### CODE REVIEW

**Comment by aruniverse** [comment]
@dassaf4 shouldnt this be targeting the `imodel02` branch?

**Comment by dassaf4** [comment]
> @dassaf4 shouldnt this be targeting the `imodel02` branch?

Of course, this makes sense. I didn't see this detail on the "imodel-native PR Validation" wiki. Should I close this one and start a new PR?

**Review by ben-polinsky — APPROVED** [review]

**Comment by aruniverse** [comment]
> > @dassaf4 shouldnt this be targeting the `imodel02` branch?
> 
> Of course, this makes sense. I didn't see this detail on the "imodel-native PR Validation" wiki. Should I close this one and start a new PR?

I was able to retarget the pr, but looks like you shouldve probably branched off of the imodel02 branch first. Might need to recreate the pr/branch

**Comment by dassaf4** [comment]
Closing due to wrong branch base.

**Pull request closed without merging**
