### PR TITLE
Add support for API keys to DTA Android

### PR DESCRIPTION
**Pull request by tcobbs-bentley**

### CODE REVIEW

**Review by pmconne — APPROVED** [review]

**Review by toddsouthenbentley — APPROVED** [review]

**Comment by tcobbs-bentley** [comment]
@aruniverse Tests are failing in the pipeline. I reran the failing jobs, and they failed again.

**Comment by pmconne** [comment]
> Tests are failing in the pipeline.

Backporting #5661.

**Comment by pmconne** [comment]
Uh looks like 3.7.x is supposed to use node 14...gonna need a yaml person - sorry @aruniverse.

**Comment by aruniverse** [comment]
+ @DanRod1999 to take a look

**Comment by DanRod1999** [comment]
> should node 14 only be used on this release/3.7.x branch, and if so can we make that change in fast-ci.yaml in this PR to avoid creating another PR and merging into here @aruniverse or @pmconne?
Changes here
https://github.com/iTwin/itwinjs-core/pull/5674

**Review by markschlosseratbentley — APPROVED** [review]

**Pull request merged**
