### PR TITLE
Update xml2js

### LINKED ISSUE #5373: Update @azure/storage-blob for xml2js CVE
[xml2js CVE](https://github.com/advisories/GHSA-776f-qx25-q3cc) affects current releases of @azure/storage-blob.
[@azure issue](https://github.com/Azure/azure-sdk-for-js/issues/25499)
Temporarily ignored in #5372. Revert that change once a patched release becomes available.

### PR DESCRIPTION
**Pull request by pmconne**
Fixes #5373.

### CODE REVIEW

**Comment by pmconne** [comment]
Danabbit.
```
ERROR: HIGH Security Vulnerability: xml2js is vulnerable to prototype pollution  in xml2js (from ..__..__full-stack-tests__backend>@itwin/imodels-client-authoring>@azure/storage-blob>@azure/core-http>xml2js).  See https://github.com/advisories/GHSA-776f-qx25-q3cc for more info.
```

**Comment by aruniverse** [comment]
we mostly need to wait for azurite to update, which has a dep on the older xml2js. they merged a pr to update yesterdya, just waiting for them to release

**Comment by aruniverse** [comment]
can either close this pr/branch, or wait to update once azurite gets updated next qtr. going to draft for now

**Comment by pmconne** [comment]
> can either close this pr/branch, or wait to update once azurite gets updated next qtr

We're tracking the issue, closing this PR.

**Pull request closed without merging**
