### PR TITLE
Add setup for testing Electron backend code

### PR DESCRIPTION
**Pull request by GytisCepk**
## Introduction

PR purpose is to add setup for testing *core-electron* backend code.

Requirements for setup:
- Tests must run in Electron main process.
- `ElectronHost.startup` tests should be run on separate process due to `ElectronHost.startup` being static and having multiple side effects. This requirement could be emitted if we decide to add `ElectronHost.shutdown`.

## Suggested solution

Suggested setup launches new child process for every single test.

Main problem with this approach is execution time. Single test takes ~950ms on average (~1400ms if debugger attached) on laptop (i9-9880H). Most of the execution time seems to be spent loading modules.

## Rejected frameworks

Multiple frameworks exists to test Electron but non where used:
- **Spectron** - [deprecated](https://github.com/electron-userland/spectron#readme).
- **Selenium** and **WebDriverIO** - e2e testing, doesn't seem to support testing on Electron main process.
- **Playwright** - mainly for e2e testing. It does have [`electronApplication.evaluate`](https://playwright.dev/docs/api/class-electronapplication#electron-application-evaluate) which allows to execute code in Electron main process, but, since it losses context and doesn't allow imports, it isn't enough to test `ElectronHost`.
- **electron-mocha** - unlike Mocha, it runs on Electron rather than Node. Problem is that it doesn't restart electron process after each test and that makes `ElectronHost.startup` testing "difficult".

### CODE REVIEW

**Comment by calebmshafer** [comment]
@GytisCepk this looks good so far and is what I had in mind.

FYI, @ben-polinsky to take a look and provide feedback/opinions here.

**Comment by ben-polinsky** [comment]
Sorry for the delay here.

Yeah, this is an annoying problem which has been "unsolved" due to Spectron's deprecation.[ Cypress at one point ](https://www.cypress.io/blog/2019/09/26/testing-electron-js-applications-using-cypress-alpha-release/) was going to add electron support - but that's gone away. [They say they are "stubbing events" from electron, but the link they provide is dead.](https://docs.cypress.io/faq/questions/using-cypress-faq#Can-I-test-my-Electron-app) 

I assume pure unit testing would be tough because we'd have to create a bunch of flexible spies/mocks for internal electron behavior (like ipc/app and window events/etc)?

This does seem close to E2E testing, but poking and prodding at the internals of the app. Is there no way to gain the testing confidence we need by manipulating/watching public APIs?

**Comment by GytisCepk** [comment]
> I assume pure unit testing would be tough because we'd have to create a bunch of flexible spies/mocks for internal electron behavior (like ipc/app and window events/etc)?

Intension was to have integrations tests rather than unit tests and there are several reasons for that:
- Integrations tests should allow us to feel safer when adding support for newer Electron versions.
- `core-electron` is very tightly coupled with Electron, so I don't see much point in mocking Electron.

> This does seem close to E2E testing, but poking and prodding at the internals of the app. Is there no way to gain the testing confidence we need by manipulating/watching public APIs?

You mean could we avoid running tests in separate processes and rather have something like `ElectronHost.shutdown` (like `ElectronApp.shutdown`) ? I don't like this approach because:
- From API side it doesn't make since to me to have `ElectronHost.shutdown`.
- As #4245 shown, it is hard to clean up all side effects and it might end up effecting other tests.

**Comment by ben-polinsky** [comment]
> > I assume pure unit testing would be tough because we'd have to create a bunch of flexible spies/mocks for internal electron behavior (like ipc/app and window events/etc)?
> 
> Intension was to have integrations tests rather than unit tests and there are several reasons for that:
> 
> * Integrations tests should allow us to feel safer when adding support for newer Electron versions.
> * `core-electron` is very tightly coupled with Electron, so I don't see much point in mocking Electron.
> 
> > This does seem close to E2E testing, but poking and prodding at the internals of the app. Is there no way to gain the testing confidence we need by manipulating/watching public APIs?
> 
> You mean could we avoid running tests in separate processes and rather have something like `ElectronHost.shutdown` (like `ElectronApp.shutdown`) ? I don't like this approach because:
> 
> * From API side it doesn't make sense to me to have `ElectronHost.shutdown`.
> * As [Fix `ElectronApp.shutdown` causing tests to crash #4245](https://github.com/iTwin/itwinjs-core/pull/4245) shown, it is hard to clean up all side effects and it might end up effecting other tests.

That all makes sense to me.

**Review by ben-polinsky — APPROVED** [review]

**Comment by pmconne** [comment]
Please run `rush change` so reviewers can see if builds succeed.

**Comment by pmconne** [comment]
Is it intended that these tests will only ever be run manually (e.g., when upgrading Electron or intentionally changing core-electron)? Or, should they run as part of PR validation to catch unexpected regressions?

**Comment by pmconne** [comment]
> Right now idea is to run them manually on any core-electron changes. Even simple test takes ~1 sec (on local PC) and, once more tests are written, it will noticeable slow down PR validations.

A few extra seconds spent running integration tests per PR might be preferable to, in the event of a regression, the time required for a developer to track down what caused it.
@calebmshafer what do you think?

**Comment by ben-polinsky** [comment]
> > Right now idea is to run them manually on any core-electron changes. Even simple test takes ~1 sec (on local PC) and, once more tests are written, it will noticeable slow down PR validations.
> 
> A few extra seconds spent running integration tests per PR might be preferable to, in the event of a regression, the time required for a developer to track down what caused it. @calebmshafer what do you think?

I tend to agree. Even 50 tests/+1 minute seems worth it. Would these be run in the integration or "main" build(s)?

**Comment by pmconne** [comment]
> Would these be run in the integration or "main" build(s)?

Integration.

**Comment by ben-polinsky** [comment]
> > Would these be run in the integration or "main" build(s)?
> 
> Integration.

Even better.

**Review by pmconne — APPROVED** [review]

**Comment by pmconne** [comment]
@GytisCepk can you add the tests to [integration-test-steps.yaml](https://github.com/iTwin/itwinjs-core/blob/master/common/config/azure-pipelines/templates/integration-test-steps.yaml)?

**Comment by calebmshafer** [comment]
@pmconne FWIW, I agree that putting it in integration makes sense. Let's see how much time it adds and we can always re-factor later if it's too much but for now ensuring that we don't accidentally break it will be the priority.

**Comment by ben-polinsky** [comment]
@calebmshafer @GytisCepk I did approve yesterday so someone else is needed :)

**Review by calebmshafer — APPROVED** [review]

**Pull request merged**
