### PR TITLE
Add camera paths to display-test-app

### PR DESCRIPTION
**Pull request by TitouanLeDuigou**
This PR adds the support for camera paths in display-test-app. It allows users to record, load, save and play camera animations. This feature is for testing purposes.

A new dropdown menu next to the "saved views" button is added. In this menu, the user can create a camera path by writing its name and pressing "``Enter``" or the "``Create``" button. The path created is empty and should be recorded by pressing the "record" button. To stop the recording, press the "``Stop``" button. A non-empty path can be played using the "``Play``" button.

Camera paths are automatically saved in a ``.json`` file, similarly to saved views. It is also loaded with the iModel.

Paths are composed of keyframes interpolated linearly. They support orthographic and perspective camera with different zoom levels and lens angles. Camera paths for views that are too far from the surface are not supported.

### CODE REVIEW

**Comment by pmconne** [comment]
@MarcNeely would you mind reviewing please?

**Comment by MarcNeely** [comment]
When walking around in walk mode it seems to work really well.  When zooming out with the mouse wheel however it does not seem to capture/replay that correctly and does not zoom out as much.

**Comment by TitouanLeDuigou** [comment]
> When zooming out with the mouse wheel however it does not seem to capture/replay that correctly and does not zoom out as much.



Currently, working with global views when we zoom too far is not supported. Recording/Playing camera paths in these situations gives incorrect results.


For debug in display-test-app, we considered this a sufficient first step. Supporting global view would require more work. Is this something that we must do in this PR?

**Review by MarcNeely — APPROVED** [review]

**Comment by TitouanLeDuigou** [comment]
> No. Just make sure to document the limitation somewhere.

I added a TODO in the code in the recording and replaying functions. Is it enough or should it be documented somewhere else?

> That's fine about the global views, but I wasn't zooming out that much. Just enough to fit the whole model (a small house) in the view.

This is not supposed to happen when dezooming a little indeed. Do you have any way to reproduce this behavior so I can investigate it?

**Comment by pmconne** [comment]
@Mergifyio update

**Pull request merged**
