### PR TITLE
glTF instancing, plus bounding box fixes

### LINKED ISSUE #5937: glTF Bounding Box misaligned
**Describe the bug**
The [gltfGraphics](https://www.itwinjs.org/reference/core-frontend/tiles/gltfgraphic/) has 2 properties related to the bounding box. 
 `boundingBox`, aligned in world space (Up axis Z) & `localBoudingBox`, aligned to the graphic's local space (Up axis Y).  I would expect the boundingBox range tightly bound the graphics.

**To Reproduce**

1. Call [readGlft](https://www.itwinjs.org/reference/core-frontend/tiles/readgltf) (See this [Sandbox](https://www.itwinjs.org/sandboxes/NathanElrod/bound-gltf) for more details about this step)
(This is easier to talk about this visually, so I will include steps the steps I took to draw this in the viewport)
3. Convert boundingBox (Range3d) into a RenderGraphics (I used [Box.createRange](https://www.itwinjs.org/reference/core-geometry/solid/box/createrangestatic/) to ensure there were no misalignment issues from possible transforms on a AA Range)
4. Draw both graphics and BB returned from `readGltf` with a decorator.
5. Observe that the bounding box does not align with the graphics.

I included [3 gltf sample models](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0) in the sandbox:
1. Duck: Massive BB relative to model, and underneath model.
3. CesiumMilkTruck: BB is slightly larger than the model, and oriented differently than others.
4. Fox: Correctly sized BB and underneath model.

**Expected behavior**
I would expect gltfGraphics.boundingBox object to align with the gltf graphics.

**Screenshots**
image

- OS: widows 10
- Browser chrome
- Version 115.0.5790.171
- iTwin.js Version 4.0.0

**Additional context**
My limited testing included about 10 sample gltf models.  Although the models included in the sandbox do not reflect it, the bounding box was _usually_ the correct size, but oriented incorrectly.  The orientation was _usually_ correctable by rotating 180 along the X axis.

### LINKED ISSUE #6378: Support EXT_mesh_gpu_instancing
**Is your feature request related to a problem? Please describe.**
glTF 2.0 supports instanced geometry via the [EXT_mesh_gpu_instancing](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Vendor/EXT_mesh_gpu_instancing/README.md) extension. iTwin.js does not currently support this extension. iTwin Experience folks intend to use it.

**Describe the solution you'd like**
glTF utilizing this extension should decode and render correctly.

**Describe alternatives you've considered**
Require people to use 3D Tiles 1.0 i3dm format for instanced geometry. This would not work for plain glTF models, and is superseded in 3D Tiles 1.1 by the much more straightforward extension.

**Additional context**
[This glTF model](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/SimpleInstancing) can be used to test basic conformance.

### PR DESCRIPTION
**Pull request by pmconne**
Fixes #6378 by adding support for the glTF 2.0 instancing extension described in the issue. It successfully renders the model referenced in the issue.

Fixes #5937. Fixes https://github.com/iTwin/itwinjs-backlog/issues/969. Both relate to incorrect bounding boxes computed for glTF models. For unclear reasons we were applying inverse transforms to the bounding boxes.

TODO:
- [x] Investigate and fix model drawing black instead of white
  - Good ol' white-on-white reversal...
- [x] Run ImageTests and evaluate results
  - Similar inconcsistent pixel diffs as occur on master
- [x] Remove debug bounding box graphic

### CODE REVIEW

**Comment by pmconne** [comment]
@alarkbentley @Ellord207 FYI.

**Comment by pmconne** [comment]
Blocked by #6380.

**Comment by pmconne** [comment]
```
  1) GltfReader
       computes bounding boxes:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (agent/_work/1/s/core/frontend/src/test/tile/GltfReader.test.ts:383:78)
```

**Review by markschlosseratbentley — APPROVED** [review]
Looks good to me.

**Pull request merged**
