### PR TITLE
@bentley/imodeljs-native 3.5.13

### PR DESCRIPTION
**Pull request by skirby1996**

### CODE REVIEW

**Comment by aruniverse** [comment]
@khanaffan just want to confirm we wanted to backport the SQlite upgrade to 3.40.0 to the imodel-native@3.5.x release

**Comment by aruniverse** [comment]
I merged the changes from https://github.com/iTwin/itwinjs-core/pull/4825 into this branch to get tests to pass

**Comment by aruniverse** [comment]
@grigasp not sure if the following test failure is transient or not. Re-running since it passed on windows & mac. Just wanted to bring to your attention 

https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=1892618&view=logs&j=0aa84d8c-14fd-5636-fb46-99be2362d8e1&t=234e5986-45f5-5876-92cf-d939451fbda1&l=28757

**Review by calebmshafer — APPROVED** [review]

**Comment by khanaffan** [comment]
> @khanaffan just want to confirm we wanted to backport the SQlite upgrade to 3.40.0 to the [imodel-native@3.5.x](mailto:imodel-native@3.5.x) release

yes, it's included.

**Comment by grigasp** [comment]
> @grigasp not sure if the following test failure is transient or not. Re-running since it passed on windows & mac. Just wanted to bring to your attention 
> 
> https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=1892618&view=logs&j=0aa84d8c-14fd-5636-fb46-99be2362d8e1&t=234e5986-45f5-5876-92cf-d939451fbda1&l=28757

Thanks. This is a known issue, which is already fixed on master.

**Pull request merged**
