### PR TITLE
Promote ECSqlReader to public

### LINKED ISSUE #5569: Take ECSqlReader out of beta
Discuss what is left to do (if anything) before we can make ECSqlReader public, make those changes, then make it public.

### PR DESCRIPTION
**Pull request by mattbjordan**
Resolves #5569 

@khanaffan Please give the ECSqlReader API a final look for any necessary changes before this PR gets completed and ECSqlReader is officially out of beta.

### CODE REVIEW

**Comment by mattbjordan** [comment]
@khanaffan I feel like I should point out two things: 1. Everything from ECSqlReader.ts is no longer marked as beta. 2. I took QueryPropertyMetaData from ConcurrentQuery.ts out of beta since it is directly used by ECSqlReader. There are other things from ConcurrentQuery.ts that are still in beta.

**Review by aruniverse — DISMISSED** [review]
so youre promoting it to `public`?

why not just say that?

**Comment by mattbjordan** [comment]
> so youre promoting it to `public`?
> 
> why not just say that?

Because I couldn't think of the better wording 😄  and didn't even initially tag the code as public... I've now reworded the change comments and properly marked things as public.

**Comment by aruniverse** [comment]
@khanaffan  plz review pr

**Review by khanaffan — APPROVED** [review]

**Review by aruniverse — APPROVED** [review]

**Pull request merged**
