### PR TITLE
Granularized GeoServices tests so we know which one is failing

### PR DESCRIPTION
**Pull request by AlainRobertAtBentley**
Simple restucturing of GeoServices tests.

### CODE REVIEW

**Review by pmconne — COMMENTED** [review]
Does it still test all the same things it did previously?

**Comment by AlainRobertAtBentley** [comment]
> It is exactly the same tests but I put individual it() tests in a describe() grouping instead. The diff is horrible and you cannot see the actual changes.

**Comment by pmconne** [comment]
Diff is much more readable if you ignore whitespace. Append "?w=1" like [this](https://github.com/iTwin/itwinjs-core/pull/4107/files?w=1).
Or install [chrome extension](https://chrome.google.com/webstore/detail/github-whitespace/fnpkdafamnbjoldglihkjjdicofghccm/related?hl=en-US) to automatically do it for all diffs.

**Review by pmconne — APPROVED** [review]

**Comment by AlainRobertAtBentley** [comment]
@Mergifyio update

**Pull request merged**
