### PR TITLE
Update test app docs

### PR DESCRIPTION
**Pull request by calebmshafer**
Fixed an env. var that was incorrect in the template and added info for debugging ui-test-app.

### CODE REVIEW

**Review by NancyMcCallB — APPROVED** [review]

**Review by bsteinbk — COMMENTED** [review]
I pulled but this has not helped me open a hub file... in fact I am now seeing an invalid URL error.

**Comment by calebmshafer** [comment]
> I pulled but this has not helped me open a hub file... in fact I am now seeing an invalid URL error.

@bsteinbk, yea... This PR didn't really do anything to fix ui-test-app. I'm currently getting 3-4 different errors I'm trying to untangle. At least one of them is an issue with the Electron auth client but I think the others are directly in ui-test-app setup issues.

**Comment by bsteinbk** [comment]
> > I pulled but this has not helped me open a hub file... in fact I am now seeing an invalid URL error.
> 
> @bsteinbk, yea... This PR didn't really do anything to fix ui-test-app. I'm currently getting 3-4 different errors I'm trying to untangle. At least one of them is an issue with the Electron auth client but I think the others are directly in ui-test-app setup issues.

@calebmshafer - I was able to finally get a file from QA to open if added the scope "imodels:read", which is not listed in readme.

**Comment by calebmshafer** [comment]
@Mergifyio update

**Comment by calebmshafer** [comment]
> @calebmshafer - I was able to finally get a file from QA to open if added the scope "imodels:read", which is not listed in readme.

thanks @bsteinbk, updated.

**Pull request merged**
