### PR TITLE
Support showing AccuDraw input fields in a popup at the cursor.

### PR DESCRIPTION
**Pull request by bbastings**
Added method that is called when AccuDraw compass display changes.

### CODE REVIEW

**Review by mathieu-fournier — APPROVED** [review]

**Review by pmconne — CHANGES_REQUESTED** [review]
It would be bad if somebody directly set `currentState` instead of calling `setCurrentState`, right? If so, can you do something to prevent or discourage that?

**Comment by bbastings** [comment]
@pmconne Like what, it's public? Same issue with compassMode and rotationMode. Pretty much relying on the class documentation saying not to call this stuff directly here...

**Comment by mathieu-fournier** [comment]
Why not add public get private set ?

**Comment by bbastings** [comment]
> Why not add public get private set ?

That's a breaking change...

**Comment by pmconne** [comment]
> > Why not add public get private set ?
> 
> That's a breaking change...

You could change`currentState` to a getter+setter, move your `setCurrentState` logic to the setter, delete `setCurrentState`.

**Comment by bbastings** [comment]
> You could changecurrentState to a getter+setter, move your setCurrentState logic to the setter, delete setCurrentState.
@pmconne Done. Didn't think this was a good idea, but since we do it in other setters...

**Review by mathieu-fournier — APPROVED** [review]

**Review by pmconne — APPROVED** [review]

**Pull request merged**
