### PR TITLE
Update BlobContainer.TokenProps interface

### PR DESCRIPTION
**Pull request by YashodipD**
ContainerService.requestToken() returns TokenProps, inside the TokenProps, base uri seems to be missing. 

base uri points to the location where the actual workspace container lives, it is required for every operation. Internal api (storage-container) also return base uri, we just need to expose it through interface and add it to response.

### CODE REVIEW

**Comment by YashodipD** [comment]
fixex https://github.com/iTwin/itwinjs-core/issues/7139

**Comment by YashodipD** [comment]
I made it optional so no breaking change will be introduced.

**Comment by kabentley** [comment]
I'm not sure where/why you need this (the caller to `requestToken` must supply it), but making it optional makes it useless. The whole interfaces is @beta, I'd just add it.

**Comment by YashodipD** [comment]
I am creating a `client` using `BlobContainerService` which calls `requestToken`. BlobContainerService accepts baseUrl, It is optional. I think url accepted by BlobContainerService is used to fetch information about `storage-container` api and the base uri which I am looking for is the url of actual blob container (https://xyz.blob.core.windows.net).

**Review by pmconne — APPROVED** [review]

**Pull request merged**
