### PR TITLE
Bugfix/window area with aspect ratio skew

### PR DESCRIPTION
**Pull request by a-gagnon**
This fixes an issue with the window area tool that previously ignored the aspectRatioSkew.

Please refer to the 'before' and 'after' videos that show the behavior with aspectRatioSkew = 1 and aspectRatioSkew = 5.

https://github.com/iTwin/itwinjs-core/assets/3418768/658c7810-5da1-42e5-b377-f1ffd543260e

https://github.com/iTwin/itwinjs-core/assets/3418768/5242e2ad-45ee-4173-a39c-6b0014c4b87b

### CODE REVIEW

**Review by pmconne — APPROVED** [review]

**Comment by pmconne** [comment]
Thanks for the fix @a-gagnon.

@aruniverse Errors like the following have been showing up on macOS recently. Presumably #5681 will banish them.
```
2023-06-23T02:01:16.3523840Z --[ FAILURE: core-full-stack-tests ]------------------------[ 34.94 seconds ]--
2023-06-23T02:01:16.3524070Z 
2023-06-23T02:01:16.3524420Z Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r1022525 is guaranteed to work.
2023-06-23T02:01:16.3524950Z TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r1022525 is guaranteed to work.
2023-06-23T02:01:16.3525800Z     at Timeout.onTimeout (/Users/platform-bld/vsts_work_a/1/s/common/temp/node_modules/.pnpm/puppeteer@15.5.0/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:300:20)
2023-06-23T02:01:16.3526360Z     at listOnTimeout (node:internal/timers:569:17)
2023-06-23T02:01:16.3526750Z     at process.processTimers (node:internal/timers:512:7)
2023-06-23T02:01:16.3526960Z 
2023-06-23T02:01:16.3527380Z --[ FAILURE: rpc-full-stack-tests ]-------------------------[ 35.68 seconds ]--
2023-06-23T02:01:16.3527590Z 
2023-06-23T02:01:16.3527960Z Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r1022525 is guaranteed to work.
2023-06-23T02:01:16.3528480Z TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r1022525 is guaranteed to work.
2023-06-23T02:01:16.3529420Z     at Timeout.onTimeout (/Users/platform-bld/vsts_work_a/1/s/common/temp/node_modules/.pnpm/puppeteer@15.5.0/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:300:20)
2023-06-23T02:01:16.3530340Z     at listOnTimeout (node:internal/timers:569:17)
2023-06-23T02:01:16.3530730Z     at process.processTimers (node:internal/timers:512:7)
```

**Review by bbastings — APPROVED** [review]

**Review by markschlosseratbentley — APPROVED** [review]
Awesome, thanks @a-gagnon!

**Comment by aruniverse** [comment]
@a-gagnon did you need this in a 4.0 patch?

@pmconne yea noticed that as well yesterday. Hoping the linked PR will fix it.

**Comment by a-gagnon** [comment]
> @a-gagnon did you need this in a 4.0 patch?
> 
> @pmconne yea noticed that as well yesterday. Hoping the linked PR will fix it.

Hey Arun. Thanks for asking. This is a minor inconvenience and I think we're fine waiting on the next minor version.

**Pull request merged**
