### PR TITLE
Prefer `Set` in `sortChildrenBeforeParents`

### PR DESCRIPTION
**Pull request by jackson-at-bentley**
Assuming `ECInstanceId`'s are unique among definition elements, I think we should be using a set to sort a bag of definition elements into their breadth-first ordering. In the worst-case scenario your iModel contains definition elements arranged in a linked list, and so this reduces the time complexity of `sortChildrenBeforeParents` from $O(n^3)$ to $O(n^2) $, `n === ids.length`.

I've also added a failing test for nested definition models. If we attempt to delete all deferred definition elements first, and any of those definition elements are modeled, the backend gets upset because the model's `ModeledElement` navigation property is still pointing to its modeled element.

### CODE REVIEW

**Comment by pmconne** [comment]
@swwilson-bsi mind reviewing?

**Comment by swwilson-bsi** [comment]
@jackson-at-bentley You are quite right about sort algorithm performance.
However, rather than improve sortChildrenBeforeParents, we really should delete it.
What I mean is that sortChildrenBeforeParents is a work-around for a bug in Elements.deleteDefinitionElements (as explained in the comment). My fault for writing a work-around instead of fixing the real bug. The fix should be very simple. deleteDefinitionElements just needs to not blow up when it comes to an already-deleted element. (If the list of elements passed to deleteDefinitionElements includes both child elements and their parents, then deleteDefinitionElements may delete the parents first. That will cause the child elements to be deleted as a side-effect. When deleteDefinitionElements moves on to the already-deleted child elements, it just needs to avoid deleting them.)

I will look at the failing test with the sub-modeled definition element. Thanks for teeing up that scenario.

**Comment by pmconne** [comment]
@jackson-at-bentley @swwilson-bsi should this PR be pursued, or closed?

**Comment by pmconne** [comment]
> However, rather than improve sortChildrenBeforeParents, we really should delete it.
What I mean is that sortChildrenBeforeParents is a work-around for a bug in Elements.deleteDefinitionElements (as explained in the comment). My fault for writing a work-around instead of fixing the real bug.

Based on this comment and inactivity I'm closing this PR.
@swwilson-bsi please follow up if the underlying bug still needs to be addressed.

**Pull request closed without merging**
