### PR TITLE
Fix spelling for MapLayerSettingsService.test.ts

### PR DESCRIPTION
**Pull request by stuartpb**

### CODE REVIEW

**Review by bsteinbk — APPROVED** [review]

**Review by calebmshafer — APPROVED** [review]

**Review by mdastous-bentley — APPROVED** [review]

**Comment by stuartpb** [comment]
@calebmshafer I can do a `rush change`, but is that called for here? As I understand it, `rush change` creates data for changelogs - a one-character fix to the name of one of the test files has no user-facing impact, and adding a note about it to the changelog seems like it'd just add noise.

**Comment by aruniverse** [comment]
> seems like it'd just add noise.

Yea you're right that we don't need to explicitly mention the file rename in the changelogs. You should be able to create an empty change log message. We just need the `rush change` to create the changelog for the CI to succeed.

**Review by MarcBedard8 — APPROVED** [review]

**Comment by calebmshafer** [comment]
> Commit amended and repushed.

@stuartpb would you be able to resolve the merge conflict?

**Comment by calebmshafer** [comment]
closing in favor of #3987

**Pull request closed without merging**
