### PR TITLE
Reduce memory footprint for edges

### PR DESCRIPTION
**Pull request by pmconne**
Our current representation of edges requires excessive memory, both on the GPU and in the tiles. Each segment expands into a quad; each of the six vertices of each quad carries a bunch of redundant data.
Switch to storing the information about each edge in a lookup table and associating only a 24-bit index into that table with each vertex. We refer to these as "indexed edges".
The edge table is partitioned such that hard edges are in the bottom partition, silhouettes in the upper. The vertex shader identifies silhouettes by comparing edge index to the size of the lower partition. The lookup table is tightly packed, consisting of:
- For each hard edge, a pair of 24-bit indices into the vertex table for  the endpoints (6 bytes total).
- For each silhouette edge, the pair of 24-bit indices plus 2 16-bit oct-encoded normals (10 bytes total).

Incidentally this also permits us to draw all edges (silhouettes and hard edges) using a single draw call instead of two. The "quad index" attribute is inferred from `gl_VertexID`.
In 3d, polyline edges are converted to hard edges if their line weight is < 4, as before - no changes have been made.
Note: Indexed edges are only supported in WebGL 2 because (1) they use gl_VertexID and (2) WebGL 1 only guarantees (and iOS only delivers) 8 texture units - we need one for the lookup table.

Comparison:

| Edge type | Per-edge (old) | Per-edge (new) | Reduction |
|-----------|----------------|----------------|---------|
| Silhouette| 66 bytes       | 28 bytes       | 58%     |
| Hard      | 42 bytes       | 24 bytes       | 43%     |

TODO:
- ~Update tile generator to produce indexed edges, and reader to deserialize them.~ DONE.
- ~Add TileAdmin option and tile tree flag to control whether indexed edges are requested.~ DONE.
- ~Performance comparison.~ DONE.
- ~Memory / tile size comparison.~ DONE.
- ~Run ImageTests.~ DONE.
- ~Possibly default to always requesting edges, if memory usage in real-world data sets is sufficiently reduced to warrant it.~ Still too much additional data required for edges to justify always requesting them.
- ~Notify @wgoehrig and @paulius-valiunas of changes to default tile options for tile agents.~ DONE.
- ~Ensure `RenderOrder.Silhouette` is output to pick buffers for silhouettes.~ DONE.

### CODE REVIEW

**Review by mgooding — APPROVED** [review]

**Review by markschlosseratbentley — APPROVED** [review]

**Comment by MarcNeely** [comment]
You added something to turn this on and off for display-test-app, but what about display-performance-test-app?  Do you think we need to be able to toggle this there?

**Comment by pmconne** [comment]
>  what about display-performance-test-app? Do you think we need to be able to toggle this there?

Using an environment variable? I don't think so. You can override TileAdminProps.enableIndexedEdges in your dpta config.

**Comment by MarcNeely** [comment]
> > what about display-performance-test-app? Do you think we need to be able to toggle this there?
> 
> Using an environment variable? I don't think so. You can override TileAdminProps.enableIndexedEdges in your dpta config.

Yes, I don't think environment variables would work & I wasn't suggesting that.  What I meant was whether something like the override of enableIndexedEdges would work.  Do you think that we need to flag this in the file name of the generated images (I would guess not since I'm assuming that there should be no difference in them)?

**Comment by pmconne** [comment]
>  whether something like the override of enableIndexedEdges would work.

It will.

> Do you think that we need to flag this in the file name of the generated images?

We should add something to the filename if the feature is disabled, yes.

**Comment by pmconne** [comment]
@MarcNeely display-performance-test-app will now add "-idxEdg" to the filename if the config sets TileAdminProps.enableIndexedEdges to false.

**Review by Ellord207 — APPROVED** [review]

**Pull request merged**
