### PR TITLE
Expose MapLayerImageryProvider

### PR DESCRIPTION
**Pull request by mdastous-bentley**

### CODE REVIEW

**Review by pmconne — COMMENTED** [review]
`extract-api`, `rush change`.

What can someone do with this API and where is that explained in the docs?

**Comment by mdastous-bentley** [comment]
@pmconne Actually I created this PR early to kick off a discussion about what should be exposed in MapLayerImageryProvider.  For instance, `getToolTip()` references `ImageryMapTileTree`... I dont think we want to expose `ImageryMapTileTree`.  If you look closely, the tree object is passed to providera to get access to the `tilingScheme` property.   

That makes me realize that passing a `QuadId` object to a provider without information about its tiling scheme is like passing a length value without its units of measure, which forces the providers to assume stuff about the tile scheme (i.e. `loadTile `method) What do think of including tilescheme part of a QuadId object ? 

Also some providers uses custom tiling schemes, which might (or not) be compatible with the tile scheme usedby iTwinjs.  We currently have work around methods in some providers to check for example if a tile scheme is web mercator compatible, I think we should get this code out of providers as much as possible, so that newly created providers can benefit from the existing functionality.

**Comment by pmconne** [comment]
@mdastous-bentley deciding what should be exposed requires defining what you expect to enable people to do.

**Comment by mdastous-bentley** [comment]
> @mdastous-bentley deciding what should be exposed requires defining what you expect to enable people to do.

I think, anyone should be able to provide its own map imagery format, and its associated provider.  So anything used currently by map-layers-format should be made accessible.

**Pull request closed without merging**
