### PR TITLE
@bentley/imodeljs-native 3.4.20

### PR DESCRIPTION
**Pull request by pmconne**
Includes backports of #4516 and #4521.
Addresses [xmldom vulnerability](https://github.com/advisories/GHSA-9pgh-qqpf-7wqj).

### CODE REVIEW

**Comment by pmconne** [comment]
@aruniverse @MichaelBelousov blocked by #4524, do you have a specific plan to address it?

**Comment by aruniverse** [comment]
> @aruniverse @MichaelBelousov blocked by #4524, do you have a specific plan to address it?

Could you apply the [same change](https://github.com/iTwin/itwinjs-core/commit/5034a62c1b60cf10cd9b7188c700c0445e193977) for the time being?

**Comment by pmconne** [comment]
@aruniverse is testing in progress?

**Comment by aruniverse** [comment]
> @aruniverse is testing in progress?

yes. im deploying gob to dev rn with 3.5.0-dev.22, and then to qa, and then will test out some of the perf models to verify

**Pull request merged**
