### PR TITLE
Fix new tiles not updating planar clip mask immediately

### PR DESCRIPTION
**Pull request by MarcNeely**
This fixes a problem where the planar clip mask was not getting updated immediately after some changes which effected it for new tiles.  This only occurred in certain modes of masking.

Fixes issue https://github.com/iTwin/itwin-graphics-backlog/issues/284

### CODE REVIEW

**Comment by MarcNeely** [comment]
ImageTest in progress...

**Comment by DStradley** [comment]
ImageTest passed.

**Review by pmconne — APPROVED** [review]

**Comment by MarcNeely** [comment]
@Mergifyio backport release/4.7.2

**Comment by MarcNeely** [comment]
@Mergifyio backport release/4.7.x

**Pull request merged**
