### PR TITLE
Update to imodeljs-native@3.3.1

### PR DESCRIPTION
**Pull request by calebmshafer**

### CODE REVIEW

**Comment by pmconne** [comment]
Were there merge issues or should @MichaelBelousov take a look?
```
--[ FAILURE: @itwin/core-transformer ]-------------[ 5 minutes 16.6 seconds ]--

src/test/IModelTransformerUtils.ts(702,36): error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.
src/test/IModelTransformerUtils.ts(703,36): error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.
src/test/IModelTransformerUtils.ts(704,36): error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.
src/test/IModelTransformerUtils.ts(705,66): error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string | Code | ElementLoadProps'.
  Type 'undefined' is not assignable to type 'string | Code | ElementLoadProps'.
src/test/IModelTransformerUtils.ts(752,11): error TS2739: Type 'ElementAspect' is missing the following properties from type 'ExternalSourceAspect': scope, identifier, kind
src/test/IModelTransformerUtils.ts(768,11): error TS2322: Type 'ElementAspect' is not assignable to type 'ExternalSourceAspect'.
src/test/IModelTransformerUtils.ts(791,68): error TS2339: Property 'placement' does not exist on type 'ElementProps'.
src/test/IModelTransformerUtils.ts(794,31): error TS2339: Property 'placement' does not exist on type 'ElementProps'.
```

**Review by grigasp — APPROVED** [review]

**Comment by MichaelBelousov** [comment]
> Were there merge issues or should @MichaelBelousov take a look?

Looks like merge and linter issues. A lot of the affected lines had non-null assertions and casts removed.
I also noticed in the diff that cd6307b3d reverted a bunch of changes in the IModelTransformationUtils, but I haven't checked beyond that

**Comment by MichaelBelousov** [comment]
> Looks like merge and/or linter issues. A lot of the affected lines had non-null assertions and casts removed.
I can push some appropriate fixes

**Comment by calebmshafer** [comment]
> @calebmshafer you can cherry-pick them [from this branch](https://github.com/iTwin/itwinjs-core/tree/native/3.3.1-format-fixes) or let me know and I'll push them to this one

great, thanks @MichaelBelousov. I'll cherry-pick them over.

**Pull request closed without merging**
