### PR TITLE
Allow UiItemsProvider to populate a Widget without requiring React via new attachToDom method.

### PR DESCRIPTION
**Pull request by bsteinbk**

### CODE REVIEW

**Comment by bsteinbk** [comment]
@evelynpreslar-bentley  - Please review to see if the new `attachToDom` method that allows a provider to add DOM elements presents a security concern.  See example usage in file GenericWidget.ts.

**Comment by calebmshafer** [comment]
@bsteinbk would this not be prone to same attack vectors as the React setInnerHtml? https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml.

**Comment by bsteinbk** [comment]
> 

@calebmshafer - That is why I have asked @evelynpreslar-bentley to review.  But to be honest anyone writing an IModelApp could be doing this anyways. There is nothing to prevent an app from modifying the DOM. This generic DOM approach is already being used, it is the way Keith shows the itwinjs logo and info box.

**Comment by evelynpreslar-bentley** [comment]
@bsteinbk @calebmshafer React provides the `dangerouslySetInnerHTML` function, which allows unfettered access to the DOM. React marks this function as "dangerous" because programmatically setting the DOM without sanitizing the input can indeed lead to XSS attacks if the arguments for the function come from user input or a third-party source. The function therefore shouldn't be used without accepting the risk, but React still includes it because the manual control is useful in some cases.

Those developing iTwin apps already have full access to React, and thus this function, so it's already possible to do what's being facilitated by `attachToDom`. In addition, it's always possible to not just add new elements, but _directly edit_ the DOM through JavaScript calls, so `attachToDom` doesn't really expose anything new that wasn't available to iTwin developers before; it mostly just makes it easier (Note: this increased ease of use will make the chance of this happening more frequent as a result).

The real security concern is in how apps (and especially extensions) will implement `attachToDom`. Code that drops text obtained through an API call directly into the DOM through this function will be opening itself to XSS, but I don't think that's something the iTwin platform can really police other than by giving a warning that it's dangerous (like React does).

**Comment by calebmshafer** [comment]
@bsteinbk can we drop this down to a draft PR?

**Comment by calebmshafer** [comment]
going to close.

@NancyMcCallB

**Pull request closed without merging**
