### PR TITLE
update the version of chrome-launcher used by display-test-app

### PR DESCRIPTION
**Pull request by calebmshafer**
There are two new vulnerabilities that have popped up.

1. minimist has a new vulnerability for the older versions of the package. This has been patched in a compatible way with most of our dependencies. The one dependency that relied on too old of a version is chrome-launcher version. Updating to the latest version of chrome-launcher to the latest minor version moves up as needed
2. node-forge has two new CVEs ([here](https://github.com/advisories/GHSA-x4jg-mjrx-434g) and [here](https://github.com/advisories/GHSA-cfm4-qjh2-4765)) and is a transitive dependency of webpack-dev-server and react-scripts. Unfortunately webpack-dev-server is locked down to a specific version of the `selfsigned` package, the package with a dependency on `node-forge`, which is on an old major version of the node-forge. The only way to fix this would be to either fork webpack-dev-server (which we don't want to do) or update to react-scripts@5 that is on the latest version.

    Since @aruniverse is working on webpack5 support (i.e. react-scripts@5 support) we will add this vulnerability to our excluded list for the time being as this is a development dependency. 

Edit: Sigh... There is now an additional vulnerability reported in the time it took to make this PR. The issue is with `faker.js`, a dev dependency used for testing, that is consumed by the presentation tests. There is no current fix so it has been added to the excluded list.

### CODE REVIEW

**Review by pmconne — APPROVED** [review]

**Review by AJMigliore — APPROVED** [review]

**Review by kckst8 — APPROVED** [review]

**Comment by calebmshafer** [comment]
@bsteinbk I locked down the `@types/react` version and didn't try to fix the compilation error.

**Review by wgoehrig — APPROVED** [review]

**Review by bsteinbk — APPROVED** [review]

**Comment by bsteinbk** [comment]
> 

@calebmshafer - I think some React types definitions got updated during Rush Update processing .... I have these errors fixed in the PR that is blocked https://github.com/iTwin/itwinjs-core/pull/3293.

**Comment by skirby1996** [comment]
@mergifyio backport release/3.1.x

**Comment by skirby1996** [comment]
@mergifyio backport release/3.0.x

**Pull request merged**
