### PR TITLE
Change expected number of CRS to 11975 in GeoServices.test.ts

### PR DESCRIPTION
**Pull request by nick4598**
image
Arun mentioned that gcs workspace was deployed to prod yesterday.

### CODE REVIEW

**Comment by aruniverse** [comment]
@wgoehrig this seems pretty fragile no?

The gcs workspace doesnt get updated often, but it theoretically could.
Should we rather just expect the gcs workspace to not be empty?

**Review by wgoehrig — APPROVED** [review]

**Comment by wgoehrig** [comment]
@aruniverse I actually really like this test, I just think we should move it to run as part of the workspace deployment...

**Comment by aruniverse** [comment]
@mergifyio backport release/4.11.x

**Comment by ben-polinsky** [comment]
@mergifyio backport release/4.10.x

**Pull request merged**
