### PR TITLE
Update puppeteer to latest major version

### PR DESCRIPTION
**Pull request by calebmshafer**
The `chrome-86` tag we are using is very old at this point and does not support arm-based Macs. Updating to the latest major version to get a handful of fixes and types directly in the package.

### CODE REVIEW

**Comment by pmconne** [comment]
I'm looking into the WebGL compatibility test failure.

**Comment by pmconne** [comment]
@calebmshafer @wgoehrig These tests assume the browser is using software rendering.
With new version, chrome is using GPU instead of software rendering on Windows.
I tried adding (among other flags), "--disable-gpu" to certa.json's chromeOptions.args. It still uses GPU.
If I launch my installed Chrome from cmd line with same option, it uses software rendering (if you close all Chrome windows first).
I tried editing ChromeTestRunner.initialize to always add --disable-gpu to options.args. After clean rebuild it still uses GPU.

**Comment by calebmshafer** [comment]
@pmconne okay, I'll take a look. Maybe they change the flag for this in puppeteer or don't honor it anymore for some reason...

**Comment by pmconne** [comment]
@calebmshafer I adjusted the tests to not assume software rendering.

**Comment by calebmshafer** [comment]
@pmconne sounds good. Looks like they made the change in puppeteer due to a fix for a chrome bug that existed on Windows only, https://github.com/puppeteer/puppeteer/issues/1260#issuecomment-498857599. Not sure why it's only Windows that now doesn't honor the flag though...

I'll do a bit more digging to figure out what's going on.

**Review by pmconne — APPROVED** [review]

**Comment by pmconne** [comment]
Failing core-frontend tests.
```
  1) RenderState
       should have expected initial WebGL context state:

      AssertionError: expected 4294967295 to equal 2147483647
      + expected - actual

      -4294967295
      +2147483647
      
      at Context.call (D:\vsts_a\1\s\core\frontend\src\test\render\webgl\RenderState.test.ts:291:30)
      at callFn (@/lib/runnable.js:366:21)
      at Test.run (@/lib/runnable.js:354:5)
      at Runner.runTest (@/lib/runner.js:677:10)
      at fn (@/lib/runner.js:801:12)
      at next (@/lib/runner.js:594:14)
      at fn (@/lib/runner.js:604:7)
      at next (@/lib/runner.js:486:14)
      at http://localhost:3001/@/lib/runner.js:572:5
      at timeslice (@/browser-entry.js:100:5)

  2) Techniques
       WebGL 1
         should compile all shader programs:
     Error: Timeout of 95000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at createTimeoutError (@/lib/errors.js:498:15)
      at Test._timeoutError (@/lib/runnable.js:431:10)
      at done (@/lib/runnable.js:308:18)
      at http://localhost:3001/@/lib/runnable.js:371:11

  3) Techniques
       WebGL 1
         should compile all shader programs without MRT:
     Error: Timeout of 95000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at createTimeoutError (@/lib/errors.js:498:15)
      at Test._timeoutError (@/lib/runnable.js:431:10)
      at http://localhost:3001/@/lib/runnable.js:246:24

  4) Techniques
       WebGL 1
         should compile all shader programs without logarithmic depth:
     TypeError: Cannot read property 'capabilities' of undefined
      at Context.call (D:\vsts_a\1\s\core\frontend\src\test\render\webgl\Technique.test.ts:127:31)
      at callFn (@/lib/runnable.js:366:21)
      at Test.run (@/lib/runnable.js:354:5)
      at Runner.runTest (@/lib/runner.js:677:10)
      at fn (@/lib/runner.js:801:12)
      at next (@/lib/runner.js:594:14)
      at fn (@/lib/runner.js:604:7)
      at next (@/lib/runner.js:486:14)
      at http://localhost:3001/@/lib/runner.js:572:5
      at timeslice (@/browser-entry.js:100:5)

  5) Techniques
       WebGL 1
         should successfully compile surface shader with clipping planes:
     TypeError: Cannot read property 'techniques' of undefined
      at Context.call (D:\vsts_a\1\s\core\frontend\src\test\render\webgl\Technique.test.ts:137:38)
      at callFn (@/lib/runnable.js:366:21)
      at Test.run (@/lib/runnable.js:354:5)
      at Runner.runTest (@/lib/runner.js:677:10)
      at fn (@/lib/runner.js:801:12)
      at next (@/lib/runner.js:594:14)
      at fn (@/lib/runner.js:604:7)
      at next (@/lib/runner.js:486:14)
      at http://localhost:3001/@/lib/runner.js:572:5
      at timeslice (@/browser-entry.js:100:5)

  6) Techniques
       WebGL 1
         should produce exception on syntax error:
     TypeError: Cannot read property 'capabilities' of undefined
      at new ShaderBuilder (D:\vsts_a\1\s\core\frontend\src\render\webgl\ShaderBuilder.ts:501:25)
      at new VertexShaderBuilder (D:\vsts_a\1\s\core\frontend\src\render\webgl\ShaderBuilder.ts:714:5)
      at new ProgramBuilder (D:\vsts_a\1\s\core\frontend\src\render\webgl\ShaderBuilder.ts:1142:17)
      at createPurpleQuadBuilder (D:\vsts_a\1\s\core\frontend\src\test\render\webgl\Technique.test.ts:20:19)
      at Context.call (D:\vsts_a\1\s\core\frontend\src\test\render\webgl\Technique.test.ts:143:25)
      at callFn (@/lib/runnable.js:366:21)
      at Test.run (@/lib/runnable.js:354:5)
      at Runner.runTest (@/lib/runner.js:677:10)
      at fn (@/lib/runner.js:801:12)
      at next (@/lib/runner.js:594:14)

  7) Techniques
       WebGL 1
         should produce exception on unused uniform:
     TypeError: Cannot read property 'capabilities' of undefined
      at new ShaderBuilder (D:\vsts_a\1\s\core\frontend\src\render\webgl\ShaderBuilder.ts:501:25)
      at new VertexShaderBuilder (D:\vsts_a\1\s\core\frontend\src\render\webgl\ShaderBuilder.ts:714:5)
      at new ProgramBuilder (D:\vsts_a\1\s\core\frontend\src\render\webgl\ShaderBuilder.ts:1142:17)
      at createPurpleQuadBuilder (D:\vsts_a\1\s\core\frontend\src\test\render\webgl\Technique.test.ts:20:19)
      at Context.call (D:\vsts_a\1\s\core\frontend\src\test\render\webgl\Technique.test.ts:166:25)
      at callFn (@/lib/runnable.js:366:21)
      at Test.run (@/lib/runnable.js:354:5)
      at Runner.runTest (@/lib/runner.js:677:10)
      at fn (@/lib/runner.js:801:12)
      at next (@/lib/runner.js:594:14)

  8) Techniques
       WebGL 1
         Number of varying vectors
           does not exceed minimum guaranteed:
     TypeError: Cannot read property 'context' of undefined
      at Context.call (D:\vsts_a\1\s\core\frontend\src\test\render\webgl\Technique.test.ts:207:45)
      at callFn (@/lib/runnable.js:366:21)
      at Test.run (@/lib/runnable.js:354:5)
      at Runner.runTest (@/lib/runner.js:677:10)
      at fn (@/lib/runner.js:801:12)
      at next (@/lib/runner.js:594:14)
      at fn (@/lib/runner.js:604:7)
      at next (@/lib/runner.js:486:14)
      at http://localhost:3001/@/lib/runner.js:572:5
      at timeslice (@/browser-entry.js:100:5)

  9) Techniques
       WebGL 2
         "before all" hook for "should produce a simple dynamic rendering technique":
     Error: Class BisCore:Entity is already registered. Make sure static schemaName and className members are correct on class EntityState
      at Function.registerEntityState (D:\vsts_a\1\s\core\frontend\src\IModelApp.ts:309:13)
      at Function.startup (D:\vsts_a\1\s\core\frontend\src\IModelApp.ts:371:10)
      at Context.<anonymous> (D:\vsts_a\1\s\core\frontend\src\test\render\webgl\Technique.test.ts:57:9)
```

**Comment by pmconne** [comment]
Failing core-full-stack-tests test.
```
  1) RenderTarget
       should clip using a single plane:

      AssertionError: expected 2 to be at least 3
      + expected - actual

      -2
      +3
      
      at D:\vsts_a\1\s\full-stack-tests\core\src\frontend\standalone\RenderTarget.test.ts:692:29
      at testOnScreenViewport (D:\vsts_a\1\s\full-stack-tests\core\src\frontend\TestViewport.ts:336:5)
      at testViewports (D:\vsts_a\1\s\full-stack-tests\core\src\frontend\TestViewport.ts:360:3)
      at testViewportsWithDpr (D:\vsts_a\1\s\full-stack-tests\core\src\frontend\TestViewport.ts:368:5)
      at Context.<anonymous> (D:\vsts_a\1\s\full-stack-tests\core\src\frontend\standalone\RenderTarget.test.ts:668:5)
```

**Comment by calebmshafer** [comment]
closing in favor of #4017

**Pull request closed without merging**
