### PR TITLE
3.x deprecation tags.

### LINKED ISSUE #4909: Add version info to deprecated tags
@aruniverse @calebmshafer know anyone who's bored and wants to write a script to add `@deprecated in 3.x` to existing tags?

_Originally posted by @pmconne in https://github.com/iTwin/itwinjs-core/issues/4907#issuecomment-1379214584_
      
Our API deprecation policy mandates a minimum number of major releases before a deprecated API can be removed. We need to make it clear to users in what version an API became deprecated so that they can understand when it becomes eligible for removal.

Replace existing `@deprecated` tags with `@deprecated in 2.x` or `@deprecated in 3.x`.

UI APIs contain many 2.x deprecations and will be handled separately in https://github.com/iTwin/itwinjs-backlog/issues/613.

### PR DESCRIPTION
**Pull request by pmconne**
Fixes #4909 by replacing all "@deprecated" tags with "@deprecated in 3.x" or, for a handful that were deprecated prior to 3.0, "@deprecated in 2.x".
UI packages to be covered in a separate PR - there are many more 2.x deprecations in them.

### CODE REVIEW

**Review by MichaelBelousov — APPROVED** [review]
transformer changes lgtm

**Review by saeeedtorabi — APPROVED** [review]

**Comment by raplemie** [comment]
Should we evaluate and mark correct version for code that was deprecated in 2.x ? (Otherwise, it may look surprising that we mention many component deprecated in 3.x that are removed in 4.0, notably for AppUi stuff.)

**Review by markschlosseratbentley — APPROVED** [review]

**Review by bbastings — APPROVED** [review]

**Comment by aruniverse** [comment]
> > Should we evaluate and mark correct version for code that was deprecated in 2.x ? (Otherwise, it may look surprising that we mention many component deprecated in 3.x that are removed in 4.0, notably for AppUi stuff.)
> 
> If you know of specific APIs that were deprecated prior to 3.0, go ahead and mark them accordingly. We intentionally (for better or worse) deleted most (all, I think) deprecated things between 2.x and 3.0, at least in core/.

I see 320 deprecated apis in the `release/3.0.0` tag. 
image

Let's make sure to have correct deprecation tags before merging this pr. I think this affects ui more than anyone else as they've been waiting for ui@4.0 to finally get rid of their deprecated apis

**Comment by raplemie** [comment]
> > > Should we evaluate and mark correct version for code that was deprecated in 2.x ? (Otherwise, it may look surprising that we mention many component deprecated in 3.x that are removed in 4.0, notably for AppUi stuff.)
> > 
> > 
> > If you know of specific APIs that were deprecated prior to 3.0, go ahead and mark them accordingly. We intentionally (for better or worse) deleted most (all, I think) deprecated things between 2.x and 3.0, at least in core/.
> 
> I see 320 deprecated apis in the `release/3.0.0` tag. image
> 
> and 496 results for the latest in `release/2.19.x` image
> 
> Let's make sure to have correct deprecation tags before merging this pr. I think this affects ui more than anyone else as they've been waiting for ui@4.0 to finally get rid of their deprecated apis

The folder structure have been changed from 2 to 3, so figuring what was deprecated in 2.x will not be a 15 min task, so I created an issue for this, I dont know if we want to old up this PR as it will likely quickly get hard to maintain... I can create a different one only with UI, as long as it is done before the next release.

**Review by ben-polinsky — APPROVED** [review]

**Comment by pmconne** [comment]
> I dont know if we want to old up this PR

Well, no point in merging incorrect version info. I can refocus this PR on non-UI APIs.

**Review by dassaf4 — APPROVED** [review]

**Review by grigasp — APPROVED** [review]

**Review by aruniverse — APPROVED** [review]

**Comment by aruniverse** [comment]
@pmconne i don't think there are any files for @itwin/itwinjs-core-ui to review anymore, and can't seem to remove them as a reviewer. Once the pipeline succeeds feel free to force merge if you dont get an approval from them

**Review by raplemie — APPROVED** [review]
As we are required :)

**Pull request merged**
