### PR TITLE
Migrate from using itwin/projects-client to itwin/itwins-client api

### PR DESCRIPTION
**Pull request by anmolshres98**
Integration tests have been failing on build possibly because of projects api being turned off on qa as mentioned [here](https://github.com/iTwin/itwinjs-core/pull/5824#issuecomment-1668575362)

This PR is it fix that issue.

> Note: variables used in build still needs to updated to request token with scope `itwins:read`.

### CODE REVIEW

**Review by paulius-valiunas — APPROVED** [review]

**Review by aruniverse — APPROVED** [review]

**Comment by aruniverse** [comment]
@mergifyio backport release/4.1.x

**Pull request merged**
