### PR TITLE
Mobile backend access token fixes

### PR DESCRIPTION
**Pull request by tcobbs-bentley**
* Apply fixes from MobileAuthorizationFrontend to backend
* Don't resolve a promise after it has been rejected

### CODE REVIEW

**Comment by tcobbs-bentley** [comment]
@swbsi @aruniverse While @toddsouthenbentley was debugging a problem with failed token fetches in Android, I noticed these two problems in the mobile backend code. Neither was related to Todd's problem, but both of them are problems that need to be fixed.

**Review by aruniverse — APPROVED** [review]

**Comment by tcobbs-bentley** [comment]
@aruniverse There's nothing I can do about the failing Docs pipeline.

**Comment by aruniverse** [comment]
> @aruniverse There's nothing I can do about the failing Docs pipeline.

@ben-polinsky @yashincontrol

**Comment by ben-polinsky** [comment]
> > @aruniverse There's nothing I can do about the failing Docs pipeline.
> 
> @ben-polinsky @yashincontrol

Looking into it!

**Comment by ben-polinsky** [comment]
@aruniverse @tcobbs-bentley docs fixed

**Comment by tcobbs-bentley** [comment]
> @aruniverse @tcobbs-bentley docs fixed

Thanks!

**Pull request merged**
