### PR TITLE
Fix ios Display Test App

### PR DESCRIPTION
**Pull request by DanielToby**
The Webpack configuration for display-test-app on iOS was out of date. I updated it to align with changes to other packages and resolve this error:

TypeError: hexoid is not a function
    at Object.<anonymous> (/private/var/containers/Bundle/Application/080F2CDC-D154-4888-A50F-4588EC953475/imodeljs-test-app.app/Assets/main.js:89652:18)

This revealed further issues with importing Electron on iOS, which I fixed in src/backend/Backend.ts.

Network errors on iModel load were resolved by disabling auth. Fixes to auth are underway and will appear in a future PR.

### CODE REVIEW

**Comment by pmconne** [comment]
@markschlosseratbentley can you verify please?

**Comment by DanielToby** [comment]
> This fixes the build and initial runtime errors - However, I am unable to open a snapshot iModel. Have you successfully opened a snapshot iModel, @DanielToby ?
> 
> I get the following error pop-up: "Error: Network Error"

I have not, and experience the same network error when opening iModels. Looking into this now.

**Comment by DanielToby** [comment]
@markschlosseratbentley Mark, mind taking a look at this now that we've fixed the network error?

**Comment by markschlosseratbentley** [comment]
> @markschlosseratbentley Mark, mind taking a look at this now that we've fixed the network error?

@DanielToby I will take a look later today.

**Comment by markschlosseratbentley** [comment]
> > @markschlosseratbentley Mark, mind taking a look at this now that we've fixed the network error?
> 
> @DanielToby I will take a look later today.

I am getting past the network error now error - thanks!  However, when I open a snapshot, it does not open the model and I get the tile load progress bar just bouncing back and forth (almost like the backend and frontend are not communicating).  This happens on both iPhone 13 and iPad Pro 2021.

@khanaffan FYI.

**Comment by markschlosseratbentley** [comment]
Everything works now.

**Review by markschlosseratbentley — APPROVED** [review]
LGTM!

**Pull request merged**
