### PR TITLE
Address memory leak regarding markers and decorators

### PR DESCRIPTION
**Pull request by hl662**
When ImodelApp.shutdown() is called, ViewManager's onShutdown() is called. Problem is, the  viewports that are a part of IModelApp do not have their dispose() functions called, which holds up WebGL resources. This results in a memory leak even after shutdown() is called: thousands of featureAppearance overrides are being retained every refresh, which are coming from ScreenViewport's OnScreenTarget.

Solution is to drop all viewports in IModelApp's viewManager when shutdown is called.

### CODE REVIEW

**Comment by hl662** [comment]
@pmconne @markschlosseratbentley @Maxime-Brassard can you check this? This is a problem Maxime found after he put IModelApp.shutdown() into WaterSight after the meeting. The viewport still remained, with thousands of decorators remaining. 
To note, this is different from the 2 problems we discussed in the meeting.

**Review by markschlosseratbentley — APPROVED** [review]
Approving, but I agree with Ben's comment about a unit test.

**Comment by hl662** [comment]
> Approving, but I agree with Ben's comment about a unit test.

Agreed, just added one unit test, had to accommodate for errors when iterating through already disposed viewports

**Review by ben-polinsky — APPROVED** [review]

**Comment by aruniverse** [comment]
@mergifyio backport release/4.4.x

**Pull request merged**
