### PR TITLE
Imodel02 merge master

### PR DESCRIPTION
**Pull request by DanRod1999**
Merging to fix issues with eslint plugin in imodel02 found from https://github.com/iTwin/imodel-native/pull/213 validation runs. The eslint-plugin version in fixes this issue.

### CODE REVIEW

**Comment by pmconne** [comment]
Wrong target branch?

**Comment by DanRod1999** [comment]
> Wrong target branch?

yes sorry about that.

**Comment by pmconne** [comment]
I have been watching it. I'm not in love with two of your three recent merge commits. We want the history on imodel02 to look like the history on master.

**Comment by mattbjordan** [comment]
> I have been watching it. I'm not in love with two of your three recent merge commits. We want the history on imodel02 to look like the history on master.

Yeah... I'm not sure exactly what happened there. I can look into undoing them.

**Comment by DanRod1999** [comment]
> > I have been watching it. I'm not in love with two of your three recent merge commits. We want the history on imodel02 to look like the history on master.
> 
> Yeah... I'm not sure exactly what happened there. I can look into undoing them.

I believe this was due to it initially being merged to master, so it ran when it shouldn't have.

**Comment by aruniverse** [comment]
> I'd also like to see CI jobs running. extract-api failed for @DanRod1999 yesterday.

@pmconne i thought the full ci was never run against this target branch, since no native with the changes have been published

**Comment by nick4598** [comment]
> > i thought the full ci was never run against this target branch, since no native with the changes have been published
> 
> Right.

https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=2040439&view=results

I ran iTwin.js build pipeline against this branch and it all passed. This doesn't run extract-api though, which is a github action instead of an azure pipeline. Would you still like to see that? I'm not sure how to run a github action on this branch, maybe Seamus would know?

**Comment by calebmshafer** [comment]
@DanRod1999 let's add an issue for adding extract-api to the list of checks for the imodel02 branch... This will be painful since we're partially in GH and partially in ADO but let's add it to the list.

@pmconne anything holding this up from your side? If not, I'll merge it.

**Pull request merged**
