### PR TITLE
delete pkgs from core repo which have moved out into their own repos

### PR DESCRIPTION
**Pull request by aruniverse**
- appui pkgs have moved to https://github.com/iTwin/appui
- presentation pkgs have moved to https://github.com/iTwin/presentation
- eslint-plugin has moved to https://github.com/iTwin/eslint-plugin
- map-layers has moved to https://github.com/iTwin/viewer-components-react

### CODE REVIEW

**Comment by aruniverse** [comment]
@iTwin/itwinjs-core-presentation is the presentation test app in this repo still required or will it be completely replaced by the one in the presentation repo?

**Comment by grigasp** [comment]
> @iTwin/itwinjs-core-presentation is the presentation test app in this repo still required or will it be completely replaced by the one in the presentation repo?

The test app will be completely removed from core repo. We'll also remove some of the tests in `presentation-full-stack-tests` suite.

**Comment by saskliutas** [comment]
I have PR removing `presentation-components`, `presentation-testing` and some full-stack-tests. I am only waiting for docs pipeline before I can complete it. https://github.com/iTwin/itwinjs-core/pull/4836

**Comment by saskliutas** [comment]
@aruniverse As docs pipeline was updated I looked again at my PR removing some presentation-full-stack-tests https://github.com/iTwin/itwinjs-core/pull/4836. I tried removing `presentation-components` and `presentation-testing` in that PR as well but it looks like those packages should be remove at the same time as `ui`. So that could be done in this PR.

As for presentation-full-stack-tests not all of them should be removed. The ones that needs to be removed are removed in this PR https://github.com/iTwin/itwinjs-core/pull/4836. So this PR should not need to make any changes in `full-stack-test/presentation` folder.

**Comment by aruniverse** [comment]
I looked again yesterday, and can't delete UI from the repo w/o map-layers moving out of the repo. Will be working with Michel and team to do that on Monday.

**Review by pmconne — APPROVED** [review]

**Comment by pmconne** [comment]
I presume #4580 is dead now @mdastous-bentley?
@eringram have you moved your WIP changes to viewer-components-react repo?

**Review by ben-polinsky — APPROVED** [review]

**Review by dassaf4 — APPROVED** [review]

**Comment by eringram** [comment]
> I presume #4580 is dead now @mdastous-bentley? @eringram have you moved your WIP changes to viewer-components-react repo?

Not yet but I plan to after [this PR](https://github.com/iTwin/viewer-components-react/pull/365) is merged. I think with my changes MapLayerImageryProvider will also need to be exposed since it's used by the map layers widget.

**Review by mdastous-bentley — APPROVED** [review]

**Comment by mdastous-bentley** [comment]
> I presume #4580 is dead now @mdastous-bentley? 
Depends on Erin's changes.  There's still a need to expose map-layer imagery providers to create a new format like we do in map-layers-formats.

**Review by saskliutas — APPROVED** [review]

**Review by calebmshafer — APPROVED** [review]

**Review by GerardasB — APPROVED** [review]

**Pull request merged**
