### PR TITLE
ColorDef validation and ColorByName fix

### PR DESCRIPTION
**Pull request by pmconne**
`ColorDef.fromString` produces black if the input cannot be interpreted as a color.
`ColorDef.fromTbgr` takes a number and converts it to a uint32 via Uint32Array; fractional parts are truncated, sign bits are flipped, etc.

Added `ColorDef.isValidColor` to return whether the input (`number | string`) is a valid color representation, and `ColorDef.tryComputeTbgrFromString` which - unlike `computeTbgrFromString` - returns `undefined` instead of black if the string cannot be interpreted as a color.

In the process of testing this, I discovered that `ColorDef.create("aqua")` produces black - it fails to find `ColorByName.aqua`. This is because `ColorByName` is an enum, `ColorByName.cyan` has the same integer value as aqua, and enums are wack in TypeScript. `Object.entries` iterates the values, which omits duplicate values.

Converted `ColorByName` to an object (via `namespace`) to eliminate this problem without breaking code that currently does `ColorByName.whatever`. Code that relies on ColorByName being an enum may break, but enums are wack, so no one should be relying upon that.

### CODE REVIEW

**Review by mgooding — APPROVED** [review]
I appreciated the enum vs object explanation in NextVersion.md.

**Review by kabentley — APPROVED** [review]

**Review by bsteinbk — APPROVED** [review]

**Comment by pmconne** [comment]
Force merging because macOS is hung on ECSql tests again.

**Review by NancyMcCallB — APPROVED** [review]

**Comment by pmconne** [comment]
@UgniusZidonis in what way is this bug manifesting on 2.19.x?

**Comment by UgniusZidonis** [comment]
@pmconne, as I had explained in the Teams channel, there is no way of checking whether an argument for creating a color is valid or not, so with invalid arguments you get a black color. We need that `isValidColor` function.

**Pull request merged**
