### PR TITLE
Deprecate ByteStream getters

### PR DESCRIPTION
**Pull request by pmconne**
I knew when I wrote these that it was a bit dirty for a getter to increment the current read position.
Now Angular is eliding repeated calls to the getters because it [assumes they are free of side effects](https://github.com/angular/angular-cli/issues/12128#issuecomment-472309593).
Deprecate and replace with corresponding methods.

Note there are probably other getters that will similarly trip up Angular's optimizer. @aruniverse is looking into creating a custom Angular config to prevent such problems.

### CODE REVIEW

**Review by kabentley — APPROVED** [review]

**Review by bbastings — APPROVED** [review]

**Review by aruniverse — APPROVED** [review]
Thanks for the fast fix

**Review by markschlosseratbentley — APPROVED** [review]

**Review by aruniverse — APPROVED** [review]
approving again, on behalf of the extension api changes, not sure how that got pulled in

**Comment by pmconne** [comment]
@mattbjordan does [this change](https://github.com/iTwin/itwinjs-backlog/issues/348) unintentionally fail to trigger builds for a PR after pushing a commit that, e.g., only modifies files in common/changes?
After I pushed [this commit](https://github.com/iTwin/itwinjs-backlog/issues/348) my builds were not triggered.

**Comment by mattbjordan** [comment]
> @mattbjordan does [this change](https://github.com/iTwin/itwinjs-backlog/issues/348) unintentionally fail to trigger builds for a PR after pushing a commit that, e.g., only modifies files in common/changes?

@pmconne [_This_ change](https://github.com/iTwin/itwinjs-core/pull/4547), implemented after the one you linked, doesn't trigger builds when only `.json` files under common/changes/ have changes (or any other files that match the exclusion list globs).

> After I pushed [this commit](https://github.com/iTwin/itwinjs-backlog/issues/348) my builds were not triggered.

Also the link to your commit is wrong, so I'm not sure what you're talking about.

**Comment by pmconne** [comment]
> Also the link to your commit is wrong, so I'm not sure what you're talking about.

[This](https://github.com/iTwin/itwinjs-core/pull/4796/commits/7060890bc21c34c49fb8c3994fd31ee6caafc929) is the commit to which I intended to refer.

**Comment by pmconne** [comment]
Pushing [revert changelog](https://github.com/iTwin/itwinjs-core/pull/4796/commits/6f7176649d576e4f1dc9f1570065454030073efc) did trigger builds. I can't tell if there's an issue here or not, or whether it's related to #4547.

**Comment by mattbjordan** [comment]
I can't tell if there's an issue or not either. I would expect at the very least that either the "skip check" build or the rest of the builds would trigger, but it seems like neither triggered. All files in the current PR should be considered when a build determines if it will run or not.

@pmconne If you see this again, ping me before you try to trigger the builds so I can better see what is going on. I can't see the "required" builds' statuses from the past commits; I would expect to see them as "pending" or something.

**Comment by aruniverse** [comment]
@mergifyio backport release/3.5.x

**Pull request merged**
