### PR TITLE
suppress GHSA-8mwq-mj73-qv68

### PR DESCRIPTION
**Pull request by aruniverse**
suppress https://github.com/advisories/GHSA-8mwq-mj73-qv68

### CODE REVIEW

**Review by paulius-valiunas — APPROVED** [review]

**Review by wgoehrig — APPROVED** [review]

**Comment by pmconne** [comment]
@Mergifyio backport release/3.7.x

**Comment by pmconne** [comment]
@aruniverse anything holding up the merge?

**Comment by skirby1996** [comment]
@mergifyio backport release/3.6.x

**Comment by pmconne** [comment]
@Mergifyio backport release/3.5.x

**Pull request merged**
