### PR TITLE
Restore dta iOS CI build

### PR DESCRIPTION
**Pull request by toddsouthenbentley**
Now using a local dir for the DerivedData which should be more reliable in CI builds.

### CODE REVIEW

**Comment by toddsouthenbentley** [comment]
@calebmshafer @tcobbs-bentley @markschlosseratbentley Can you please give this a try when you get a chance?

Steps:
```sh
npm run build:ios
npm run build:ios-app
```

**Comment by aruniverse** [comment]
i see theres a manual option to build ios dta in the ci, could you run that, and link it in the pr?

**Comment by toddsouthenbentley** [comment]
> i see theres a manual option to build ios dta in the ci, could you run that, and link it in the pr?

Manual run of the iTwin.js pipeline: https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=1708598&view=results

**Review by aruniverse — APPROVED** [review]

**Review by calebmshafer — APPROVED** [review]

**Review by markschlosseratbentley — APPROVED** [review]
Tested the build commands; works for me.

**Review by tcobbs-bentley — APPROVED** [review]

**Pull request merged**
