### PR TITLE
Presentation: Support default formats when formatting in ts

### PR DESCRIPTION
**Pull request by grigasp**
Note: This PR doesn't have a native counterpart. The reason it targets `imodel02` is that it builds on top of what's not in `master` yet.

### CODE REVIEW

**Review by saskliutas — APPROVED** [review]

**Comment by pmconne** [comment]
> This PR doesn't have a native counterpart. The reason it targets imodel02 is that it builds on top of what's not in master yet.

Still would like the CI jobs to validate your changes.

**Comment by grigasp** [comment]
> Still would like the CI jobs to validate your changes.

Apparently not as simple as it sounds 🤔

**Review by pmconne — APPROVED** [review]
Please publish a new addon as soon as this PR completes.

**Pull request merged**
