### PR TITLE
Add CDN and version parameters to mesh-export/get-exports query

### PR DESCRIPTION
**Pull request by danieliborra**
- Add the following parameters to the mesh-export/get-exports query:
  - version: filters the exports by version, to support multiple versions
  - cdn: activates the CDN (context delivery network) to make tile downloads faster

### CODE REVIEW

**Comment by pmconne** [comment]
```
cd extensions/frontend-tiles
npm run lint
npm run extract-api
```

If no errors, or after committing fixes

```
rush change
# describe your changes
git add ../../common/changes
git commit --amend --no-edit
```

**Review by markschlosseratbentley — APPROVED** [review]
Looks good.

**Comment by pmconne** [comment]
Test is failing.

```
  1) obtainMeshExportTilesetUrl
       selects the first export matching the changeset Id:

      AssertionError: expected 'http://tiles.com/a/tileset.json' to equal 'http://tiles.com/b/tileset.json'
      + expected - actual

      -http://tiles.com/a/tileset.json
      +http://tiles.com/b/tileset.json

      at home/paul/c/j2/s/itwinjs/extensions/frontend-tiles/src/test/FrontendTiles.test.ts:200:36
      at mockFetch (home/paul/c/j2/s/itwinjs/extensions/frontend-tiles/src/test/FrontendTiles.test.ts:39:5)
      at expectUrl (home/paul/c/j2/s/itwinjs/extensions/frontend-tiles/src/test/FrontendTiles.test.ts:191:5)
      at Context.<anonymous> (home/paul/c/j2/s/itwinjs/extensions/frontend-tiles/src/test/FrontendTiles.test.ts:212:5)
```

**Comment by markschlosseratbentley** [comment]
@aruniverse can we backport this to 4.4 possibly?
cc @danieliborra

**Comment by aruniverse** [comment]
@mergifyio backport release/4.4.x

**Pull request merged**
