### PR TITLE
@bentley/imodeljs-native 4.3.6

### PR DESCRIPTION
**Pull request by anmolshres98**
Addon includes:
https://github.com/iTwin/imodel-native/commit/bb5453e891049dcbc568326952fc4f53e0325bb3
https://github.com/iTwin/imodel-native/commit/47c231c469e7ccc33b202394bd0f36eede54d392
https://github.com/iTwin/imodel-native/commit/ae033352eb2679e676f9709abc50efed93c8ce31
https://github.com/iTwin/imodel-native/commit/f5eca8736b295aa829b60d6b797f467c16de885e

### CODE REVIEW

**Review by aruniverse — APPROVED** [review]

**Review by DanRod1999 — APPROVED** [review]

**Comment by tcobbs-bentley** [comment]
I don't know why the Mac build is failing on the Android test. This happens intermittently. I am working on a possible fix, but so far rerunning the build has fixed the problem.

**Comment by anmolshres98** [comment]
> I don't know why the Mac build is failing on the Android test. This happens intermittently. I am working on a possible fix, but so far rerunning the build has fixed the problem.

rerunning now

**Comment by tcobbs-bentley** [comment]
I see it failed again. I submitted a PR to master that might fix the problem:

https://github.com/iTwin/itwinjs-core/pull/6302

Assuming the CI succeeds on that PR and it is merged, backporting it to release/4.3.x might fix things here. Another alternative is to try rerunning the whole CI for this PR instead of just rerunning the failing job.

**Comment by anmolshres98** [comment]
> I see it failed again. I submitted a PR to master that might fix the problem:
> 
> #6302
> 
> Assuming the CI succeeds on that PR and it is merged, backporting it to release/4.3.x might fix things here. Another alternative is to try rerunning the whole CI for this PR instead of just rerunning the failing job.

I will keep an eye on that PR but in the meantime I can also rerun entire CI, thanks

**Comment by anmolshres98** [comment]
> > I see it failed again. I submitted a PR to master that might fix the problem:
> > #6302
> > Assuming the CI succeeds on that PR and it is merged, backporting it to release/4.3.x might fix things here. Another alternative is to try rerunning the whole CI for this PR instead of just rerunning the failing job.
> 
> I will keep an eye on that PR but in the meantime I can also rerun entire CI, thanks

I reran the whole CI and failed with same error message

**Comment by tcobbs-bentley** [comment]
> I reran the whole CI and failed with same error message

@toddsouthenbentley @aruniverse Can one of you look at my PR that hopefully fixes the CI problem that this PR is running into?

https://github.com/iTwin/itwinjs-core/pull/6302

**Pull request merged**
