### PR TITLE
Fix DTA signin error

### PR DESCRIPTION
**Pull request by pbell97**
Display Test App previously logged errors to the console in electron when opening a model and not signed in. 

Moved the init of the electron renderer auth client to when the signin method is called so that `IModelApp.authorizationClient` is undefined until ready to signin. Previously `IModelApp.authorizationClient` was defined in the beginning but no signed in, and various places expect it to be signed in if it is defined which causes an error when getting an access token.

Also changed the signout method to removed the auth client from `IModelApp.authorizationClient` so that the app wouldn't think it was still able to get access tokens.

### CODE REVIEW

**Comment by pmconne** [comment]
@DStradley please review.

**Review by DStradley — APPROVED** [review]
This fixes the "'itwin.electron.auth.getAccessToken: Authorization error" messages in DTA (but does not fix the "Error: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document." assertions when selecting an element).

**Comment by pmconne** [comment]
@pbell97 don't merge this yet, I want to test the keyins.

**Comment by pbell97** [comment]
> I built your branch, launched display-test-app, and opened an iModel containing a reality model (requires access token, QA env). Reality model displays correctly, because cached token. Keyed in `dta signout` then `dta signin`. I sign in successfully to QA. I reopen the iModel and am presented with CORS errors trying to access the reality model. I repeatedly sign out and back in, exiting and restarting the app in between some attempts, with no improvement. I can no longer get my reality model to display.
> 
> ```
> Access to XMLHttpRequest at 'https://qa-api.bentley.com/contextshare/v1/Repositories/S3MXECPlugin--00000…00-0000-000000000000/S3MX/RealityData/c26b14fc-2f7a-4d82-a53a-837e769f8c72' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> client.js:890 GET https://qa-api.bentley.com/contextshare/v1/Repositories/S3MXECPlugin--00000…00-0000-000000000000/S3MX/RealityData/c26b14fc-2f7a-4d82-a53a-837e769f8c72 net::ERR_FAILED
> :3000/:1 Access to XMLHttpRequest at 'https://qa-api.bentley.com/contextshare/v1/Repositories/S3MXECPlugin--00000…00-0000-000000000000/S3MX/RealityData/c26b14fc-2f7a-4d82-a53a-837e769f8c72' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> client.js:890 GET https://qa-api.bentley.com/contextshare/v1/Repositories/S3MXECPlugin--00000…00-0000-000000000000/S3MX/RealityData/c26b14fc-2f7a-4d82-a53a-837e769f8c72 net::ERR_FAILED
> :3000/:1 Access to XMLHttpRequest at 'https://qa-api.bentley.com/contextshare/v1/Repositories/S3MXECPlugin--00000…00-0000-000000000000/S3MX/RealityData/c26b14fc-2f7a-4d82-a53a-837e769f8c72' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> client.js:890 GET https://qa-api.bentley.com/contextshare/v1/Repositories/S3MXECPlugin--00000…00-0000-000000000000/S3MX/RealityData/c26b14fc-2f7a-4d82-a53a-837e769f8c72 net::ERR_FAILED
> :3000/:1 Access to XMLHttpRequest at 'https://qa-api.bentley.com/contextshare/v1/Repositories/S3MXECPlugin--00000…00-0000-000000000000/S3MX/RealityData/c26b14fc-2f7a-4d82-a53a-837e769f8c72' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> client.js:890 GET https://qa-api.bentley.com/contextshare/v1/Repositories/S3MXECPlugin--00000…00-0000-000000000000/S3MX/RealityData/c26b14fc-2f7a-4d82-a53a-837e769f8c72 net::ERR_FAILED
> :3000/:1 Access to XMLHttpRequest at 'https://qa-api.bentley.com/contextshare/v1/Repositories/S3MXECPlugin--00000…00-0000-000000000000/S3MX/RealityData/c26b14fc-2f7a-4d82-a53a-837e769f8c72' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> client.js:890 GET https://qa-api.bentley.com/contextshare/v1/Repositories/S3MXECPlugin--00000…00-0000-000000000000/S3MX/RealityData/c26b14fc-2f7a-4d82-a53a-837e769f8c72 net::ERR_FAILED
> ```

Hey Paul, I've been debugging this for awhile and I _think_ I've tracked it down to a RealityDataSource problem. I swapped over to master and I was able to reproduce this same error you describe on master as well. Would you mind testing on master and see if you get the same result? 

The workflow I've been able to reproduce it with is when you open a reality model like normal, then close it and signout, then open the model again (which is expected to fail since you aren't signed in and gives the CORS error in console), then close the model and signin and open the model again and it still wont load which produces `Failed to load resource: the server responded with a status of 404 (The specified blob does not exist.)`.

I think it has to do with RealityDataSource messing up the url to get the blobs, it seems to incorrectly store the url when it tries to open an iModel when not signedin, and then it prepends that old url to the existing one it is supposed to use so it ends up with a malformed url. Still digging into it...

**Comment by MarcBedard8** [comment]
From what I see in this url: https://qa-api.bentley.com/contextshare/v1/Repositories/S3MXECPlugin--00000…00-0000-000000000000/S3MX/RealityData/c26b14fc-2f7a-4d82-a53a-837e769f8c72, you have an invalid empty iTwinId ( the 00000…00-0000-000000000000). In the current version of the Reality Data API, an iTwinId is required. @EricPaquetB is working to bring back undefined iTwinId to work.

**Review by pmconne — APPROVED** [review]

**Comment by pbell97** [comment]
> From what I see in this url: [https://qa-api.bentley.com/contextshare/v1/Repositories/S3MXECPlugin--00000…00-0000-000000000000/S3MX/RealityData/c26b14fc-2f7a-4d82-a53a-837e769f8c72](https://qa-api.bentley.com/contextshare/v1/Repositories/S3MXECPlugin--00000%E2%80%A600-0000-000000000000/S3MX/RealityData/c26b14fc-2f7a-4d82-a53a-837e769f8c72), you have an invalid empty iTwinId ( the 00000…00-0000-000000000000). In the current version of the Reality Data API, an iTwinId is required. @EricPaquetB is working to bring back undefined iTwinId to work.

The problem I've been facing is after this when I am signed back in. It seems `getTileContent()` has the baseUrl already set (due to `getRootDocument()` calling `this.setBaseUrl(url)` when there is not a token on a non-signed-in attempt) which causes the blob it tries to get to have the url `https://realityblobqaeussa01.blob.core.windows.net/c26b14fc-2f7a-4d82-a53a-837e769f8c72/https://qa-api.bentley.com/contextshare/v1/Repositories/S3MXECPlugin--00000000-0000-0000-0000-000000000000/S3MX/RealityData/_Data_Model_Model_L17_000_3mxb.b3dm?sv=2020-08-04&se=2021-12-14T23:59:59Z&sr=c&sp=rl&sig=LL4VTtj0ahy9LI1RUOaMM1ppPpb8U1MlDW07EodhNfg=`. This causes `Failed to load resource: the server responded with a status of 404 (The specified blob does not exist.)` error.

That's just what I've seen when debugging, I don't know too much about the intended logic.

**Comment by MarcBedard8** [comment]
@pbell97 It could be a problem with an optimization I've try to do which keep last instance found from a realityDataSourceKey.
In RealityDataSource.ts, in method fromKey (near line 183), If you disable these lines (which store result in a cache), does it help?
/*
    let rdSource = RealityDataSourceImpl._realityDataSources.get(rdSourceKeyString);
    if (rdSource)
      return rdSource;
*/
If so, I'll remove tht optimization...

**Comment by pbell97** [comment]
> @pbell97 It could be a problem with an optimization I've try to do which keep last instance found from a realityDataSourceKey. In RealityDataSource.ts, in method fromKey (near line 183), If you disable these lines (which store result in a cache), does it help? /* let rdSource = RealityDataSourceImpl._realityDataSources.get(rdSourceKeyString); if (rdSource) return rdSource; */ If so, I'll remove tht optimization...

Yes that seems to do the trick!

**Comment by MarcBedard8** [comment]
> 

This PR sould fix this: https://github.com/iTwin/itwinjs-core/pull/2905

**Pull request merged**
