### PR TITLE
Fix missing iTwinId caching to reduce the frequency of rate limiting

### PR DESCRIPTION
**Pull request by franklbh**
Resolved an issue where the iTwinId was not cached after being fetched, which led to redundant requests and increased the chances of triggering rate limiting. Now, the iTwinId is correctly assigned and reused for subsequent requests, which reduces the frequency of rate limiting issues, but does not fully prevent it.

Despite this improvement, given the nature of how test suites and instance variables are used across multiple test runs, there can still be a significant number of calls made to the iTwins service, especially when multiple tests run in parallel.

### CODE REVIEW

**Review by pmconne — APPROVED** [review]

**Comment by franklbh** [comment]
the old pipeline run: [link to the old pipeline](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=3170951&view=logs&jobId=ed028be3-93cc-5810-b6af-4051bb99b75a&j=f86f5973-737a-5adb-450c-2392b7392c71&t=a1ced17a-6e07-5999-28cb-90a1fc9faca1)

the most recent: [link to the new pipeline](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=3204207&view=logs&j=bb859fd0-9d44-5778-3197-aa487cc254aa&t=344bfc9a-a72c-583b-3ed0-211461d2cd5b) 

In the old pipeline, the errors were a result of excessive redundant requests being sent to the iTwins service. The lack of caching caused repeated calls to the service during tests, which triggered rate-limiting issues and led to test failures.

**Comment by aruniverse** [comment]
> Resolved an issue where the iTwinId was not cached after being fetched, which led to redundant requests and increased the chances of triggering rate limiting. 

Can you also look at if we're properly caching iModels and anything else?

**Comment by franklbh** [comment]
> > Resolved an issue where the iTwinId was not cached after being fetched, which led to redundant requests and increased the chances of triggering rate limiting.
> 
> Can you also look at if we're properly caching iModels and anything else?

sure I will do that

**Comment by franklbh** [comment]
> > Resolved an issue where the iTwinId was not cached after being fetched, which led to redundant requests and increased the chances of triggering rate limiting.
> 
> Can you also look at if we're properly caching iModels and anything else?

I've looked over and they seem to be correctly cached

**Review by hl662 — APPROVED** [review]

**Pull request merged**
