### PR TITLE
Deprecate visibility trees

### PR DESCRIPTION
**Pull request by saskliutas**
Deprecated visibility tree after they were moved to `@itwin/tree-widget-react` package. This should allow to remove `appui-react` dependency on `presentation-components` more easily.

### CODE REVIEW

**Review by aruniverse — COMMENTED** [review]
Could you mention this in NextVersion.md

**Comment by raplemie** [comment]
I think all the exports from "imodel-component" should be marked as `@deprecated moved to tree-widget-react`. Currently the content of VisibilityTreeRenderer was not marked as such, is it an oversight or is it plan to keep them there? (Since they are duplicated in `tree` package anyway ?

**Comment by saskliutas** [comment]
> I think all the exports from "imodel-component" should be marked as `@deprecated moved to tree-widget-react`. Currently the content of VisibilityTreeRenderer was not marked as such, is it an oversight or is it plan to keep them there? (Since they are duplicated in `tree` package anyway ?

Wasn't sure if I need to deprecate `alpha` interfaces. I guess it shouldn't cause problems deprecating them so I added `@deprecated` tag to them all. It will give lint errors if someone is using `alpha` APIs. I think those APIs need to be looked at and probably promoted.

**Review by raplemie — APPROVED** [review]
LGTM

**Comment by pmconne** [comment]
@saskliutas these deprecations of public APIs are not mentioned in NextVersion.md. Is there a reason they should not be?

**Comment by saskliutas** [comment]
> @saskliutas these deprecations of public APIs are not mentioned in NextVersion.md. Is there a reason they should not be?

There is a section in NextVersion.md about these APIs being moved to another package. https://github.com/iTwin/itwinjs-core/blob/master/docs/changehistory/NextVersion.md#itwinappui-react

**Pull request merged**
