### PR TITLE
Presentation: Fixes for PresentationFilterDialog

### PR DESCRIPTION
**Pull request by saskliutas**
Fixed styles of NavigationPropertyEditor to correctly render it in Dialog component.
While testing found that filters with navigation property were incorrectly converted to ECExpression. This was caused because property and field of that property typeName were different. Property itself has `long` type and field typeName is set to `navigation`.

Closes https://github.com/iTwin/itwinjs-core/issues/4974

### CODE REVIEW

**Comment by grigasp** [comment]
I see this fixes the menu being nested inside the dialog, but still there are a few styling problems:
image

1. When the popout exceeds available width of the window, we can't see its scrollbar. Should we set max-width? Or maybe the popout can be made to align to the other side?
2. The chevron's white background is still on top of the border of focused combo box.
3. The "Select target instance" text becomes multiline when the combo box is too narrow. IMO it should stay on one line and apply ellipsis on the text (or at least cut it).

**Comment by saskliutas** [comment]
I will take a lot.

Regarding 2 It might be an issue in itwinui as other select components we use in test-app have same behavior
image

**Comment by grigasp** [comment]
> I will take a look.
> 
> Regarding 2 It might be an issue in itwinui as other select components we use in test-app have same behavior

I can't repro it here: https://itwin.github.io/iTwinUI-react/?path=/story/core-combobox--with-custom-message-icon. Maybe we add some kind of style customization?..

**Comment by saskliutas** [comment]
I think this is noticeable only when select size is set to small. https://codesandbox.io/s/itwinui-react-example-forked-llbr13?file=/src/App.tsx

Also it looks like this is fixed in itwinui v2

**Comment by grigasp** [comment]
> Also it looks like this is fixed in itwinui v2

@iTwin/itwinjs-core-ui, any plans to move to itwinui 2?

**Review by grigasp — APPROVED** [review]
I think the popout is still not perfect, but I'm approving just so we can get this into 3.6 and we can reiterate afterwards.

**Pull request merged**
