### PR TITLE
Fix `fetch` stub issue when using node.js 20.x

### PR DESCRIPTION
**Pull request by mdastous-bentley**

### CODE REVIEW

**Comment by mdastous-bentley** [comment]
@nick4598 looks like there is another issue with Docs, can you help with that?

**Comment by ben-polinsky** [comment]
> @nick4598 looks like there is another issue with Docs, can you help with that?

I'm on it.

**Review by nick4598 — APPROVED** [review]

**Review by eringram — APPROVED** [review]

**Comment by mdastous-bentley** [comment]
@nick4598 There are still errors coming from `@itwin/physical-material-backend`

**Comment by mdastous-bentley** [comment]
@aruniverse please review

**Pull request merged**
