### PR TITLE
Work around content range tile problems when reprojecting tiles

### PR DESCRIPTION
**Pull request by markschlosseratbentley**
Fixes https://github.com/iTwin/itwinjs-backlog/issues/761
Fixes https://github.com/iTwin/itwinjs-backlog/issues/749

When reprojecting tiles, the tile range may be very, very tall in some datasets. This results in the reprojection causing gaps between tiles. Instead, just use "content range" for reprojecting tiles, which much more tightly encompasses the tile and avoids this kind of error.

### CODE REVIEW

**Comment by pmconne** [comment]
`rush change` is going to fail.

**Review by pmconne — APPROVED** [review]

**Comment by markschlosseratbentley** [comment]
> `rush change` is going to fail.

thanks

**Comment by pmconne** [comment]
Does user expect prompt fix? If so backport to appropriate release branch.

**Comment by markschlosseratbentley** [comment]
> Does user expect prompt fix? If so backport to appropriate release branch.

Asking on original work item.

**Comment by markschlosseratbentley** [comment]
@mergifyio backport release/3.7.x

**Comment by pmconne** [comment]
@Mergifyio backport release/4.0.x

**Pull request merged**
