### PR TITLE
@bentley/imodeljs-native 3.6.0

### PR DESCRIPTION
**Pull request by nick4598**

### CODE REVIEW

**Comment by nick4598** [comment]
I'm getting one failed test locally: 

Common table expression support in ECSQL
    1) collect base properties recursively


  0 passing (1s)
  1 failing

  1) Common table expression support in ECSQL
       collect base properties recursively:

      AssertionError: expected [ 'CodeScope', 'CodeSpec', …(52) ] to have the same ordered members as [ 'BBoxHigh', 'BBoxLow', …(52) ]
      + expected - actual

       [
      +  "BBoxHigh"
      +  "BBoxLow"
      +  "Category"
      +  "GeometryStream"
      +  "Origin"
      +  "Rotation"
      +  "TypeDefinition"
         "CodeScope"
         "CodeSpec"
         "CodeValue"
         "FederationGuid"
--
         "LastMod"
         "Model"
         "Parent"
         "UserLabel"
      -  "BBoxHigh"
      -  "BBoxLow"
      -  "Category"
      -  "GeometryStream"
      -  "Origin"
      -  "Rotation"
      -  "TypeDefinition"
      -  "IsPrivate"
         "Description"
         "Rank"
      +  "IsPrivate"
         "Recipe"
         "Data"
         "Type"
         "Angle"
         "Pitch"
         "Roll"
         "Yaw"
      -  "CategorySelector"
      -  "DisplayStyle"
         "BaseModel"
         "Extents"
         "RotationAngle"
      +  "CategorySelector"
      +  "DisplayStyle"
         "Properties"
         "Name"
         "InSpatialIndex"
         "Enabled"
      +  "ModelSelector"
         "EyePoint"
         "FocusDistance"
         "IsCameraOn"
         "LensAngle"
      -  "ModelSelector"
      +  "RepositoryGuid"
         "Url"
      -  "RepositoryGuid"
         "PaletteName"
         "Height"
         "Scale"
         "SheetTemplate"

      at Context.<anonymous> (src\test\ecdb\CTE.test.ts:47:12)
      
@khanaffan any idea what may have changed here?

**Comment by aruniverse** [comment]
Re the test failure nick has mentioned above. if im not mistaken, @DanRod1999 imodel02 pr validation had succeeded as recntly as of wednesday, so if its not a local issue, whats breaking the pr was probably introduced within the last 2 days

**Comment by khanaffan** [comment]
@nick4598  i cannot tell why the order would have changed. Though it's possible it may be due to sqlite update as i am not aware of anything change in ecdb that may have caused it.

**Comment by nick4598** [comment]
> @nick4598 i cannot tell why the order would have changed. Though it's possible it may be due to sqlite update as i am not aware of anything important in ecdb that may have caused it.

I was also thinking the sqlite update after what arun said... Did this order mean anything before? Or was it just the order at the time of writing the test?

**Comment by nick4598** [comment]
Affan mentioned he'd take a look at this next week. Skipping the test may be an option, but I'll just leave it as is for now.

**Review by pmconne — APPROVED** [review]

**Review by aruniverse — APPROVED** [review]

**Pull request merged**
