### PR TITLE
Fix missing login dialog for some ArcGIS services

### PR DESCRIPTION
**Pull request by mdastous-bentley**
Some ArcGIS service will throw an error 403 (You do not have permissions to access this resource or perform this operation),
when an OAuth token is required ( instead of the typical 499 error - TokenRequired).

So we now check for error 403 before triggering the Oauth2 login process.

### CODE REVIEW

**Review by aruniverse — APPROVED** [review]
i assume linter will fail, but lgtm
can prob be cleaned up further so these checks dont get too much more unruly

**Comment by jjbeckman13** [comment]
@aruniverse, can you backport this to 4.7.x? Needed to address service case.

**Comment by aruniverse** [comment]
@mergifyio backport release/4.x

**Comment by aruniverse** [comment]
@mergifyio backport release/4.7.x

**Pull request merged**
