### PR TITLE
 Isolate Oauth2 code under ArcGisAccessClient

### PR DESCRIPTION
**Pull request by mdastous-bentley**
Create new `MapLayersAccessClient` interface that will be used to encapsulate all authentication logic of map layers formats (i.e. ESRI's Oauth2 ).

 A `MapLayersAccessClient` implementation can be set for each maplayer format in the `MapLayerFormatRegistry`.  This allow external package, or in this case the maplayers package, to enable the Oauth2 functionality while keep specialized code outside core package.

IMPORTANT: `ArcGisAccessClient` and other OAuth2 related classes are still part of core-frontend, but will be moved in the maplayers package once this designed is approved.

### CODE REVIEW

**Comment by mdastous-bentley** [comment]
@calebmshafer @pmconne Please comment.

**Comment by pmconne** [comment]
> will be moved in the maplayers package

Today the map-layers package is a UI package with lots of dependencies. That doesn't seem like the right place for map layer access clients. Would it make more sense to deliver access clients via extensions?

**Review by MarcBedard8 — APPROVED** [review]

**Comment by calebmshafer** [comment]
> > will be moved in the maplayers package
> 
> Today the map-layers package is a UI package with lots of dependencies. That doesn't seem like the right place for map layer access clients. Would it make more sense to deliver access clients via extensions?

@pmconne I agree that they should be split out from the UI but not sure Extensions will be that correct split. At least initially.

**Comment by pmconne** [comment]
@calebmshafer please elaborate. Injecting support for a data source not natively supported by core seems like a perfect use case for extensions.

**Review by MarcBedard8 — APPROVED** [review]

**Review by MarcBedard8 — APPROVED** [review]

**Comment by mdastous-bentley** [comment]
@calebmshafer I created a new `maplayers-auth` package, can you have a quick look and confirms that good.  Also I wasn't sure I should create an empty `CHANGELOG.json` file

**Review by MarcBedard8 — APPROVED** [review]

**Review by MarcBedard8 — APPROVED** [review]

**Pull request merged**
