### PR TITLE
Upgrade azurite to version 3.18.0 to fix moment vulnerability

### PR DESCRIPTION
**Pull request by anmolshres98**
Proper fix to workaround from this PR: #3907

### CODE REVIEW

**Review by pmconne — APPROVED** [review]

**Review by calebmshafer — APPROVED** [review]
LGTM!

**Comment by pmconne** [comment]
@anmolshres98 @calebmshafer I don't understand -- I had made the same change to package.json and run `rush update` and ended up with moment 2.29.2. How did you end up with 2.29.4?
I just did the same thing on release/2.19.x because #3913 is blocked by same problem, and got same result - 2.292.

**Comment by calebmshafer** [comment]
> @anmolshres98 @calebmshafer I don't understand -- I had made the same change to package.json and run `rush update` and ended up with moment 2.29.2. How did you end up with 2.29.4?
> 
> I just did the same thing on release/2.19.x because #3913 is blocked by same problem, and got same result - 2.292.

Try doing a 'rush update --full' or delete the pnpm-lock.yaml and run a rush update. That will force it to update to the latest.

**Comment by anmolshres98** [comment]
> @anmolshres98 @calebmshafer I don't understand -- I had made the same change to package.json and run `rush update` and ended up with moment 2.29.2. How did you end up with 2.29.4? I just did the same thing on release/2.19.x because #3913 is blocked by same problem, and got same result - 2.292.

I faced that issue. What I did was I removed azurite from the package.json in full-stack-tests/backend, ran a rush update which removed moment from the pnpm-lock.yaml then ran rush add -p azurite from inside full-stack-tests/backend directory.

**Pull request merged**
