### PR TITLE
fix ios webpack5 config

### PR DESCRIPTION
**Pull request by aruniverse**
- add native as an external module
- ignore optional peer deps

### CODE REVIEW

**Comment by aruniverse** [comment]
@markschlosseratbentley could you test this out and make sure the ios app builds?

**Comment by aruniverse** [comment]
> @markschlosseratbentley could you test this out and make sure the ios app builds?

We're not running into the OOM error from [before](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=1598490&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=96d68eba-7198-517e-3083-eb7169f4ccb9) now. Also, dta ios backend builds with the changes in here as well now. Looks like more work needs to be done to switch to consuming the native binaries on ios via xcframework so will come back to fixing dta ios after we release 3.3

**Comment by aruniverse** [comment]
@mergifyio backport release/3.3.x

**Comment by calebmshafer** [comment]
@tcobbs-bentley @toddsouthenbentley can you verify this with the Mobile SDK? The DTA is still in a broken state so won't be able to verify that this is actually working.

FWIW, DTA needs to be updated to use the MobileSDK instead of the old way of using the npm packages.

**Review by calebmshafer — APPROVED** [review]

**Comment by tcobbs-bentley** [comment]
@calebmshafer I'm not sure what you mean. Do you just want us to test webpack 5 with the mobile SDK? If so, we can do that.

**Comment by tcobbs-bentley** [comment]
@calebmshafer Also, Arun walked me through setting up @bentley/imodeljs-native as an external plugin (as is done in this PR), and unfortunately that is a definite no-go, as it results in two separate copies of the 350MB mobile native library being in the app.

**Comment by aruniverse** [comment]
> setting up @bentley/imodeljs-native as an external plugin (as is done in this PR), and unfortunately that is a definite no-go

I do think the native pkg should probably be an external; if we removed the CopyExternalPlugin thered only be 1 instance. We just need to figure out how to have the backend resolve the native library from xcframework

**Pull request closed without merging**
