### PR TITLE
`SQLiteDb.withOpenDb` is @internal

### PR DESCRIPTION
**Pull request by kabentley**

### CODE REVIEW

**Comment by pmconne** [comment]
Is this meant to target release/3.3.x instead of master?

**Comment by kabentley** [comment]
> Is this meant to target release/3.3.x instead of master?

yes

**Review by pmconne — DISMISSED** [review]

**Comment by pmconne** [comment]
> yes, though i suppose both.

I assumed you were introducing the function as internal in 3.3 so that you can change its signature in 3.4. Is there any reason why you would want to discourage people from using it?

**Comment by pmconne** [comment]
> Changing its signature here involves too much flux.

Yep. #4078.

**Pull request closed without merging**
