### PR TITLE
Omit auth in RPC communication between mobile frontend and backend

### PR DESCRIPTION
**Pull request by tcobbs-bentley**

### CODE REVIEW

**Review by DanielToby — APPROVED** [review]

**Comment by tcobbs-bentley** [comment]
@calebmshafer I have no idea what is causing the failed check, or ever what is failing. Who can I talk to to track down what the problem is?

**Comment by pmconne** [comment]
@tcobbs-bentley those integration tests have been failing for everyone for a few weeks now - nothing to do with your changes.

**Review by pmconne — APPROVED** [review]

**Comment by calebmshafer** [comment]
@wgoehrig is working on fixing the tests. Last I heard he figured out why but doesn't have a fix yet.

**Comment by aruniverse** [comment]
@mergifyio backport release/3.2.x

**Pull request merged**
