### PR TITLE
Update to rush 5.97 and pnpm 7

### PR DESCRIPTION
**Pull request by calebmshafer**
- The latest major version of pnpm drop Node 12 support.
- Latest Rush version is needed to move up to latest pnpm version

edit: Technically the above is now a lie given pnpm 8 has just been released two days ago.

### CODE REVIEW

**Review by aruniverse — APPROVED** [review]

**Comment by pmconne** [comment]
@calebmshafer @aruniverse do we want to move to rush 5.97 and pnpm 8.3.1 (those are now the latest)?

**Comment by pmconne** [comment]
>  I'll update this PR to the latest versions.

I can work on it.

**Comment by pmconne** [comment]
Fighting with [various issues](https://github.com/microsoft/rushstack/issues/4033), might stick with pnpm 7 for now.

**Comment by aruniverse** [comment]
hopefully this pr can be replaced with https://github.com/iTwin/itwinjs-core/pull/5418, a different approach to updating the audit

**Pull request closed without merging**
