### PR TITLE
upgrade puppeteer to 15.x

### PR DESCRIPTION
**Pull request by anmolshres98**
Upgrade puppeteer for Apple M1 processor support

### CODE REVIEW

**Comment by pmconne** [comment]
IIRC @wgoehrig previously attempted to upgrade puppeteer and discovered the newer version no longer used software rendering by default - looks like that's probably the issue in test failure below. If so, any idea if it can be forced to use software rendering?
```
1) Render Compatibility
     should query proper render compatibility info assuming software rendering ignoring performance caveat:

    AssertionError: expected 1 to equal 2
    + expected - actual

    -1
    +2
    
    at Context.<anonymous> (D:\vsts_a\6\s\core\webgl-compatibility\src\test\Compatibility.test.ts:79:61)
    at callFn (@/lib/runnable.js:366:21)
    at Test$4.Runnable$3.run (@/lib/runnable.js:354:5)
    at Runner.runTest (@/lib/runner.js:666:10)
    at http://localhost:3000/@/lib/runner.js:789:12
    at next (@/lib/runner.js:581:14)
    at http://localhost:3000/@/lib/runner.js:591:7
    at next (@/lib/runner.js:474:14)
    at http://localhost:3000/@/lib/runner.js:559:5
    at timeslice (@/browser-entry.js:100:27)
```

**Comment by anmolshres98** [comment]
> IIRC @wgoehrig previously attempted to upgrade puppeteer and discovered the newer version no longer used software rendering by default - looks like that's probably the issue in test failure below. If so, any idea if it can be forced to use software rendering?
> 
> ```
> 1) Render Compatibility
>      should query proper render compatibility info assuming software rendering ignoring performance caveat:
> 
>     AssertionError: expected 1 to equal 2
>     + expected - actual
> 
>     -1
>     +2
>     
>     at Context.<anonymous> (D:\vsts_a\6\s\core\webgl-compatibility\src\test\Compatibility.test.ts:79:61)
>     at callFn (@/lib/runnable.js:366:21)
>     at Test$4.Runnable$3.run (@/lib/runnable.js:354:5)
>     at Runner.runTest (@/lib/runner.js:666:10)
>     at http://localhost:3000/@/lib/runner.js:789:12
>     at next (@/lib/runner.js:581:14)
>     at http://localhost:3000/@/lib/runner.js:591:7
>     at next (@/lib/runner.js:474:14)
>     at http://localhost:3000/@/lib/runner.js:559:5
>     at timeslice (@/browser-entry.js:100:27)
> ```

I haven't looked into that so far but I will do some research to try and see if that can be done before I try and merge this PR. Thanks

**Review by pmconne — APPROVED** [review]

**Comment by pmconne** [comment]
>  I will do some research to try and see if that can be done before I try and merge this PR.

That's ok, it was never great for the tests to make assumptions. The revised tests are fine.

**Comment by pmconne** [comment]
Fun. I guess I'll look.
```
1) RenderState
     should have expected initial WebGL context state:

    AssertionError: expected 4294967295 to equal 2147483647
    + expected - actual

    -4294967295
    +2147483647
    
    at Context.<anonymous> (agent/_work/1/s/core/frontend/src/test/render/webgl/RenderState.test.ts:291:30)

2) Techniques
     WebGL 2
       should compile all shader programs:
   Error: Timeout of 95000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by pmconne** [comment]
Previously (using software rendering) gl.getParameter for a newly-created webgl context was returning 0xffffffff for STENCIL_WRITEMASK and STENCIL_BACK_WRITEMASK.
This appears to match the behavior described in [the OpenGl reference](https://registry.khronos.org/OpenGL-Refpages/es3.0/html/glStencilMask.xhtml).
> Initially, the mask is all 1's
Now, on both Windows and Linux (presumably also macOS), apparently using the GPU, it is returning 0x7fffffff, with high bit unset.
That seems wrong.

**Comment by pmconne** [comment]
This test failure has been occurring intermittently and is unrelated to your changes.
```
TypeError: Cannot read properties of undefined (reading 'purgeTileTrees')
    at IModelTileRpcImpl.purgeTileTrees (D:\vsts_a\6\s\core\backend\src\rpc-impl\IModelTileRpcImpl.ts:202:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RpcSessionInvocation.resolve (D:\vsts_a\6\s\core\common\src\rpc\core\RpcInvocation.ts:165:14)
    at RpcHandler.request (D:\vsts_a\6\s\core\backend\src\LocalhostIpcHost.ts:68:25)
    at D:\vsts_a\6\s\core\backend\src\IpcHost.ts:160:26
    at IpcWebSocketBackend.dispatch (D:\vsts_a\6\s\core\common\src\ipc\IpcWebSocket.ts:165:22)
```

**Review by wgoehrig — APPROVED** [review]

**Comment by anmolshres98** [comment]
@Mergifyio backport release/3.3.x

**Pull request merged**
