### PR TITLE
Work around Mali G-76 transparency issues

### PR DESCRIPTION
**Pull request by markschlosseratbentley**
Mali G-76 is unable to render transparency when using full floating point textures.  Fall back to non-full floating textures when that chipset is detected (like we do for other similar chipsets).

### CODE REVIEW

**Comment by pmconne** [comment]
A quick web search suggests the Huawei P30 is only 3 years old. Have we compiled a list of known devices affected by this problem and are we making any effort to obtain one?

**Comment by markschlosseratbentley** [comment]
> A quick web search suggests the Huawei P30 is only 3 years old. Have we compiled a list of known devices affected by this problem and are we making any effort to obtain one?

@pmconne [The "Bifrost" Mali series ](https://en.wikipedia.org/wiki/Mali_(GPU)) of GPUs appears to be the common factor.  I think it may be limited to those series of chipsets. At this point, I agree we should try to acquire some "Bifrost" device since it ends up the Bifrost P30 is newer (though still stuck on earlier Android versions).   I'll work on trying to get a Bifrost device for future investigation.

**Review by pmconne — APPROVED** [review]

**Comment by markschlosseratbentley** [comment]
> A quick web search suggests the Huawei P30 is only 3 years old. Have we compiled a list of known devices affected by this problem and are we making any effort to obtain one?
> 
> EDIT: That list includes any non-M1 iOS device running iOS 15, right? Have we tried diagnosing why full-float transparency doesn't work on those devices?

@pmconne RE: non-M1 iOS 15: I just had the same thought; that could be a good avenue to investigate the problem. I'll schedule an item with some info.  iOS gets regular iOS updates that may fix the problem; not sure if it still happens there.

**Comment by markschlosseratbentley** [comment]
> > A quick web search suggests the Huawei P30 is only 3 years old. Have we compiled a list of known devices affected by this problem and are we making any effort to obtain one?
> > EDIT: That list includes any non-M1 iOS device running iOS 15, right? Have we tried diagnosing why full-float transparency doesn't work on those devices?
> 
> @pmconne RE: non-M1 iOS 15: I just had the same thought; that could be a good avenue to investigate the problem. I'll schedule an item with some info. iOS gets regular iOS updates that may fix the problem; not sure if it still happens there.

@pmconne BTW; the iOS issue was investigated originally, and resulted in this workaround.  Maybe we can figure something out more a second time around.

**Comment by markschlosseratbentley** [comment]
@pmconne [FYI; work item for further investigation.](https://github.com/iTwin/itwinjs-core/issues/3964)

**Pull request merged**
