### PR TITLE
Replace calls to deprecated query methods

### LINKED ISSUE #5239: Replace calls to deprecated query methods
Get rid of calls to deprecrated `query`, `queryRowCount`, and `restartQuery` methods and replace them with updated equivalents. 

The linter was suppressed for lines that use these methods in [this commit (#75fee93)](https://github.com/iTwin/itwinjs-core/commit/75fee93073befac92b2984d81a9298c1e7ee68e2). That commit can be used to see where function calls need to be updated.

### PR DESCRIPTION
**Pull request by mattbjordan**
Resolves #5239  

Replaces calls to `query`, `queryRowCount`, and `restartQuery` with `createQueryReader` as the former were deprecated (see #5240).

Most of the refactoring was relatively straightforward. The more unique changes are to `ExecutingECSQL.ts` which has example code and to `FavoritePropertiesManager` and `RulesetEmbedder` tests which required replacing the mocked `query` method with a mocked `createQueryReader` method. 

I believe the only changes not covered by tests are to display-test-app.

### CODE REVIEW

**Comment by pmconne** [comment]
ECSqlReader is entirely undocumented. Will a subsequent PR rectify that?

**Comment by pmconne** [comment]
Was consideration given to providing an API that creates an ECSqlReader internally and iterates over `reader.current`? The new API seems inconveniently verbose vs `query`.

**Comment by mattbjordan** [comment]
> ECSqlReader is entirely undocumented. Will a subsequent PR rectify that?

It is very much on our radar to properly document it early in 4.x. I just created a GitHub issue for it since there was none: #5349

**Comment by mattbjordan** [comment]
> Was consideration given to providing an API that creates an ECSqlReader internally and iterates over `reader.current`? Or at least giving `ECSqlReader` a `[Symbol.iterator]`? The new API seems inconveniently verbose vs `query`.

@khanaffan or @ColinKerr would know more about this

**Comment by pmconne** [comment]
> > Was consideration given to providing an API that creates an ECSqlReader internally and iterates over `reader.current`? Or at least giving `ECSqlReader` a `[Symbol.iterator]`? The new API seems inconveniently verbose vs `query`.
> 
> @khanaffan or @ColinKerr would know more about this

@ColinKerr @khanaffan do you have objections to a better replacement API than the one currently supplied?

**Comment by pmconne** [comment]
@mattbjordan #5240 doesn't explain *why* it deprecated `query`. What was the motivation? Was it just the `any` return type, or something else?

**Review by grigasp — APPROVED** [review]

**Review by khanaffan — APPROVED** [review]

**Review by pmconne — CHANGES_REQUESTED** [review]
@khanaffan please explain why `query` was deprecated.

> @mattbjordan https://github.com/iTwin/itwinjs-core/pull/5240 doesn't explain why it deprecated query. What was the motivation? Was it just the any return type, or something else?

**Comment by ColinKerr** [comment]
> > > > Was consideration given to providing an API that creates an ECSqlReader internally and iterates over `reader.current`? Or at least giving `ECSqlReader` a `[Symbol.iterator]`? The new API seems inconveniently verbose vs `query`.
> > > 
> > > 
> > > @khanaffan or @ColinKerr would know more about this
> > 
> > 
> > @ColinKerr @khanaffan do you have objections to a better replacement API than the one currently supplied?
> 
> I have no issue with the iterator symbol. Though it will by a `Symbol.asyncIterator`.

I agree that having an async iterator based implementation would provide a better API.  I think I would prefer the iterator on the ECSqlReader rather than another method that returns the iterator instead of the reader, but I'm open to other implementations

**Comment by pmconne** [comment]
My concern is the volume of code that needs to be adjusted to respond to this deprecation - not only within itwinjs-core, but outside of it. We are putting an obstacle in our users' upgrade path, which we want to avoid - especially if we can't show a tangible benefit for doing so.

I'd like to see `query`'s return type change from `AsyncIterableIterator<any>` to `AsyncIterableIterator<QueryRowProxy>`.
If that's not possible, I'd like to see an equivalent method to `query` with a different name, again iterating over `QueryRowProxy`.
If neither of those is acceptable (please explain why), make `ECSqlReader` iterable so people can replace `for await (const row of imodel.query(...))` with `for await (const row of imodel.createQueryReader(...))`.
(Regardless of how we address the `query` deprecation, making the reader iterable seems like a no-brainer).

**Comment by pmconne** [comment]
> just replace .query with .createQueryReader where possible, correct?

Yes please.

**Review by pmconne — CHANGES_REQUESTED** [review]
Please add this change to NextVersion.md with example for adjusting existing code to use `createQueryReady` instead of `query`. Everything else looks good.

**Comment by mattbjordan** [comment]
Well I see that you've noticed that I'm done with the refactor. @pmconne 

The one thing of note is that there is a slight quirk since iterating on ECSqlReader returns a QueryRowProxy object and not a raw JavaScript object. I noticed failing tests, seemingly in places where a comparison was made against the returned row. So basically, if you want to do anything with the returned row other than simply accessing the row values, you can call `.toRow()` on it to get a raw JavaScript object back instead - which is exactly what most of the previous code assumed it was working with. I.e.,

```ts
for await (const queryRow of iModel.createQueryReader(queryString)) {
    jsObjectRow = queryRow.toRow();
    // ...
}
```

So if any issues pop up in the future because of these changes, calling `.toRow()` will probably fix it.

I'll probably note this quirk in what I write in NextVersion.md.

**Review by ColinKerr — APPROVED** [review]

**Review by calebmshafer — APPROVED** [review]

**Pull request merged**
