### PR TITLE
@bentley/imodeljs-native 3.4.16

### PR DESCRIPTION
**Pull request by pmconne**

### CODE REVIEW

**Review by calebmshafer — APPROVED** [review]

**Review by dassaf4 — APPROVED** [review]

**Comment by pmconne** [comment]
@aruniverse magic comments plugin tests failed again.

**Comment by pmconne** [comment]
@calebmshafer display-test-app failed to build for iOS.
```
note: Using new build system
note: Using codesigning identity override: 
note: Planning build
note: Constructing build description
CreateBuildDirectory /Users/platform-bld/Library/Developer/Xcode/DerivedData/imodeljs-test-app-bhlwsrmhanwezuhhrciejzdennda/SourcePackages/checkouts/AppAuth-iOS (in target 'AppAuth' from project 'AppAuth')
    cd /Users/platform-bld/Library/Developer/Xcode/DerivedData/imodeljs-test-app-bhlwsrmhanwezuhhrciejzdennda/SourcePackages/checkouts/AppAuth-iOS
    builtin-create-build-directory /Users/platform-bld/Library/Developer/Xcode/DerivedData/imodeljs-test-app-bhlwsrmhanwezuhhrciejzdennda/SourcePackages/checkouts/AppAuth-iOS

CreateBuildDirectory /Volumes/Builds/vsts_work_a/62/s/test-apps/display-test-app/ios/imodeljs-test-app (in target 'imodeljs-test-app' from project 'imodeljs-test-app')
    cd /Volumes/Builds/vsts_work_a/62/s/test-apps/display-test-app/ios/imodeljs-test-app
    builtin-create-build-directory /Volumes/Builds/vsts_work_a/62/s/test-apps/display-test-app/ios/imodeljs-test-app

WriteAuxiliaryFile /AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/Objects-normal/x86_64/AppAuthCore.o.LinkFileList (in target 'AppAuthCore' from project 'AppAuth')
    cd /Users/platform-bld/Library/Developer/Xcode/DerivedData/imodeljs-test-app-bhlwsrmhanwezuhhrciejzdennda/SourcePackages/checkouts/AppAuth-iOS
    write-file /AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/Objects-normal/x86_64/AppAuthCore.o.LinkFileList
error: unable to write file '/AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/Objects-normal/x86_64/AppAuthCore.o.LinkFileList': fopen(/AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/Objects-normal/x86_64/AppAuthCore.o.LinkFileList, wb): No such file or directory (2) (in target 'AppAuthCore' from project 'AppAuth')

WriteAuxiliaryFile /AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/AppAuthCore.modulemap (in target 'AppAuthCore' from project 'AppAuth')
    cd /Users/platform-bld/Library/Developer/Xcode/DerivedData/imodeljs-test-app-bhlwsrmhanwezuhhrciejzdennda/SourcePackages/checkouts/AppAuth-iOS
    write-file /AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/AppAuthCore.modulemap
error: unable to write file '/AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/AppAuthCore.modulemap': fopen(/AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/AppAuthCore.modulemap, wb): No such file or directory (2) (in target 'AppAuthCore' from project 'AppAuth')

** BUILD FAILED **


The following build commands failed:
	WriteAuxiliaryFile /AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/Objects-normal/x86_64/AppAuthCore.o.LinkFileList
	WriteAuxiliaryFile /AppAuth.build/Debug-iphonesimulator/AppAuthCore.build/AppAuthCore.modulemap
(2 failures)
##[error]Bash exited with code '65'.
```

**Comment by pmconne** [comment]
@MichaelBelousov race condition?

```
  1) ECReferenceTypesCache
       should not init schemas of a lower or equal version:
     Error: EBUSY: resource busy or locked, unlink 'D:\vsts_b\109\s\core\backend\lib\cjs\test\output\ECReferenceTypesCache\empty.bim'
      at Object.unlinkSync (node:fs:1718:3)
      at Function.unlinkSync (D:\vsts_b\109\s\core\backend\src\IModelJsFs.ts:42:57)
      at Function.prepareOutputFile (D:\vsts_b\109\s\core\backend\src\test\IModelTestUtils.ts:282:18)
      at Context.<anonymous> (src\test\standalone\ECReferenceTypesCache.test.ts:129:43)
      at processImmediate (node:internal/timers:464:21)
```

**Comment by pmconne** [comment]
@MichaelBelousov 

```
2022-09-25T23:26:39.2182260Z   1) IModelTransformer
2022-09-25T23:26:39.2183010Z        handle out-of-order references in aspects during consolidations:
2022-09-25T23:26:39.2183980Z      AssertionError: expected promise to be fulfilled but it was rejected with 'Error: 0x21 has not been inserted int…'
2022-09-25T23:26:39.2184470Z   
2022-09-25T23:26:39.2184610Z 
2022-09-25T23:26:39.2184880Z   2) IModelTransformer
2022-09-25T23:26:39.2185300Z        returns ids in order when exporting multiple ElementMultiAspect of multiple classes:
2022-09-25T23:26:39.2185790Z      AssertionError: Unspecified AssertionError
2022-09-25T23:26:39.2186270Z       at Context.<anonymous> (src/test/standalone/IModelTransformer.test.ts:1938:13)
2022-09-25T23:26:39.2186570Z 
2022-09-25T23:26:39.2186860Z   3) test resuming transformations
2022-09-25T23:26:39.2187250Z        resume old state after partially committed changes:
2022-09-25T23:26:39.2187480Z 
2022-09-25T23:26:39.2188140Z       AssertionError: expected '0' to not equal '0'
2022-09-25T23:26:39.2188860Z       + expected - actual
2022-09-25T23:26:39.2189050Z 
2022-09-25T23:26:39.2189190Z 
2022-09-25T23:26:39.2189590Z       at assertIdentityTransformation (src/test/IModelTransformerUtils.ts:361:37)
2022-09-25T23:26:39.2190170Z       at async Context.<anonymous> (src/test/standalone/IModelTransformerResumption.test.ts:319:5)
2022-09-25T23:26:39.2190490Z 
2022-09-25T23:26:39.2190790Z   4) test resuming transformations
2022-09-25T23:26:39.2191160Z        should fail to resume from an old target:
2022-09-25T23:26:39.2191560Z      AssertionError: expected [Function] to throw an error
2022-09-25T23:26:39.2192070Z       at Context.<anonymous> (src/test/standalone/IModelTransformerResumption.test.ts:402:17)
2022-09-25T23:26:39.2192380Z 
2022-09-25T23:26:39.2192680Z   5) test resuming transformations
2022-09-25T23:26:39.2193100Z        should fail to resume from an old target while processing relationships:
2022-09-25T23:26:39.2193540Z      BE_SQLITE_ERROR: SQLite Bind error
2022-09-25T23:26:39.2194190Z       at SqliteStatement.checkBind (/Volumes/Builds/vsts_work_a/52/s/core/backend/src/SqliteStatement.ts:163:13)
2022-09-25T23:26:39.2194830Z       at SqliteStatement.bindId (/Volumes/Builds/vsts_work_a/52/s/core/backend/src/SqliteStatement.ts:191:10)
2022-09-25T23:26:39.2195450Z       at /Volumes/Builds/vsts_work_a/52/s/core/transformer/lib/cjs/IModelCloneContext.js:46:1467
2022-09-25T23:26:39.2196070Z       at SQLiteDb.withPreparedSqliteStatement (/Volumes/Builds/vsts_work_a/52/s/core/backend/src/SQLiteDb.ts:155:19)
2022-09-25T23:26:39.2196660Z       at IModelCloneContext.saveStateToDb (lib/cjs/IModelCloneContext.js:46:1133)
2022-09-25T23:26:39.2197220Z       at CountdownToCrashTransformer.saveStateToDb (src/IModelTransformer.ts:411:6)
2022-09-25T23:26:39.2197770Z       at CountdownToCrashTransformer.saveStateToFile (src/IModelTransformer.ts:429:6)
2022-09-25T23:26:39.2198350Z       at Context.<anonymous> (src/test/standalone/IModelTransformerResumption.test.ts:568:19)
2022-09-25T23:26:39.2198660Z 
```

**Comment by pmconne** [comment]
@MichaelBelousov 
```2022-09-26T07:22:38.9025570Z   1) IModelTransformer
2022-09-26T07:22:38.9026330Z        handle out-of-order references in aspects during consolidations:
2022-09-26T07:22:38.9027350Z      AssertionError: expected promise to be fulfilled but it was rejected with 'Error: 0x21 has not been inserted int…'
2022-09-26T07:22:38.9028030Z   
2022-09-26T07:22:38.9028200Z 
2022-09-26T07:22:38.9028480Z   2) IModelTransformer
2022-09-26T07:22:38.9028940Z        returns ids in order when exporting multiple ElementMultiAspect of multiple classes:
2022-09-26T07:22:38.9029440Z      AssertionError: Unspecified AssertionError
2022-09-26T07:22:38.9029950Z       at Context.<anonymous> (src/test/standalone/IModelTransformer.test.ts:1938:13)
2022-09-26T07:22:38.9030240Z 
2022-09-26T07:22:38.9030700Z   3) test resuming transformations
2022-09-26T07:22:38.9031130Z        resume old state after partially committed changes:
2022-09-26T07:22:38.9031350Z 
2022-09-26T07:22:38.9032080Z       AssertionError: expected '0' to not equal '0'
2022-09-26T07:22:38.9032830Z       + expected - actual
2022-09-26T07:22:38.9033030Z 
2022-09-26T07:22:38.9033200Z 
2022-09-26T07:22:38.9033600Z       at assertIdentityTransformation (src/test/IModelTransformerUtils.ts:378:37)
2022-09-26T07:22:38.9034210Z       at async Context.<anonymous> (src/test/standalone/IModelTransformerResumption.test.ts:335:5)
2022-09-26T07:22:38.9034560Z 
2022-09-26T07:22:38.9034890Z   4) test resuming transformations
2022-09-26T07:22:38.9035260Z        should fail to resume from an old target:
2022-09-26T07:22:38.9035850Z      AssertionError: expected [Function] to throw an error
2022-09-26T07:22:38.9036400Z       at Context.<anonymous> (src/test/standalone/IModelTransformerResumption.test.ts:418:17)
2022-09-26T07:22:38.9036700Z 
2022-09-26T07:22:38.9037040Z   5) test resuming transformations
2022-09-26T07:22:38.9037480Z        should fail to resume from an old target while processing relationships:
2022-09-26T07:22:38.9037940Z      BE_SQLITE_ERROR: SQLite Bind error
2022-09-26T07:22:38.9038640Z       at SqliteStatement.checkBind (/Volumes/Builds/vsts_work_a/73/s/core/backend/src/SqliteStatement.ts:163:13)
2022-09-26T07:22:38.9039300Z       at SqliteStatement.bindId (/Volumes/Builds/vsts_work_a/73/s/core/backend/src/SqliteStatement.ts:191:10)
2022-09-26T07:22:38.9039950Z       at /Volumes/Builds/vsts_work_a/73/s/core/transformer/lib/cjs/IModelCloneContext.js:46:1467
2022-09-26T07:22:38.9040550Z       at SQLiteDb.withPreparedSqliteStatement (/Volumes/Builds/vsts_work_a/73/s/core/backend/src/SQLiteDb.ts:155:19)
2022-09-26T07:22:38.9041300Z       at IModelCloneContext.saveStateToDb (lib/cjs/IModelCloneContext.js:46:1133)
2022-09-26T07:22:38.9041890Z       at CountdownToCrashTransformer.saveStateToDb (src/IModelTransformer.ts:412:6)
2022-09-26T07:22:38.9042470Z       at CountdownToCrashTransformer.saveStateToFile (src/IModelTransformer.ts:430:6)
2022-09-26T07:22:38.9043070Z       at Context.<anonymous> (src/test/standalone/IModelTransformerResumption.test.ts:584:19)
2022-09-26T07:22:38.9043380Z 
2022-09-26T07:22:38.9043720Z   6) test resuming transformations
2022-09-26T07:22:38.9044590Z        should succeed to resume from an up-to-date target while processing relationships:
2022-09-26T07:22:38.9045130Z      BE_SQLITE_ERROR: SQLite Bind error
2022-09-26T07:22:38.9045670Z       at SqliteStatement.checkBind (/Volumes/Builds/vsts_work_a/73/s/core/backend/src/SqliteStatement.ts:163:13)
2022-09-26T07:22:38.9046290Z       at SqliteStatement.bindId (/Volumes/Builds/vsts_work_a/73/s/core/backend/src/SqliteStatement.ts:191:10)
2022-09-26T07:22:38.9047060Z       at /Volumes/Builds/vsts_work_a/73/s/core/transformer/lib/cjs/IModelCloneContext.js:46:1467
2022-09-26T07:22:38.9047710Z       at SQLiteDb.withPreparedSqliteStatement (/Volumes/Builds/vsts_work_a/73/s/core/backend/src/SQLiteDb.ts:155:19)
2022-09-26T07:22:38.9048330Z       at IModelCloneContext.saveStateToDb (lib/cjs/IModelCloneContext.js:46:1133)
2022-09-26T07:22:38.9048910Z       at CountdownToCrashTransformer.saveStateToDb (src/IModelTransformer.ts:412:6)
2022-09-26T07:22:38.9049490Z       at CountdownToCrashTransformer.saveStateToFile (src/IModelTransformer.ts:430:6)
2022-09-26T07:22:38.9050130Z       at /Volumes/Builds/vsts_work_a/73/s/core/transformer/src/test/standalone/IModelTransformerResumption.test.ts:620:21
2022-09-26T07:22:38.9050970Z       at async Context.<anonymous> (src/test/standalone/IModelTransformerResumption.test.ts:604:28)
```

**Comment by pmconne** [comment]
Closing due to issues with transformation changes.

**Pull request closed without merging**
