### PR TITLE
Fix point cloud voxel size issues for additive refinement pnts

### PR DESCRIPTION
**Pull request by DStradley**
Fixes [#5335](https://github.com/iTwin/itwinjs-core/issues/5335)

When using voxel-sized points for additive tile refinement point clouds, we get a confusing mix of different-sized points which results in lower visual quality.  After investigating, could not find a good solution for calculating voxel sizes for this case since the additive tiles can overlap and can be displayed at the same time.  Decided to force it to pixel mode for these cases.

Implemented by setting voxelSize to 0 for additive refinement tiles.  This will cause them to draw with minPixelsPerVoxel, which defaults to 2.  That way, it will draw as if in pixel mode, and voxelScale will still function.  Checking across a variety of 10 point clouds, 2 to 4 seems to work well for pixel settings (depending on the cloud), so 2 is a decent default here.

TODO
- [x] Run ImageTests

### CODE REVIEW

**Review by pmconne — APPROVED** [review]
> Implemented by setting voxelSize to 0 for additive refinement tiles.

Nice solution.

Run `rush change` before publishing.

**Comment by aruniverse** [comment]
> @aruniverse what are the correct invocations to manually trigger the docs and integration jobs?

I know GH was having service issues earlier todays, and pipelines were degraded, was hoping that was it. Looks like theyre back up now, so guess that wasn't it.

There might've been a service connection that was accidentally removed, investigating...

**Comment by pmconne** [comment]
> investigating...

I was able to manually trigger each individually. Should `/azp run iTwin.js` have triggered them all?

**Comment by pmconne** [comment]
Test failed on Linux and Windows. I suspect #5298 is relevant?

```
--[ FAILURE: core-full-stack-tests ]------------------------[ 32.88 seconds ]--

WARNING: Tests attempted to load missing asset: "/locales/en-US/CoreTools.json"
WARNING: Tests attempted to load missing asset: "/locales/en/iModelJs.json"
WARNING: Tests attempted to load missing asset: "/locales/en-US/iModelJs.json"
WARNING: Tests attempted to load missing asset: "/locales/en/CoreTools.json"
WARNING: Tests attempted to load missing asset: "/images/imodeljs-icon.svg"
WARNING: Tests attempted to load missing asset: "/locales/en-US/Editor.json"
WARNING: Tests attempted to load missing asset: "/locales/en/Editor.json"
TypeError: Cannot read properties of undefined (reading 'purgeTileTrees')
    at IModelTileRpcImpl.purgeTileTrees (D:\vsts_a\4\s\core\backend\src\rpc-impl\IModelTileRpcImpl.ts:201:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at RpcSessionInvocation.resolve (D:\vsts_a\4\s\core\common\src\rpc\core\RpcInvocation.ts:168:14)
    at RpcHandler.request (D:\vsts_a\4\s\core\backend\src\LocalhostIpcHost.ts:68:25)
    at D:\vsts_a\4\s\core\backend\src\IpcHost.ts:161:26
    at IpcWebSocketBackend.processMessages (D:\vsts_a\4\s\core\common\src\ipc\IpcWebSocket.ts:175:26)
    at IpcWebSocketBackend.dispatch (D:\vsts_a\4\s\core\common\src\ipc\IpcWebSocket.ts:159:5)
```

**Comment by aruniverse** [comment]
I suspect it actually might be #5400 , looks like it dropped some changes made in #4067 which was to resolve #4044

5400:
image

4067:
image

@swbsi

**Comment by pmconne** [comment]
@mergifyio backport release/3.7.x

**Comment by DStradley** [comment]
@Mergifyio backport release/3.7.x

**Pull request merged**
