### PR TITLE
Bug fix for hydrateViewState

### PR DESCRIPTION
**Pull request by nick4598**
Induced by #3326

### CODE REVIEW

**Comment by markschlosseratbentley** [comment]
I kicked off an Image Tests run on this branch to verify all differences are fixed.

**Review by markschlosseratbentley — DISMISSED** [review]
Make sure Image Tests successfully completes before merging in PR.

**Comment by pmconne** [comment]
I am confused as to how none of the integration tests in SheetViewState.test.ts and HyperModeling.test.ts failed.

**Comment by nick4598** [comment]
> I am confused as to how none of the integration tests in SheetViewState.test.ts and HyperModeling.test.ts failed.

A lot of the tests in sheetviewstate.test.ts, seem to focus on view attachments which I believe were handled correctly. 

Since I failed to call super.postload in ViewState2d, that means the subcategories cache was never populated (its populated in ViewState's postload), which I believe is why sheets were blank. I was thinking I needed to add a test which checks that the subcategories are populated properly.

**Comment by pmconne** [comment]
@nick4598 that makes sense - those views only contain view attachments, and we were loading the tiles for them but not displaying any of their contents because of the subcategories.

A test that displays a sheet and verifies that more than just the background and border are displayed would catch a much broader range of regressions.

**Comment by DStradley** [comment]
> Make sure Image Tests successfully completes before merging in PR.

I have gone over the results from the ImageTests  that @markschlosseratbentley initiated, and they all look good now.

**Review by pmconne — APPROVED** [review]

**Comment by pmconne** [comment]
I am merging without regression test to get the fix in ASAP.

**Pull request merged**
