### PR TITLE
Update @itwin/object-storage to 2.2.5

### PR DESCRIPTION
**Pull request by pmconne**
Reverts #7078 now that [CVE](https://github.com/advisories/GHSA-8hc4-vh64-cxmj) is patched.

### CODE REVIEW

**Comment by pmconne** [comment]
Wheee...
```
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ high                │ Server-Side Request Forgery in axios                   │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ axios                                                  │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ >=1.3.2 <=1.7.3                                        │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Patched versions    │ >=1.7.4                                                │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Paths               │ ../../full-stack-tests/core >                          │
│                     │ @itwin/reality-data-client@1.2.1 > axios@1.7.3         │
│                     │                                                        │
│                     │ ../../test-apps/display-performance-test-app >         │
│                     │ @itwin/reality-data-client@1.2.1 > axios@1.7.3         │
│                     │                                                        │
│                     │ ../../test-apps/display-test-app >                     │
│                     │ @itwin/reality-data-client@1.2.1 > axios@1.7.3         │
│                     │                                                        │
│                     │ ... Found 42 paths, run `pnpm why axios` for more      │
│                     │ information                                            │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ More info           │ https://github.com/advisories/GHSA-8hc4-vh64-cxmj      │
└─────────────────────┴────────────────────────────────────────────────────────┘
```

**Comment by pmconne** [comment]
Fun! @austeja-bentley 
```
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ high                │ Server-Side Request Forgery in axios                   │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ axios                                                  │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ >=1.3.2 <=1.7.3                                        │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Patched versions    │ >=1.7.4                                                │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Paths               │ ../../full-stack-tests/backend >                       │
│                     │ @itwin/imodels-access-backend@5.1.2 >                  │
│                     │ @itwin/imodels-access-common@5.1.2 >                   │
│                     │ @itwin/imodels-client-management@5.6.0 > axios@1.6.8   │
│                     │                                                        │
│                     │ ../../full-stack-tests/backend >                       │
│                     │ @itwin/imodels-access-backend@5.1.2 >                  │
│                     │ @itwin/imodels-client-authoring@5.6.0 >                │
│                     │ @itwin/imodels-client-management@5.6.0 > axios@1.6.8   │
│                     │                                                        │
│                     │ ../../full-stack-tests/backend >                       │
│                     │ @itwin/imodels-access-backend@5.1.2 > axios@1.6.8      │
│                     │                                                        │
│                     │ ... Found 39 paths, run `pnpm why axios` for more      │
│                     │ information                                            │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ More info           │ https://github.com/advisories/GHSA-8hc4-vh64-cxmj      │
└─────────────────────┴────────────────────────────────────────────────────────┘
```

**Review by aruniverse — APPROVED** [review]

**Comment by pmconne** [comment]
Waiting on https://github.com/iTwin/imodels-clients/pull/272

**Comment by austeja-bentley** [comment]
> Waiting on [iTwin/imodels-clients#272](https://github.com/iTwin/imodels-clients/pull/272)

released new versions:
@itwin/imodels-client-management, @itwin/imodels-client-authoring - **5.8.1**
@itwin/imodels-access-frontend, @itwin/imodels-access-backend - **5.2.1**

**Review by ColinKerr — APPROVED** [review]

**Comment by ben-polinsky** [comment]
@mergifyio backport release/4.8.x

**Pull request merged**
