### PR TITLE
Usable instructions for debugging display-test-app backend.

### PR DESCRIPTION
**Pull request by pmconne**
The entry points in .vscode/launch.json haven't worked in ages.

### CODE REVIEW

**Comment by pmconne** [comment]
> What do you observe isn't working?

ERR_CONN_REFUSED, electron window never opens, etc.

**Comment by calebmshafer** [comment]
Nope since we didn't document it but yes that's how the workflow should be.

1. `npm run build:backend`
2. `npm run start:webserver`
3. Start debug config

Any time you make a change in the frontend then, it will automatically reload the frontend. This will also work if you can a dependent package in the repo, just run an `npm run build` there and the frontend will automatically refresh with the change.

Then if you want a change to the backend, you do need to run `npm run build:backend` and re-start the debug config.

Optionally for the backend you could do, `npm run build:backend -- --watch` which will compile any change to the backend right away. you'd still need to re-start the debug config to have it start and allow debugging of the changes.

**Comment by pmconne** [comment]
@calebmshafer thanks - `-- watch` is also news to me.
I had always done `start npm run start` and until a while ago electron would hot reload if I changed dta frontend code or rebuilt any of its dependencies.

**Comment by calebmshafer** [comment]
@pmconne @bbastings let me know what you think of the new steps.

@bbastings I also fixed the editor breakpoints so you should now be able to debug directly in those packages as well.

**Comment by pmconne** [comment]
> I also fixed the editor breakpoints so you should now be able to debug directly in those packages as well.

Did you push that change to a different branch?

**Pull request merged**
