### PR TITLE
RpcBriefcaseUtility.openBriefcase supports multiple concurrent downloads

### PR DESCRIPTION
**Pull request by paulius-valiunas**

### CODE REVIEW

**Review by pmconne — APPROVED** [review]

**Review by aruniverse — APPROVED** [review]

**Comment by paulius-valiunas** [comment]
https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=2590561&view=logs&j=4aa4172e-637e-5768-b518-2d8dfafc7ab0&s=b15d9194-8f26-5328-b47f-5968c76b37e7&t=8eecb1f5-5b40-5ae7-7ad4-1a56e22d11f9&l=2523
this is failing repeatedly, it doesn't look like it's related to my changes

**Comment by pmconne** [comment]
> https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=2590561&view=logs&j=4aa4172e-637e-5768-b518-2d8dfafc7ab0&s=b15d9194-8f26-5328-b47f-5968c76b37e7&t=8eecb1f5-5b40-5ae7-7ad4-1a56e22d11f9&l=2523 this is failing repeatedly, it doesn't look like it's related to my changes

@khanaffan @tcobbs-bentley 

```
[Mocha_Result_XML]:   <testsuite name="Changeset Reader API" timestamp="2023-12-22T12:05:51" tests="1" time="0.6210" failures="1">
[Mocha_Result_XML]:     <testcase name="Changeset Reader API Changeset reader / EC adaptor" time="0.6160" classname="Changeset reader / EC adaptor">
[Mocha_Result_XML]:       <failure message="expected &apos;0x3d&apos; to equal &apos;0x3f&apos;" type="AssertionError"><![CDATA[AssertionError: expected '0x3d' to equal '0x3f'
[Mocha_Result_XML]:     at Context.<anonymous> (main.js:155478:27)]]></failure>
```

**Comment by kabentley** [comment]
I don't understand why this function even exists. Who uses it and why?

**Comment by tcobbs-bentley** [comment]
I don't know what the test is trying to do, but I think that the failure is that the changeset ID is changing. Also, the failure is happening when the test is run on an iOS simulator. @khanaffan, do you know what might be happening?

**Comment by paulius-valiunas** [comment]
> I don't understand why this function even exists. Who uses it and why?
> 
> Nobody should use a downloaded briefcase from a web application, and nobody should use RPC for a desktop application. Is this just from tests?

No idea, I found this bug accidentally when looking through the source code for something else. I don't want to go into detail about whether this whole class is needed or not, but I took patching this bug as a top priority and didn't want to postpone it to achieve some bigger/better refactor. IMHO, this kind of code with critical security flaws (the possibility to open a completely different iModel than what was requested) has no right to exist in our code base, even if no one uses it.

**Comment by kabentley** [comment]
> No idea, I found this bug accidentally when looking through the source code for something else. I don't want to go into detail about whether this whole class is needed or not, but I took patching this bug as a top priority and didn't want to postpone it to achieve some bigger/better refactor. IMHO, this kind of code with critical security flaws (the possibility to open a completely different iModel than what was requested) has no right to exist in our code base, even if no one uses it.

This whole concept (opening a briefcase from RPC) should be removed, not "patched" and propagated. Only checkpoints may safely be opened from RPC. I suggest you simply remove the `openBriefcase` function and throw an exception if anyone is still using `SynchMode.PullOnly` or `SynchMode.PullAndPush`  (and deprecate them).

**Comment by paulius-valiunas** [comment]
> This whole concept (opening a briefcase from RPC) should be removed, not "patched" and propagated. Only checkpoints may safely be opened from RPC. I suggest you simply remove the `openBriefcase` function and throw an exception if anyone is still using `SynchMode.PullOnly` or `SynchMode.PullAndPush` (and deprecate them).

I patched it not because I want people to use it, but because that was much faster than deprecating, removing chunks of code and then fixing all the unit tests that use it. I do agree it should be removed, but I would like that to be a part of a bigger refactor, i.e. getting rid of `RpcBriefcaseUtility` altogether. I'd prefer not to keep this trap in the code base while we wait for someone to find the time for that and to fix all the unit tests that will be broken.

**Comment by kabentley** [comment]
I agree there should definitely be a refactoring to remove the whole concept. It was never a good idea and has lots of other serious implications that can't be ignored (disk space, security, performance, etc.), Fortunately we don't use it anymore and it can safely be removed. If you're not going to do that here/now (when?), I definitely think the right thing to do is to disable it somehow for *our* backends. We can't leave this gaping hole open.

At the very least you should deprecate the `SyncMode` members in this PR.

**Comment by paulius-valiunas** [comment]
Well, there is no code path in the public API that uses this, and `RpcBriefcaseUtility` is not exported in the barrel file, so I hope our backends are already not using it. I added deprecation tags so if someone is somehow using it, they will get an additional warning.

**Comment by khanaffan** [comment]
> > > https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=2590561&view=logs&j=4aa4172e-637e-5768-b518-2d8dfafc7ab0&s=b15d9194-8f26-5328-b47f-5968c76b37e7&t=8eecb1f5-5b40-5ae7-7ad4-1a56e22d11f9&l=2523 this is failing repeatedly, it doesn't look like it's related to my changes
> > 
> > 
> > @khanaffan @tcobbs-bentley
> > ```
> > [Mocha_Result_XML]:   <testsuite name="Changeset Reader API" timestamp="2023-12-22T12:05:51" tests="1" time="0.6210" failures="1">
> > [Mocha_Result_XML]:     <testcase name="Changeset Reader API Changeset reader / EC adaptor" time="0.6160" classname="Changeset reader / EC adaptor">
> > [Mocha_Result_XML]:       <failure message="expected &apos;0x3d&apos; to equal &apos;0x3f&apos;" type="AssertionError"><![CDATA[AssertionError: expected '0x3d' to equal '0x3f'
> > [Mocha_Result_XML]:     at Context.<anonymous> (main.js:155478:27)]]></failure>
> > ```
> 
> that's me working on it.

https://github.com/iTwin/itwinjs-core/pull/6334

**Pull request merged**
