### PR TITLE
Fixed DuplicateSchema error with multiple async getSchema calls

### PR DESCRIPTION
**Pull request by RohitPtnkr1996**
The getSchema() in ECSchemaRPCLocater internally calls the Schema.fromJSON().
When reading the schema, a call is made to context.addSchema() so as to be able to locate schemaItems within the context.
However, there is no check when calling addSchema() to see if the schema has already been loaded.

Hence, if multiple async calls are made to getSchema(), every getSchema() call after the first will throw a DuplicateSchema error as it tried to load the schema again.

I've added a check to see if the schema has already been cached.
addSchema() is only called if the schema is not present in the context.

### CODE REVIEW

**Comment by pmconne** [comment]
Wouldn't it be more robust and more efficient to ensure that, if another request for the same schema comes into `getSchema` while you awaiting the result of a previous request, the second (and subsequent) requests await the same result rather than duplicating and then discarding the work being done on behalf of the first request?

**Comment by ColinKerr** [comment]
> Wouldn't it be more robust and more efficient to ensure that, if another request for the same schema comes into `getSchema` while you awaiting the result of a previous request, the second (and subsequent) requests await the same result rather than duplicating and then discarding the work being done on behalf of the first request?

@pmconne makes a good point.  if the schema is already in the context do we need to proceed and do all the work we do AFTER we add the schema to the context?  One concern with this is that it is possible that there could be a partially loaded schema already in the cache.  By running through the schema and forcing everything to load we ensure that the schema is fully loaded when the method returns.  If we are getting into this partial load case I suspect that there is a bug but it's worth making sure @AkshayN5 considers this as he is working on async schema loading

Over all I think the right thing to do here is to include all work to load the schema in the check for the schema already existing in the cache.  If it already exists in the cache all the work should be skipped.

**Comment by RohitPtnkr1996** [comment]
I had a look at the PR #1542 and this issue has been resolved in it.
The partially loaded schema check has also been catered to.
I had a call with Akshay and will be adding this test scenario to his branch.

Abandoning this PR.

**Pull request closed without merging**
