### PR TITLE
Add support for Electron 28

### PR DESCRIPTION
**Pull request by GytisCepk**
#### Changes:
- Extend range of supported Electron versions with Electron 28.
- Increase Electron dev dependency version to `^28.0.0`.

No code changes required since core doesn't use [APIs changed in 28](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#planned-breaking-api-changes-280).

### CODE REVIEW

**Comment by pmconne** [comment]
@tcobbs-bentley error with Android display-test-app reported in #6263 recurred here.
```
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Failed to transform mobile-native-android-4.3.5.aar (com.github.itwin:mobile-native-android:4.3.5) to match attributes {artifactType=android-databinding, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not download mobile-native-android-4.3.5.aar (com.github.itwin:mobile-native-android:4.3.5)
         > Could not get resource 'https://maven.pkg.github.com/itwin/mobile-sdk-android/com/github/itwin/mobile-native-android/4.3.5/mobile-native-android-4.3.5.aar'.
            > Could not HEAD 'https://maven.pkg.github.com/itwin/mobile-sdk-android/com/github/itwin/mobile-native-android/4.3.5/mobile-native-android-4.3.5.aar'.
               > Certificate for <maven.pkg.github.com> doesn't match any of the subject alternative names: [*.registry.github.com, registry.github.com]
```

**Review by pmconne — APPROVED** [review]

**Review by aruniverse — APPROVED** [review]

**Comment by tcobbs-bentley** [comment]
> @tcobbs-bentley error with Android display-test-app reported in #6263 recurred here.
> 
> ```
> Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> > Could not resolve all files for configuration ':app:debugCompileClasspath'.
>    > Failed to transform mobile-native-android-4.3.5.aar (com.github.itwin:mobile-native-android:4.3.5) to match attributes {artifactType=android-databinding, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
>       > Could not download mobile-native-android-4.3.5.aar (com.github.itwin:mobile-native-android:4.3.5)
>          > Could not get resource 'https://maven.pkg.github.com/itwin/mobile-sdk-android/com/github/itwin/mobile-native-android/4.3.5/mobile-native-android-4.3.5.aar'.
>             > Could not HEAD 'https://maven.pkg.github.com/itwin/mobile-sdk-android/com/github/itwin/mobile-native-android/4.3.5/mobile-native-android-4.3.5.aar'.
>                > Certificate for <maven.pkg.github.com> doesn't match any of the subject alternative names: [*.registry.github.com, registry.github.com]
> ```

I suspect that there is a problem with one or more of the CI Macs, and it succeeds when rerun due to being on a different Mac. @chuckkir: Any thoughts on this?

**Comment by tcobbs-bentley** [comment]
[This StackOverflow answer](https://stackoverflow.com/questions/72168009/error-while-generating-build-from-jenkins) claims that this certificate error is fixed by updating the local Java version. However, I thought that the CI build process used Java from a upack, so I don't understand why it would fail intermittently.

**Comment by chuckkir** [comment]
Java is not intentionally installed on any of the CI machines.

**Comment by tcobbs-bentley** [comment]
I can't find the failed pipeline run. The successful one seems to have run on BuildMacM1Minion53-A.

**Comment by tcobbs-bentley** [comment]
I investigated further, and my Python script to build and run display-test-app for Android (which only runs on Macs) installs the openjdk_macos upack, version 11.0.1-0. So this version is indeed one that the StackOverflow answer claimed would cause this problem, but since it usually works, I'm not sure what is going on. I will investigate creating a JDK upack with a newer version.

**Pull request merged**
