### PR TITLE
Prune unnecessary deps and update rush audit [release/3.7.x]

### PR DESCRIPTION
**Pull request by aruniverse**
Based on #5397.

### CODE REVIEW

**Review by paulius-valiunas — APPROVED** [review]

**Comment by pmconne** [comment]
This is approximately a backport of #5397?

**Comment by aruniverse** [comment]
> This is approximately a backport of #5397?

Yes. Mostly. Didn't remove base64-js because we still support node 12 and need the polyfill.

Couldn't remove the dep on azure/storage-blob in core-backend. 

Need to do one more pass at this pr, just triggered to get pipelines ready for paulius. Will update title and description shortly.

**Review by mdastous-bentley — APPROVED** [review]

**Review by ben-polinsky — APPROVED** [review]

**Review by dassaf4 — APPROVED** [review]

**Review by saskliutas — APPROVED** [review]

**Pull request merged**
