### PR TITLE
Add Support for APIM RDS url to create RealityDataSourceKey from tilesetUrl

### PR DESCRIPTION
**Pull request by MarcBedard8**
Support url returned by new reality-data-client (APIM) in create RealityDataSourceKey from tilesetUrl.
New url looks like this one:
https://api.bentley.com/realitydata/{id}?projectId={itwinId}

### CODE REVIEW

**Review by pmconne — APPROVED** [review]

**Comment by MarcBedard8** [comment]
@Mergifyio update

**Comment by MarcBedard8** [comment]
@pmconne @calebmshafer Build failed on MacOS only, but this is definitly not caused by my changes. What could I do?

**Comment by calebmshafer** [comment]
@MarcBedard8 it's a flaky test that has been causing problems for over a week. I'm digging into it today, hopefully I'll have a fix soon.

For now, I can just override that check and merge the PR if that works with you.

**Comment by MarcBedard8** [comment]
Appreciated Thanks.

**Pull request merged**
