### PR TITLE
Initial support for glTF

### PR DESCRIPTION
**Pull request by pmconne**
glTF is the standard web transmission format for 3d graphics. As discussed in #2696, an API should be provided that accepts a glTF model and produces a RenderGraphic suitable for use in decorations.
@itwin/core-frontend contains a `GltfReader` class used internally to deserialize tile graphics but provides no public API for it. The reader was implemented specifically for the kinds of glTF we encounter in our tiles (whether iModel, terrain, or reality data) - not as a general-purpose glTF reader.
Initial attempt to import the camera model supplied by Evercam revealed significant deficiencies in our implementation:
image

Inspection of the code revealed many deviations and omissions from the glTF specs. The code was quite difficult to read because it is entirely untyped.
Ultimately we intend to provide a complete implementation of the [glTF 2.0 spec](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html) (with the exception of currently unsupported features like skinning and PBR materials).
This PR constrains itself to the first step toward that goal: provide a `readGltfGraphics` API that correctly loads the Evercam model.
Subsequent PR(s) will flesh out the implementation and test it against the wide variety of [sample models](https://github.com/KhronosGroup/glTF-Sample-Models) supplied by Khronos. Many of those sample models already load and display correctly. Some exhibit missing normals or textures; some fail to load at all.

To make it easier to implement and document the spec (and to understand the implementation), this PR also defines TypeScript interfaces for the glTF data types according to the glTF schema and updates GltfReader to use them.
This required removing the inheritance relationship between ImdlReader and GltfReader, which never made much sense anyway - they shared almost no code.

For testing purposes, display-test-app's `dta gltf` keyin will allow the user to select a glTF model from the file system to be displayed as a decoration at the center of the project extents.
The Evercam model in display-test-app:
image

### CODE REVIEW

**Comment by mgooding** [comment]
Are you looking for review focused on ImdlReader here, since GltfReader will be ironed out in a subsequent PR?

**Comment by pmconne** [comment]
> Are you looking for review focused on ImdlReader here, since GltfReader will be ironed out in a subsequent PR?

Feedback on all of the changes is welcome.

**Comment by pmconne** [comment]
This would be easier to review (and easier to use as documentation) if it was properly documented. I'll add that.

**Comment by pmconne** [comment]
Awaiting ImageTests results to confirm no regressions in reality models due to GltfReader changes.

**Review by markschlosseratbentley — APPROVED** [review]

**Comment by markschlosseratbentley** [comment]
I successfully built + ran this branch.  I used the keyin to open a sample from Khronos - Box.glb - and it rendered.
If a sample fails to parse (I know this is expected for some), we get "Keyin failed to run", right?

**Pull request merged**
