### PR TITLE
Clamp batched tile fit volume to project extents.

### PR DESCRIPTION
**Pull request by pmconne**
The iModel's project extents are supposed to clamp the range of viewable geometry. The tileset publisher enforces this. However, at display time we compute the volume of the displayed viewable models by taking the union of the bounding boxes of each model, which may extend (sometimes very far!) outside of the project extents. This can arbitrarily expand the viewed volume so that when you fit the view, it zooms way out; and can negatively affect depth buffer precision, producing visual artifacts.

Add project extents clamping when computing viewed extents in BatchedModels.

Needs to be backported to 4.4.x ASAP. Running ImageTests first.

### CODE REVIEW

**Review by danieliborra — APPROVED** [review]

**Comment by pmconne** [comment]
@Mergifyio backport release/4.4.x

**Comment by pmconne** [comment]
ImageTests unsurprisingly showed a handful of minor z-fighting differences.
Two geolocated views show differences in map imagery
- 04_Plant M05 - map is much blurrier
- ClubHouse M05 - map imagery looks different
Rerunning just those tests now against master to determine if it has anything to do with this PR, or if Microsoft updated their imagery.

**Review by DStradley — APPROVED** [review]

**Comment by DStradley** [comment]
Healthcare X6 was a definite improvement.

**Review by MarcNeely — APPROVED** [review]
This unfortunately does not fix the other model that David and I noticed which just has a really huge project extents (422 miles), but does fix the problem this PR was addressing.

**Comment by pmconne** [comment]
Map differences did not recur on master nor on this PR branch.

**Pull request merged**
