### PR TITLE
Add an iterator over the entries of BatchTableProperties

### PR DESCRIPTION
**Pull request by pmconne**
For @MarcBedard8.

### CODE REVIEW

**Review by aruniverse — APPROVED** [review]

**Comment by aruniverse** [comment]
does this need to be backported?

**Comment by pmconne** [comment]
> does this need to be backported?

It's a question for @MarcBedard8.

**Comment by MarcBedard8** [comment]
I'll need this to be backported as Inspection team is waiting for that.

**Comment by pmconne** [comment]
@Mergifyio backport release/4.4.x

**Comment by hl662** [comment]
> I'll need this to be backported as Inspection team is waiting for that.

@MarcBedard8 Is there an ideal timeline you'd want this in a new patch release? I can kick off the patch release this afternoon, since there aren't any other PRs that we are waiting for immediate reviews + backport

**Comment by MarcBedard8** [comment]
Sooner the better :), So yes please, you can kick the patch release.

**Comment by hl662** [comment]
> Sooner the better :), So yes please, you can kick the patch release.

4.4.5 patch has been released onto npm

**Pull request merged**
