### PR TITLE
Accudraw and simulate motion

### PR DESCRIPTION
**Pull request by bbastings**
Fix issue with simulating a motion event not using the current unadjusted cursor location.
Change release tags for AccuDraw methods to enable/disable for session.
Added new AccuDrawHintBuilder method to force processing of hints.

Change for Internal api usage

### CODE REVIEW

**Review by pmconne — APPROVED** [review]

**Comment by aruniverse** [comment]
@mergifyio backport release/4.11.x

**Comment by bbastings** [comment]
@tcobbs-bentley Any idea on the iOS test failures?

**Comment by tcobbs-bentley** [comment]
> @tcobbs-bentley Any idea on the iOS test failures?

I'm not sure; investigating.

**Comment by tcobbs-bentley** [comment]
@bbastings @aruniverse Now that the latest published addon uses mobile Node 22, I'm able to reproduce these test failures locally, which strongly implies that there is something wrong with the Node 22 addon. I expect that fixing this will take me quite some time, so I recommend submitting a separate PR to disable the iOS Simulator backend unit tests yaml step. I can do that, or someone else can.

**Comment by aruniverse** [comment]
> @bbastings @aruniverse Now that the latest published addon uses mobile Node 22, I'm able to reproduce these test failures locally, which strongly implies that there is something wrong with the Node 22 addon. I expect that fixing this will take me quite some time, so I recommend submitting a separate PR to disable the iOS Simulator backend unit tests yaml step. I can do that, or someone else can.

Please do it.

**Comment by tcobbs-bentley** [comment]
@bbastings The PR to disable the iOS Simulator core backend tests merged, so I updated this PR from master, which should fix the problem.

**Pull request merged**
