### PR TITLE
use new changed ids extraction api

### PR DESCRIPTION
**Pull request by MichaelBelousov**
[this native PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/247174) changes the `extractChangedInstanceIdsFromChangeSet` to operate over multiple changesets and directly return javascript objects instead of a json string.

also adds a test to ensure that `processChanges` over a ModelSelector element does not lose changes even though the actual `ModelSelectorRefersToModels` relationship is not checked by the native implementation of `extractChangedInstanceIdsFromChangeset`

### CODE REVIEW

**Comment by pmconne** [comment]
Your native PR link goes to a performance testing wiki page.

**Comment by MichaelBelousov** [comment]
> Your native PR link goes to a performance testing wiki page.

Whoops thanks for pointing that out. Will fix. Keep in mind both PRs are still drafts while i add some tests

**Comment by MichaelBelousov** [comment]
> Your native PR link goes to a performance testing wiki page.

Whoops thanks for pointing that out. Will fix. Keep in mind both PRs are still drafts while i add some tests

**Comment by pmconne** [comment]
I was asking about the native PR because I wanted to know if it addresses that assertion during transformer tests.

**Comment by MichaelBelousov** [comment]
> I was asking about the native PR because I wanted to know if it addresses that assertion during transformer tests.

It does.

**Comment by MichaelBelousov** [comment]
link fixed

**Review by ColinKerr — APPROVED** [review]

**Comment by MichaelBelousov** [comment]
going to wait for a review from @iTwin/itwinjs-core-admins before merging

**Review by pmconne — APPROVED** [review]

**Comment by MichaelBelousov** [comment]
now just waiting for the native PR to be merged and approved

**Pull request merged**
