### PR TITLE
Fix loading map errors

### PR DESCRIPTION
**Pull request by calebmshafer**
WIP fix to loading maps from the variety of different source urls

### CODE REVIEW

**Comment by calebmshafer** [comment]
> Locally-hosted tilesets. URLs like this produce CORS errors: http://localhost:8080/PhiladelphiaHiResRealityModel/76/TileRoot.json

@pmconne I tried that out with the command you gave me `http-server d:\3dtiles --cors=X-Correlation-ID` and wasn't seeing any issues loading them. Maybe I'm testing it incorrectly?

**Comment by aruniverse** [comment]
@pmconne @calebmshafer I added back the react-scripts build back to dta build command (hopefully temporarily) in order to copy the static assets over and to unblock this pr. I'm continuing to investigate the issue here with the CopyBentleyStaticResourcesPlugin not working anymore in dev (react-scripts start). I timed how much longer running the webpack build adds to building dta using [gnomon](https://www.npmjs.com/package/gnomon), only add 10-15s (time spent copying the static assets as there is no react or anything else to compile). 

@bsteinbk @NancyMcCallB @GerardasB i didnt make this change in uita because webpacking the frontend there adds a min, and im hoping to figure out the issue with the copy static assets plugin soon (in a separate pr). But until then if you guys run into issues with no key-ins/localization strings i recommend running the build:ci command first.

**Comment by mdastous-bentley** [comment]
@calebmshafer Is it still too early to test various map-layers requests?

**Comment by pmconne** [comment]
@mdastous-bentley I think you should reasonably expect map layers requests to work on this branch. Please let us know what you find.

**Pull request merged**
