### PR TITLE
Add test to verify system properties are rendered correctly with ECDb Profile 4003

### PR DESCRIPTION
**Pull request by khanaffan**
Has native PR 
https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/320082

### CODE REVIEW

**Review by ColinKerr — APPROVED** [review]

**Review by aruniverse — APPROVED** [review]
Hope Vincas is aware of the 2.x EOL at the end of this month

**Comment by khanaffan** [comment]
> 

Rush changes show changes to packages that I have not changed. 

```
Found change file: \itwinjs-core\common\changes\@itwin\core-backend\itwin-reprojection_2021-10-07-16-39.json
Found change file: \itwinjs-core\common\changes\@itwin\core-common\itwin-reprojection_2021-10-07-16-39.json
Found change file: \itwinjs-core\common\changes\@itwin\core-frontend\itwin-reprojection_2021-10-07-16-39.json
Found change file: \itwinjs-core\common\changes\@itwin\core-geometry\EDL-ClosestPointOnCurveChainWithDistanceIndex_2021-10-15-18-39.json
Found change file: \itwinjs-core\common\changes\@itwin\editor-backend\itwin-reprojection_2021-10-07-16-39.json
Found change file: \itwinjs-core\common\changes\@itwin\editor-common\itwin-reprojection_2021-10-07-16-39.json
Found change file: \itwinjs-core\common\changes\@itwin\editor-frontend\itwin-reprojection_2021-10-07-16-39.json
```

**Comment by aruniverse** [comment]
> > 
> 
> Rush changes show changes to packages that I have not changed.
> 
> ```
> Found change file: \itwinjs-core\common\changes\@itwin\core-backend\itwin-reprojection_2021-10-07-16-39.json
> Found change file: \itwinjs-core\common\changes\@itwin\core-common\itwin-reprojection_2021-10-07-16-39.json
> Found change file: \itwinjs-core\common\changes\@itwin\core-frontend\itwin-reprojection_2021-10-07-16-39.json
> Found change file: \itwinjs-core\common\changes\@itwin\core-geometry\EDL-ClosestPointOnCurveChainWithDistanceIndex_2021-10-15-18-39.json
> Found change file: \itwinjs-core\common\changes\@itwin\editor-backend\itwin-reprojection_2021-10-07-16-39.json
> Found change file: \itwinjs-core\common\changes\@itwin\editor-common\itwin-reprojection_2021-10-07-16-39.json
> Found change file: \itwinjs-core\common\changes\@itwin\editor-frontend\itwin-reprojection_2021-10-07-16-39.json
> ```

do the following:
```
git reset --hard HEAD~1
git fetch -all
rush change -b origin/release/2.19.x
stage and commit your changes
git push -f
```

**Review by ColinKerr — APPROVED** [review]

**Pull request merged**
