### PR TITLE
Fix tile display issues with ArcGIS map  layers

### PR DESCRIPTION
**Pull request by mdastous-bentley**
- Fix tile display issues for layer tiles not covering the entire tile tree and TileMap service is not available.  
- Derive minimum LOD from the minimum scale. 
- Use 'fullExtent' metadata to get cartoRange of layer when getFootPrints request doesn't include data extent.
- For some reasons, ArcGIS Online  returns the content type 'image/png;charset=UTF-8' instead of 'image/png' for some tiles... tile data is perfectly valid png, but we were ignoring it.

### CODE REVIEW

**Comment by pmconne** [comment]
Run ImageTests. Email @DStradley if you don't know how to do that.

**Review by MarcBedard8 — APPROVED** [review]

**Comment by pmconne** [comment]
Make sure ImageTests is run against your latest changes please. ("Make sure all tiles from level 1 are range checked too").

**Comment by mdastous-bentley** [comment]
@pmconne I requested a new test run right after my commit.

**Comment by skirby1996** [comment]
@mergifyio backport release/3.2.x

**Comment by mdastous-bentley** [comment]
@pmconne Could not find any major issue in image test.

**Review by pmconne — APPROVED** [review]

**Pull request merged**
