### PR TITLE
update to webpack@^5.76.0 to resolve GHSA-hc6q-2mpp-qw7j

### PR DESCRIPTION
**Pull request by aruniverse**
https://github.com/advisories/GHSA-hc6q-2mpp-qw7j

### CODE REVIEW

**Review by pmconne — APPROVED** [review]

**Review by ben-polinsky — APPROVED** [review]

**Review by raplemie — APPROVED** [review]
LGTM, thanks!

**Comment by aruniverse** [comment]
@mergifyio backport release/3.7.x

**Comment by grigasp** [comment]
@raplemie @aruniverse it looks like similar change is needed in `appui`
https://github.com/iTwin/appui/pull/207
image

**Comment by aruniverse** [comment]
@mergifyio backport release/3.6.x

**Pull request merged**
