### PR TITLE
Map-layers oauth2 requests optimization and improvements 

### PR DESCRIPTION
**Pull request by mdastous-bentley**
Various improvements:

- No longer assumes all layers of a given portal (i.e www.arcgis.com) require an oauth2 token, even though such layer has already been attached to the viewport.
- Avoid making any Oauth2 discovery requests preemptively; wait until an token error is returned by the server.
- Some servers would return error message in html formats when performing tile request, fallback to service metadadata json request when it happens.
- `ArcGisTokenManager.invalidateOAuth2Token` would not update the proper cache object.

### CODE REVIEW

**Comment by mdastous-bentley** [comment]
@pmconne please review.

**Review by pmconne — COMMENTED** [review]
Were tests removed because they are no longer relevant, or some other reason?

**Comment by mdastous-bentley** [comment]
> Were tests removed because they are no longer relevant, or some other reason?

yes, some were no longer relevant and I found tests that were just duplicate.

**Comment by mdastous-bentley** [comment]
@pmconne is it good to go?

**Review by pmconne — APPROVED** [review]

**Review by aruniverse — APPROVED** [review]

**Pull request merged**
