### PR TITLE
Handle KrovakEN well-known text (fixes #3027)

### LINKED ISSUE #3027: Loading Orbit PointCloud with projection KrovakEN causes crash
Projection name "KrovakEN" is not handled.
https://github.com/iTwin/itwinjs-core/blob/b1e6c76ad3fff65a354a758680d0b2d12a2ec194/core/orbitgt/src/spatial/ecrs/WellKnownText.ts#L279

It is however handled here:
https://github.com/iTwin/itwinjs-core/blob/b1e6c76ad3fff65a354a758680d0b2d12a2ec194/core/orbitgt/src/spatial/ecrs/WellKnownText.ts#L336

but gives nullpointer because parameterList is always empty.

Example projection:
https://epsg.io/8353

WKT:
`PROJCS[
	"S-JTSK [JTSK03] / Krovak East North",
	GEOGCS[
		"S-JTSK [JTSK03]",
		DATUM["System of the Unified Trigonometrical Cadastral Network [JTSK03]",
			SPHEROID["Bessel 1841",6377397.155,299.1528128,AUTHORITY["EPSG","7004"]],
			AUTHORITY["EPSG","1201"]
		],
		PRIMEM["Greenwich",0.0,AUTHORITY["EPSG","8901"]],
		UNIT["Degree",0.017453292519943278,AUTHORITY["EPSG","9102"]],
		AUTHORITY["EPSG","8351"]
	],
	PROJECTION["KrovakEN"],
	PARAMETER["latitude_of_center",49.5],
	PARAMETER["longitude_of_center",24.833333333333332],
	PARAMETER["azimuth",30.288139752777788],
	PARAMETER["pseudo_standard_parallel_1",78.5],
	PARAMETER["scale_factor",0.9999],
	PARAMETER["false_easting",0.0],
	PARAMETER["false_northing",0.0],
	UNIT["Metre",1.0,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","8353"]
]`

### PR DESCRIPTION
**Pull request by stuartpb**

### CODE REVIEW

**Comment by calebmshafer** [comment]
@stuartpb thanks for the PR! Can you run `rush change` and add a small description of the change for the changelogs?

**Comment by lerzeel2** [comment]
Looks like a perfect fix for the reported problem.

**Review by AlainRobertAtBentley — APPROVED** [review]
@lerzeel2 has approved as effective code owner.

**Comment by AlainRobertAtBentley** [comment]
@calebmshafer @pmconne Can we move this PR forward. I approved on behalf of Lander but my approval does not carry much weight. Is there anything missing?

**Comment by calebmshafer** [comment]
> @calebmshafer @pmconne Can we move this PR forward. I approved on behalf of Lander but my approval does not carry much weight. Is there anything missing?

@AlainRobertAtBentley just kicked off a round of builds to verify. As long as those go well, we'll just need @pmconne (or someone else on Display team) to take a look and approve the change.

**Review by pmconne — APPROVED** [review]

**Comment by pmconne** [comment]
> @pmconne (or someone else on Display team)

@calebmshafer IMO we need to assign a real owner (such as @lerzeel2) to the orbitgt package - the display team isn't the right owner.

**Comment by pmconne** [comment]
@Mergifyio update

**Comment by pmconne** [comment]
>  just kicked off a round of builds to verify.

@calebmshafer the iTwin.js builds did not trigger. They still have not triggered after I updated the branch.

**Comment by calebmshafer** [comment]
> > just kicked off a round of builds to verify.
> 
> @calebmshafer the iTwin.js builds did not trigger. They still have not triggered after I updated the branch. Nor after making a trivial edit.

@pmconne it is a fork-based PR so it's not going to trigger automatically. I queued on manually last night and it passed. I'll do it one more time to make sure.

On the owner of orbit-gt package, that makes sense to me as long as @lerzeel2 agrees let's open a PR.

**Comment by pmconne** [comment]
> it is a fork-based PR so it's not going to trigger automatically. I queued on manually last night and it passed. I'll do it one more time to make sure.

How does someone other than you do that?

> On the owner of orbit-gt package, that makes sense to me as long as @lerzeel2 agrees let's open a PR.

I think he needs to join the org.

**Comment by calebmshafer** [comment]
> > it is a fork-based PR so it's not going to trigger automatically. I queued on manually last night and it passed. I'll do it one more time to make sure.
> 
> How does someone other than you do that?

@pmconne it's a pain in the butt right now to do it. I'll share the steps. We need to have a better way going forward.

> I think he needs to join the org.

He should not be a part of the Org and can be added as a reviewer.

**Pull request merged**
