### PR TITLE
Listen for events emitted when replaying external txns

### PR DESCRIPTION
**Pull request by pmconne**
Fixes https://github.com/iTwin/itwinjs-backlog/issues/845.
ModelChangeMonitor needs to know when we have finished applying a set of changes to a read-only briefcase originating from another connection to the same briefcase.
It won't get a reliable series of events if the writable connection performs an undo or redo, but we don't care, because the intended use case only involves a non-interactive second process appending new txns.
[Corresponding native PR](https://github.com/iTwin/imodel-native/pull/417).
imodel-native: https://github.com/iTwin/imodel-native/tree/pmc/external-txn-events
imodel-native-internal: https://github.com/iTwin/imodel-native-internal/tree/pmc/external-txn-events

### CODE REVIEW

**Comment by pmconne** [comment]
The first undo in the read-only iModel test produces no events. Subsequent undo/redos produce surprising series of events.
Actual events produced:
```
0 ["onCommit","onElementsChanged","onCommitted"]
1 ["onCommit","onElementsChanged","onModelsChanged","onCommitted"]
2 ["onCommit","onModelGeometryChanged","onElementsChanged","onCommitted"]
3 ["onCommit","onModelGeometryChanged","onElementsChanged","onCommitted"]
4 ["onCommit","onModelGeometryChanged","onElementsChanged","onCommitted"]
5 ["beforeUndo","onElementsChanged","onModelGeometryChanged","afterUndo"]
6 ["beforeUndo","onElementsChanged","onModelGeometryChanged","afterUndo"]
7 ["beforeUndo","onElementsChanged","onModelGeometryChanged","afterUndo"]
8 ["beforeUndo","onElementsChanged","onModelsChanged","afterUndo"]
9 ["beforeUndo","onElementsChanged","afterUndo"]
A ["beforeRedo","onElementsChanged","afterRedo"]
B ["beforeRedo","onElementsChanged","onModelsChanged","afterRedo"]
C ["beforeRedo","onElementsChanged","onModelGeometryChanged","afterRedo"]
D ["beforeRedo","onElementsChanged","onModelGeometryChanged","afterRedo"]
E ["beforeRedo","onElementsChanged","onModelGeometryChanged","afterRedo"]
F ["beforeUndo","onElementsChanged","onModelGeometryChanged","onElementsChanged","onModelGeometryChanged","onElementsChanged","onModelGeometryChanged","onElementsChanged","onModelsChanged","onElementsChanged","afterUndo"]
G ["beforeRedo","onElementsChanged","onElementsChanged","onModelsChanged","onElementsChanged","onModelGeometryChanged","onElementsChanged","onModelGeometryChanged","onElementsChanged","onModelGeometryChanged","afterRedo"]
    ? receives events for writable connection (242ms)

0 ["onReplayExternalTxns","onElementsChanged","onReplayedExternalTxns"]
1 ["onReplayExternalTxns","onElementsChanged","onModelsChanged","onReplayedExternalTxns"]
2 ["onReplayExternalTxns","onElementsChanged","onModelGeometryChanged","onReplayedExternalTxns"]
3 ["onReplayExternalTxns","onElementsChanged","onModelGeometryChanged","onReplayedExternalTxns"]
4 ["onReplayExternalTxns","onElementsChanged","onModelGeometryChanged","onReplayedExternalTxns"]
5 []
6 ["onReplayExternalTxns","onElementsChanged","onModelGeometryChanged","onReplayedExternalTxns"]
7 ["onReplayExternalTxns","onModelGeometryChanged","onElementsChanged","onModelGeometryChanged","onReplayedExternalTxns"]
8 ["onReplayExternalTxns","onElementsChanged","onElementsChanged","onReplayedExternalTxns"]
9 ["onReplayExternalTxns","onElementsChanged","onModelsChanged","onElementsChanged","onElementsChanged","onReplayedExternalTxns"]
A ["onReplayExternalTxns","onElementsChanged","onElementsChanged","onModelsChanged","onElementsChanged","onElementsChanged","onReplayedExternalTxns"]
B ["onReplayExternalTxns","onElementsChanged","onModelsChanged","onElementsChanged","onModelGeometryChanged","onModelGeometryChanged","onElementsChanged","onModelGeometryChanged","onReplayedExternalTxns"]
C ["onReplayExternalTxns","onElementsChanged","onModelGeometryChanged","onElementsChanged","onModelGeometryChanged","onElementsChanged","onModelGeometryChanged","onReplayedExternalTxns"]
D ["onReplayExternalTxns","onElementsChanged","onModelGeometryChanged","onElementsChanged","onModelGeometryChanged","onReplayedExternalTxns"]
E ["onReplayExternalTxns","onElementsChanged","onModelGeometryChanged","onReplayedExternalTxns"]
F []
G ["onReplayExternalTxns","onElementsChanged","onElementsChanged","onModelsChanged","onElementsChanged","onModelGeometryChanged","onModelGeometryChanged","onElementsChanged","onModelGeometryChanged","onReplayedExternalTxns"]
    ? receives events for read-only connection when watchForChanges is enabled (4324ms)
```

**Comment by pmconne** [comment]
I don't understand why `rush change` wants a changelog for every single package.

**Comment by pmconne** [comment]
@DanRod1999 is the build pipeline going to run `rush change -v -b origin/imodel02` or just `rush change -v`?

**Comment by DanRod1999** [comment]
> which should take care of this. If it fails lmk

Looks like it fails, so i'm looking into it

**Comment by nick4598** [comment]
@pmconne Could you explain to me how this fixes the issue reported? My understanding is that purgeTileTrees wasn't being called in a case where it should be and now it is with your PR. Since you have a new event that you're listening to(which calls purgeTileTrees) which is raised by native code after replayExternalTxns takes place. I think that part makes sense to me. What I don't understand is the [Additional context](https://github.com/iTwin/itwinjs-backlog/issues/845) section. How come the steps they tried didn't get tiles to change?

I would expect atleast step 1 to work "Manually raising invoking IpcHost.notifyTxns(briefcase, "notifyCommitted", true, Date.now()) when the associated .bim-wal file changes (similarly to how core invokes nativeDb.restartDefaultTxn() on the same event)"

This appears to raise the onCommitted event which calls 'maybeProcess' and would purge tile trees? 

I guess step 2 doesn't work because it doesn't have the modelIds. (And I guess step 3 similarly doesn't affect tile trees at all).

**Comment by pmconne** [comment]
> @pmconne is my understanding correct about how this fixes the issue the user reported?

I think what you're really asking is "where is the test that proves this causes the viewport to update to reflect changes made by the other connection".
It's a really annoying test to write. I'm working on it.

**Comment by nick4598** [comment]
> I would expect atleast step 1 to work "Manually raising invoking IpcHost.notifyTxns(briefcase, "notifyCommitted", true, Date.now())

So, I'm guessing the test passes based off of your most recent commit. Do you know why step 1 wasn't enough for that user if they both end up calling maybeProcess?

**Comment by pmconne** [comment]
> So, I'm guessing the test passes based off of your most recent commit. 

Yes, but I'm still fleshing out the test to verify that new tiles are produced that accurately reflect the updated geometry.

> Do you know why step 1 wasn't enough for that user if they both end up calling maybeProcess?

[Here's why](https://github.com/iTwin/imodel-native/pull/417/commits/f6cbb6e2cafecb6668ea87c75311a7f92f276ed8)

**Pull request merged**
