### PR TITLE
Enable schedule scripts from editing scope

### PR DESCRIPTION
**Pull request by mathieu-lemuzic**
Enable schedule script for elements in edit scope.

### CODE REVIEW

**Comment by pmconne** [comment]
Fixes https://github.com/iTwin/itwin-graphics-backlog/issues/319

**Comment by mathieu-lemuzic** [comment]
@pmconne I pushed a full stack test to ensure that edited objects are updated by scheduled scripts, I am not 100% sure about the approach, I would have prefered looking a pixel colors instead, but I could not managed to get anything to display :/

**Comment by pmconne** [comment]
Is anything further needed before this is ready for review?

**Comment by mathieu-lemuzic** [comment]
> Is anything further needed before this is ready for review?

I don't think so

**Review by pmconne — APPROVED** [review]

**Pull request merged**
