### PR TITLE
Make cloudsqlite prefetch opt-in through settings instead of opt-out

### PR DESCRIPTION
**Pull request by nick4598**

### CODE REVIEW

**Comment by kabentley** [comment]
Why?

**Comment by nick4598** [comment]
> Why?

I felt like it was slightly cumbersome to turn off, and I'm worried that some people might not know how. I ran into this when playing around with Grigas's presentation tests. I had to figure out where the assets dir was for his local backend which isn't that hard, but still. Combine that with the fact that we're still looking at those crashes with cloudsqlite, and I didn't want to complicate things any more with prefetch.

It also will help in the case that people DO end up turning off prefetching. If we set it to off by default now, we can turn on prefetching for them when they update to a newer version (by switching the default back) versus reaching out to those who have turned it off and asking them to change their settings file.

**Comment by kabentley** [comment]
I'm hoping that prefetching will improve performance substantially for web backends and that no one will ever turn it off in that environment. What is the point of turning it off in Grigas's tests if we're going to turn it on in our backends? If this is merely temporary to help diagnose the crashes, then fine.

**Comment by wgoehrig** [comment]
> But "opt in" will make it so it almost never gets turned on.

I think the goal here is just to _temporarily_ make this opt-in until either we fix the crashes and the latest CloudSQLite changes are released and consumed in 3.3.  In other words, the plan will be to revert this change and enable prefetch by default starting in 3.4.   I just want to reduce what we're committing to have totally stable and production-ready in 3.3 so we reduce the risk of delaying 3.3 any further.

I'd also _like_ to do a bit more perf testing and have confidence that prefetching is **in practice** significantly improving startup performance.  As we discussed two weeks ago, there is some evidence that the current prefetch implementation is not aggressive enough about utilizing extra bandwidth and as a result may not have enough impact on our initial queries.  But it's not clear fixing that needs to be a prerequisite for re-enabling by default in 3.4 - as long as we have confidence it isn't _harming_ our performance I think we can plan on moving forward with this again after 3.3...

**Comment by kabentley** [comment]
If this is only temporary, then I have no objections.

**Review by kabentley — APPROVED** [review]

**Review by wgoehrig — APPROVED** [review]

**Pull request merged**
