### PR TITLE
Restore Integration test for RealityDataAccess 

### PR DESCRIPTION
**Pull request by MarcBedard8**
"should get RealityDataSource for Open Street Map Building (OSM)"
See also this PR: https://github.com/iTwin/itwinjs-core/pull/2952

### CODE REVIEW

**Comment by MarcBedard8** [comment]
@skirby1996, please let me know when .env is updated with MJS_CESIUM_ION_KEY on integration test pipeline so I merge this PR.

**Comment by skirby1996** [comment]
> @skirby1996, please let me know when .env is updated with MJS_CESIUM_ION_KEY on integration test pipeline so I merge this PR.

The variable group was updated so you should be able to move forward with this.

**Comment by pmconne** [comment]
@Mergifyio update

**Comment by pmconne** [comment]
@MarcBedard8 test still failing.

**Comment by MarcBedard8** [comment]
> @MarcBedard8 test still failing.

Wiil look at it when I get a chance

**Comment by skirby1996** [comment]
@mergifyio update

**Review by calebmshafer — APPROVED** [review]

**Pull request merged**
