### PR TITLE
Update oidc-signin-tool to 4.3.7

### PR DESCRIPTION
**Pull request by MichaelSwigerAtBentley**
Update oidc signin tool to latest to fix hanging tests

### CODE REVIEW

**Review by hl662 — APPROVED** [review]

**Review by aruniverse — APPROVED** [review]

**Comment by aruniverse** [comment]
@mergifyio backport release/4.9.x

**Comment by aruniverse** [comment]
@tcobbs-bentley mind taking a look at the ios failures here?

**Review by anmolshres98 — APPROVED** [review]

**Comment by MichaelSwigerAtBentley** [comment]
@tcobbs-bentley I have disabled the iOS backend unit tests in Simulator job. When fixing, remember to remove the 'false' flag to reenable when fixing

**Pull request merged**
