### PR TITLE
Enable docs processing from published tools package

### PR DESCRIPTION
**Pull request by ben-polinsky**
Previously, the docs extraction functionality in @itwin/build-tools used a hard-coded relative path to the monorepo root. This PR adds a check for a env variable `RUSHSTACK_FILE_ERROR_BASE_FOLDER` first, which enables the package to be consumed by other repos.

### CODE REVIEW

**Review by raplemie — APPROVED** [review]
LGTM, tried the change in the appui repo and I seem to have proper results!

**Review by calebmshafer — APPROVED** [review]
LGTM

**Comment by ben-polinsky** [comment]
> LGTM

Seems to be an issue with tests at the moment. How did this PR get through https://github.com/iTwin/itwinjs-core/pull/4338/checks?check_run_id=8517433180 if the checks failed?

**Comment by aruniverse** [comment]
> > LGTM
> 
> Seems to be an issue with tests at the moment. How did this PR get through [#4338 (checks)](https://github.com/iTwin/itwinjs-core/pull/4338/checks?check_run_id=8517433180) if the checks failed?

Admins are able to force merge, bypassing review checks

**Pull request merged**
