### PR TITLE
rm cjs import in core-frontend for object-storage dynamic import

### PR DESCRIPTION
**Pull request by aruniverse**

### CODE REVIEW

**Comment by aruniverse** [comment]
@kckst8 could you guys test this out in studio via pnpm patch?

itwinjs-core/core/frontend/lib/{cjs/esm}/tile/TileAdmin.js
```ts
        this._tileStoragePromise = (async () => {
            await import("reflect-metadata");
            // eslint-disable-next-line @typescript-eslint/naming-convention
            const { AzureFrontendStorage, FrontendBlockBlobClientWrapperFactory } = await import("@itwin/object-storage-azure/lib/frontend");
            const azureStorage = new AzureFrontendStorage(new FrontendBlockBlobClientWrapperFactory());
            this._tileStorage = new TileStorage(azureStorage);
            return this._tileStorage;
        })();
```

**Comment by aruniverse** [comment]
@GytisCepk mind taking a look at the failing integration test, "should cancel pulling changes after abort signal", in core-full-stack? Failed back to back like 3 times; and i can't imagine my changes here actually breaking it

**Comment by paulius-valiunas** [comment]
if you build this usinc CJS it won't be a dynamic import anynore. The whole point was to avoid bundling @azure/storage-blob into the main bundle.

**Comment by aruniverse** [comment]
> No one should be bundling the CJS modules 

Bill beat me to saying it, but he's right. im not aware of anyone consuming our frontend deps as cjs modules. The issue we were seeing earlier was in the core repo we only build cjs by default, so unfortunately we were pulling in the azure blob storage pkg into the bundle, but this is a testing edge case like Bill mentioned earlier.

If you're for some reason consuming the cjs modules in the frontend thats on you imo

**Comment by paulius-valiunas** [comment]
alright fair enough, but I think you should keep the `webpackChunkName`

**Review by kckst8 — APPROVED** [review]
resolves this issue in Studio

**Comment by pmconne** [comment]
Any tests that prove blob storage tile cache still works?

**Comment by aruniverse** [comment]
> Any tests that prove blob storage tile cache still works?

no tests that im aware of atm. @paulius-valiunas is that right? we should make a backlog item to create a test for this if not.

paul, i did test locally with dta using hub models, as well as throw the patch into my tets apps node modules, and everything seemed fine

**Comment by pmconne** [comment]
> no tests that im aware of atm. @paulius-valiunas is that right? we should make a backlog item to create a test for this if not.

There was an action item from the 3.4 retro, but I can find no issue filed.

> i did test locally with dta

DTA does not use the cloud storage tile cache.

**Review by pmconne — APPROVED** [review]

**Comment by aruniverse** [comment]
@mergifyio backport release/3.4.x

**Pull request merged**
