### PR TITLE
@bentley/imodeljs-native 3.4.7

### PR DESCRIPTION
**Pull request by pmconne**

### CODE REVIEW

**Comment by pmconne** [comment]
@NancyMcCallB appui-connected-app and presentation-test-app are failing to build because
`##[error]Module not found: Error: Can't resolve '@storybook/theming' in '/agent/_work/1/s/common/temp/node_modules/.pnpm/@itwin+itwinui-react@1.43.0_react-dom@17.0.2+react@17.0.2/node_modules/@itwin/itwinui-react/esm/core/Dialog'`

Both before and after running `rush update`, no package.json in common/temp/node_modules nor our own packages referred to @storybook/theming.
Please suggest a solution.

**Comment by aruniverse** [comment]
> @NancyMcCallB appui-connected-app and presentation-test-app are failing to build because `##[error]Module not found: Error: Can't resolve '@storybook/theming' in '/agent/_work/1/s/common/temp/node_modules/.pnpm/@itwin+itwinui-react@1.43.0_react-dom@17.0.2+react@17.0.2/node_modules/@itwin/itwinui-react/esm/core/Dialog'`
> 
> Both before and after running `rush update`, no package.json in common/temp/node_modules nor our own packages referred to @storybook/theming. Please suggest a solution.

@iTwin/itwinui why is storybook getting pulled in here??

**Comment by aruniverse** [comment]
@pmconne for the time being you should be able to hopefully pin `@itwin/itwinui-react` to `~1.42.0` to get around the issue

**Review by aruniverse — APPROVED** [review]

**Comment by bentleyvk** [comment]
> > @NancyMcCallB appui-connected-app and presentation-test-app are failing to build because `##[error]Module not found: Error: Can't resolve '@storybook/theming' in '/agent/_work/1/s/common/temp/node_modules/.pnpm/@itwin+itwinui-react@1.43.0_react-dom@17.0.2+react@17.0.2/node_modules/@itwin/itwinui-react/esm/core/Dialog'`
> > Both before and after running `rush update`, no package.json in common/temp/node_modules nor our own packages referred to @storybook/theming. Please suggest a solution.
> 
> @iTwin/itwinui why is storybook getting pulled in here??

@aruniverse @pmconne This was a mistake on our side by having wrong import path inside one of our components. Now it is fixed https://github.com/iTwin/iTwinUI-react/releases/tag/v1.43.1

**Pull request merged**
