### PR TITLE
Double tap fix

### PR DESCRIPTION
**Pull request by tcobbs-bentley**
Fix for: https://github.com/iTwin/itwinjs-core/issues/6976
The double tap code had an `await` call when waiting for the double tap timeout. Unfortunately, that meant that it was impossible for the second tap to be registered until the first tap's timeout had already expired, thus preventing double taps from ever being registered. Changing `await` to `void` fixed the problem.

### CODE REVIEW

**Review by aruniverse — APPROVED** [review]
@mergifyio backport release/4.7.x

**Comment by tcobbs-bentley** [comment]
After merging from main, `rush cover` failed in Windows. I have no idea why. I reran the pipeline and everything succeeded, but GitHub didn't notice:

https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=3035630&view=results

**Comment by pmconne** [comment]
> After merging from main, rush cover failed in Windows. I have no idea why. I reran the pipeline and everything succeeded, but GitHub didn't notice:

Flaky test. Did you use the "Rerun Failed Jobs" button? That would usually show up as "Attempt #2", which I don't see in your linked build. So I clicked it in your failing build and GH is now waiting for the Windows job to succeed.

**Review by markschlosseratbentley — APPROVED** [review]

**Comment by aruniverse** [comment]
@mergifyio backport release/4.7.x

**Comment by tcobbs-bentley** [comment]
> Flaky test. Did you use the "Rerun Failed Jobs" button? That would usually show up as "Attempt #2", which I don't see in your linked build. So I clicked it in your failing build and GH is now waiting for the Windows job to succeed.

I used the "Run new" button instead of just the failed jobs. I seem to remember that in the past, rerunning the failed jobs often failed more often than rerunning the whole pipeline.

**Pull request merged**
