### PR TITLE
ViewCreator3d fits to the viewed models' extents

### LINKED ISSUE #5619: ViewCreator3D should fit view
I'm creating a default view through ViewCreator3D like this
image

now the problem is by default the iModel is not zoomed in, it is always zoomed out, I tried passing different values in VsAspects but none worked. This is how view looks
image

Currently I'm using a hacky way which I've seen many teams in Bentley doing is to use FitViewTool when all tiles are loaded, this is how I'm achieving the desired functionality
image

This works perfectly fine but I think this should be the job of ViewCreator3D to fit the view instead of us doing it.

If you are wondering how I'm using the viewport then I'm creating a frontstage and passing in my view like this
image

### PR DESCRIPTION
**Pull request by pmconne**
Fixes #5619.
The `ViewCreator3d` knows the union of the extents of all of the models, but it calls `SpatialViewState.computeFitRange` which tries to (re-)compute it from the ranges of the models' tile trees, which are not yet loaded; therefore it would fall back to using the project extents.
Added an optional `baseExtents` to that method to permit it to provide its precomputed minimal extents.

### CODE REVIEW

**Comment by pmconne** [comment]
Unrelated audit failure. @aruniverse FYI - I'll check if it's an easy fix.
```
Invoking "rush-pnpm audit --audit-level high"
---------------------------------------------


┌─────────────────────┬────────────────────────────────────────────────────────┐
│ high                │ dottie vulnerable to Prototype Pollution               │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ dottie                                                 │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ <2.0.4                                                 │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Patched versions    │ >=2.0.4                                                │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Paths               │ ../../full-stack-tests/backend > azurite@3.23.0 >      │
│                     │ sequelize@6.31.0 > dottie@2.0.3                        │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ More info           │ https://github.com/advisories/GHSA-4gxf-g5gf-22h4      │
└─────────────────────┴────────────────────────────────────────────────────────┘
3 vulnerabilities found
Severity: 2 moderate | 1 high
```

**Comment by aruniverse** [comment]
> Unrelated audit failure. @aruniverse FYI - I'll check if it's an easy fix.

Since its coming from azurite, i wonder if updating to 3.24.0 will resolve the issue. That should alleviate the CVE here: https://github.com/iTwin/itwinjs-core/blob/master/common/config/rush/pnpm-config.json#L27

**Comment by pmconne** [comment]
@aruniverse these instructions are not sufficient.
```
 The following file(s) contain uncommitted changes:
 M common/api/core-frontend.api.md
Please do the following:\n1. run extract-api in the core/extension dir \n2. commit the modified generated extension api files (found in the core/frontend and core/extension dirs) \n3. run rush change and commit the change files for core-frontend and core-extension
```

I presume I must `rush build --to core-extension` first - without that I get "Failed to read extension api csv". Anything else?

**Comment by aruniverse** [comment]
> @aruniverse these instructions are not sufficient.
>  The following file(s) contain uncommitted changes:

>  M common/api/core-frontend.api.md

It's complaining about extract-api in core-frontend not core-extension

**Comment by pmconne** [comment]
> It's complaining about extract-api in core-frontend not core-extension

> `1. run extract-api in the core/extension dir`

**Comment by aruniverse** [comment]
> > It's complaining about extract-api in core-frontend not core-extension
> 
> > `1. run extract-api in the core/extension dir`

updated the hint

**Review by aruniverse — APPROVED** [review]

**Review by bbastings — APPROVED** [review]

**Pull request merged**
