### PR TITLE
UI: Fix tree node icon alignment

### PR DESCRIPTION
**Pull request by roluk**

### CODE REVIEW

**Review by grigasp — APPROVED** [review]

**Review by bsteinbk — APPROVED** [review]

**Comment by roluk** [comment]
After testing with node descriptions turned on I found that shifting the expansion chevron up instead of node icon down achieves a better alignment. Updated screenshots.

**Review by bsteinbk — APPROVED** [review]

**Comment by roluk** [comment]
Found a couple more problematic alignment issues in Chrome, going to hold off making further adjustments until we can get visibility checkbox from iTwinUI.

**Comment by grigasp** [comment]
LGTM.

Chrome:
image
Firefox:
image
Edge:
image

**Review by grigasp — APPROVED** [review]

**Review by grigasp — APPROVED** [review]

**Comment by jjbeckman13** [comment]
This broke the centering of the checkbox.
` > .core-image-checkbox {
      top: -1px;
    }
`
see https://itwin.vercel.app/view/project/1bff8c44-3196-4231-b8f6-66cf6dacd45b/imodel/625fa3c3-0d3c-47ad-99a8-dbd8b8295ce0
image

**Pull request merged**
