### PR TITLE
Improve resolution of planar clip masks

### PR DESCRIPTION
**Pull request by DStradley**
Fixed several problem cases that would cause lower or poor resolution of the clip mask.  Also increased the size of the texture for the clip mask to improve general resolution.

Fixes https://github.com/iTwin/itwin-graphics-backlog/issues/282 and some of https://github.com/iTwin/itwin-graphics-backlog/issues/283

### CODE REVIEW

**Comment by DStradley** [comment]
About to kick-off final runs of a suite of ImageTests for this to double check final cleanup.

**Comment by pmconne** [comment]
You added your new test cases to the nightly ImageTests runs, right?

**Comment by DStradley** [comment]
> You added your new test cases to the nightly ImageTests runs, right?

Yes, except the 3 views for the better near resolution, which am in process of adding.

**Review by pmconne — APPROVED** [review]
Looks great.

**Comment by DStradley** [comment]
Found a problem in ImageTests run with terrain no imagery test case (isContentUnbounded case) and put in a simple fix.
Re-running ImageTests again.

**Comment by MarcNeely** [comment]
ImageTests run looks good.

**Comment by danieliborra** [comment]
@MarcNeely @DStradley can you back-port this?

**Comment by MarcNeely** [comment]
@Mergifyio backport release/4.7.x

**Pull request merged**
