### PR TITLE
ViewCreator3d default lighting update

### PR DESCRIPTION
**Pull request by Ellord207**
This change updates the default view created by the ViewCreator3d with brighter lighting. A flag was also added to the ViewCreatorOptions that would allow users to op-out of the display styling changes.

There was a [previous similar PR](https://github.com/iTwin/itwinjs-core/pull/2681) that had to be closed due to authentication issues.  Will address the requested changes here.

### CODE REVIEW

**Comment by Ellord207** [comment]
From previous PR @pmconne 

> Are you intentionally not enabling ambient occlusion?

I'm purposely avoiding turning on ambient occlusion by default due to the performance impacted it can have.

**Comment by pmconne** [comment]
> I'm purposely avoiding turning on ambient occlusion by default due to the performance impacted it can have.

This lighting setup is intended for use with AO.
Did you measure this performance impact?

**Comment by Ellord207** [comment]
> Did you measure this performance impact?

No, I was remembering that you have mentioned before.  I believe performance was the reason you avoided making it default in the view.  Please correct me if you're wrong.

**Comment by pmconne** [comment]
> No, I was remembering that you have mentioned before. I believe performance was the reason you avoided making it default in the view. Please correct me if I'm wrong.

You are probably thinking of MSAA.

@markschlosseratbentley filed some AO-related enhancements that we should consider completing before proceeding with changing the ViewCreator3d defaults.

**Comment by pmconne** [comment]
@Ellord207 what's the plan for this PR? Please close it if no longer relevant.

**Comment by Ellord207** [comment]
> @Ellord207 what's the plan for this PR? Please close it if no longer relevant.

This PR was delayed for a major release with the intent of changing the default behavior.  3.0 has gone by with this PR forgotten.  The PR should be complete, but changing the behavior to be opt-in.

**Comment by aruniverse** [comment]
@Ellord207 is this needed for 4.0?

**Comment by Ellord207** [comment]
> @Ellord207 is this needed for 4.0?

Yes, waiting for 4.0 as this will be a minor, but still breaking change as it will update the default behavior.

**Comment by pmconne** [comment]
@Ellord207 who is actually asking for this? And have you changed you mind re:

> The PR should be complete, but changing the behavior to be opt-in.

**Comment by Ellord207** [comment]
> who is actually asking for this?

You could say it's the sandbox requesting it.  It's low hanging fruit to give first time users an improved visual experience.

> And have you changed you mind re:
> 
> > The PR should be complete, but changing the behavior to be opt-in.

Just forgotten.  I will make sure this completes before that happens again.

**Comment by aruniverse** [comment]
> You could say it's the sandbox requesting it

Why cant the sandbox do this internally on their end? 
If we dont have a large enough user count/request for this functionality, then why is this default being changed to accommodate this new lighting? That should be validated.

**Comment by Ellord207** [comment]
> Why cant the sandbox do this internally on their end?

We do this some, but whenever we add code to our template, then that increases the code we have people ask, "what does this do?" (see sprint reviews from when the samples were first getting introduced) and the code that get's blindly copy and pasted by new users (observed during hackathons).

> If we dont have a large enough user count/request for this functionality, then why is this default being changed to accommodate this new lighting? That should be validated.

That was the original intent, but @pmconne and I had a conversation about this.  It was agreed that the ViewCreator was to old to be changing the default behavior (breaking), but adding an opt-in option to draw attention to the new(er) display features would still add value.  See my last comment from Dec. 9th.  I had just forgotten since I when on vacation shortly after that comment.

> The PR should be complete, but changing the behavior to be opt-in.

**Comment by Ellord207** [comment]
Higher-priority tasks are blocking me from working on this.  Closing PR.  I will come back to work on this task later.

**Pull request closed without merging**
