### PR TITLE
Allow setting composite EC properties to null

### PR DESCRIPTION
**Pull request by 6ar8nas**
imodel-native: https://github.com/iTwin/imodel-native/pull/688

There has been an issue where non-primitive properties (struct, array) didn't respond to an update request to "null". This PR adds a test validating the changes on imodel-native side and adds documentation on expected behaviors for setting a property to null.

### Misc

Added `ecschema-metadata` clean script to enable usage of `rush clean`.

Closes iTwin/itwinjs-backlog#1057

### CODE REVIEW

**Review by ColinKerr — APPROVED** [review]

**Review by ColinKerr — APPROVED** [review]

**Review by rschili — APPROVED** [review]

**Review by khanaffan — APPROVED** [review]

**Review by khanaffan — APPROVED** [review]

**Review by pmconne — APPROVED** [review]

**Comment by pmconne** [comment]
Android build timed out yesterday while publishing the new addon. I requeued it. Please [keep an eye](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=3004154&view=logs&j=e96296ee-5235-5de9-0b23-6263ff41e54f&t=ea59d40a-51b6-5f38-b364-f4f3b065557b&s=121a4c96-a877-5aee-28dc-435232aa1161) on it.

**Comment by pmconne** [comment]
@DanRod1999 [publish to npmjs](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=3007219&view=logs&j=66dba6ff-6020-55c3-7f16-d853cc586514&t=c28049a5-63e9-511e-ddd9-1ebf34fbb0ab) succeeded for windows, then failed for linux.

**Comment by DanRod1999** [comment]
I believe so too. Might need to re trigger node addon version bump and add the itwinjs-core PR number so the addon is pushed to that branch. Is the error seem transient? Rerunning the failed job first just in case might be worth a try first?

**Comment by pmconne** [comment]
> Rerunning the failed job first just in case might be worth a try first?

Already did that, failed due to existing published version as expected. Original error details linked in previous comment.

**Comment by nick4598** [comment]
Surprisingly, theres only this NodeAddon release from today, yet it says that imodeljs-linux-x64 was already published in the first attempt.
`npm error 403 403 Forbidden - PUT https://registry.npmjs.org/@bentley%2fimodeljs-linux-x64 - You cannot publish over the previously published versions: 4.8.19.`
On npm https://www.npmjs.com/package/@bentley/imodeljs-linux-x64/v/4.8.19?activeTab=readme, it also appears that 4.8.19 was published around the same time that it claimed to have failed within the pipeline due to it already existing. Not sure how that happened, but darwin 4.8.19 is missing as a result. I see another PR was just merged on imodel-native, so hopefully 4.8.20 will go off without a hitch and we can merge master into this branch to pick up the corresponding native changes. I'll monitor the release build. https://bentleycs.visualstudio.com/iModelTechnologies/_build/results?buildId=3007793&view=results

**Pull request merged**
