### PR TITLE
@bentley/imodeljs-native-3.0.22

### PR DESCRIPTION
**Pull request by pmconne**

### CODE REVIEW

**Comment by pmconne** [comment]
@AlainRobertAtBentley 
```
--[ FAILURE: @itwin/core-backend ]-----------------[ 4 minutes 51.5 seconds ]--


  302 passing (1m)
  6 pending
  1 failing

  1) GeoServices
       should be able to interpret to completion an incomplete GeographicCRS:

      AssertionError: expected false to be true
      + expected - actual
  ...1 line omitted...
      -false
      +true

      at completionTest (src\test\misc\GeoServices.test.ts:24:14)
      at Context.<anonymous> (src\test\misc\GeoServices.test.ts:365:11)
      at processImmediate (internal/timers.js:464:21)
```

**Review by nick4598 — APPROVED** [review]

**Comment by pmconne** [comment]
@AlainRobertAtBentley the Linux job failed this test:
```
  1) iModel
       should be able to reproject with iModel coordinates to or from any other GeographicCRS:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at convertTest (src/test/imodel/IModel.test.ts:1720:66)
      at Context.<anonymous> (src/test/imodel/IModel.test.ts:1817:5)
```

**Comment by pmconne** [comment]
@AlainRobertAtBentley @kabentley I reran the Linux job and the same test failed in the same spot.

**Comment by pmconne** [comment]
```
expected [-121.58905088839697,38.53252275385171,0] actual [-121.58798236995744,38.532616292208,0]
    1) should be able to reproject with iModel coordinates to or from any other GeographicCRS
```

**Comment by pmconne** [comment]
Abandoning due to issues with case-sensitive csmap filenames on Linux.

**Comment by kabentley** [comment]
> ```
> expected [-121.58905088839697,38.53252275385171,0]
> actual   [-121.58798236995744,38.532616292208,  0]
>     1) should be able to reproject with iModel coordinates to or from any other GeographicCRS
> ```

Don't know how. @MichaelBelousov  verified it on his box. Are you sure there are no build errors and that you got [this PR](https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/211697)? There definitely was an error, and i definitely fixed it.

**Pull request closed without merging**
