### PR TITLE
Use relative links instead of $docs syntax

### PR DESCRIPTION
**Pull request by williamkbentley**
- Use relative links for md -> md linking
    - Makes navigating links in Github and VSCode easier
    - Improves readability
    - Functionality equivalent
 - TODO: Update tooling to reject $docs link syntax in Markdown files

### CODE REVIEW

**Review by pmconne — APPROVED** [review]
I assume bmsBuild will catch any invalid links.

**Review by grigasp — APPROVED** [review]

**Comment by williamkbentley** [comment]
> I assume bmsBuild will catch any invalid links.

Yes. See TODO. Separate PR will be completed after this one.

**Comment by calebmshafer** [comment]
@mergifyio backport release/3.1.x

**Comment by calebmshafer** [comment]
@Mergifyio backport release/3.0.x

**Pull request merged**
