### PR TITLE
imodeljs-native@4.2.2

### PR DESCRIPTION
**Pull request by markschlosseratbentley**

### CODE REVIEW

**Review by aruniverse — APPROVED** [review]

**Comment by markschlosseratbentley** [comment]
`rush cover` on CI is failing [here](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=2369992&view=logs&j=9f3a3068-7880-5994-433d-b92c1f9d379b&t=da1bc539-0d62-5c29-85fd-865150eba47d&l=11823), in TxnManager tests, something about local changes.  @khanaffan is this related to the API changes for iterating local changes?

**Comment by khanaffan** [comment]
> `rush cover` on CI is failing [here](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=2369992&view=logs&j=9f3a3068-7880-5994-433d-b92c1f9d379b&t=da1bc539-0d62-5c29-85fd-865150eba47d&l=11823), in TxnManager tests, something about local changes. @khanaffan is this related to the API changes for iterating local changes?

I have PR for it. But you can fix it in your PR as well.

https://github.com/iTwin/itwinjs-core/pull/5924

**Comment by aruniverse** [comment]
> > `rush cover` on CI is failing [here](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=2369992&view=logs&j=9f3a3068-7880-5994-433d-b92c1f9d379b&t=da1bc539-0d62-5c29-85fd-865150eba47d&l=11823), in TxnManager tests, something about local changes. @khanaffan is this related to the API changes for iterating local changes?
> 
> I have PR for it. But you can fix it in your PR as well.
> 
> #5924

pr merged; you can cherry pick that commit over into this branch

**Comment by aruniverse** [comment]
@nick4598 plz look at failing integration tests
image

**Comment by markschlosseratbentley** [comment]
@calebmshafer @pmconne Can you complete the PR without squashing commits?
cc @aruniverse

**Comment by nick4598** [comment]
Its good to go now @aruniverse

**Pull request merged**
