### PR TITLE
Fix framebuffer resize issue that causes WebGL errors

### PR DESCRIPTION
**Pull request by markschlosseratbentley**
This PR resolves a problem that can happen when viewports are resized after quickly dropping and adding them.
When a viewport is quickly dropped and added, an internal render-to-screen optimization gets toggled off and on.
The function that does this toggling updates the internally-tracked view rectangle in case of resize.  However, it does not then recreate the WebGL framebuffers with the new dimensions, causing this error to occur.

Work items: [here](https://bentleycs.visualstudio.com/iModelTechnologies/_workitems/edit/534091) and [here](https://bentleycs.visualstudio.com/iModelTechnologies/_workitems/edit/847343) and [here](https://bentleycs.visualstudio.com/iModelTechnologies/_workitems/edit/824046)

Repro steps of the fixed issue:
1. Have display-test-app maximized with a file open (Hong Kong was open for me)
2. Open a new file (I was opening LivingRoom)
3. Immediately double click the title bar of dta to make the window no longer maximized – do this before the new file manages to load  (Or you might need to drag the viewport to be a smaller size instead).
4. The new file will be rendered with the new file rendering inset into the old rendering.
5. You will see WebGL framebuffer errors in the console.
6. This does not fix itself until resizing the window again.

WebGL errors:
image

### CODE REVIEW

**Comment by pmconne** [comment]
Did you identify reproducible actions that will consistently trigger the problem?
Did you verify the events really do "halt"? That seems bizarre and scary.

**Comment by markschlosseratbentley** [comment]
> Did you identify reproducible actions that will consistently trigger the problem? Did you verify the events really do "halt"? That seems bizarre and scary.

@pmconne I can consistently reproduce with actions, yes.  I am not sure how to 100% verify that events "halt" - but I set a breakpoint during and after updateViewRect() in renderFrame() -- the breakpoint inside updateViewRect() will hit and updateViewRect() will return true.  The code in renderFrame() that checks the return of updateViewRect() never gets hit.  renderFrame will then be called again afresh in the event loop.

**Comment by pmconne** [comment]
@markschlosseratbentley please document those actions in the PR description. Did you determine whether it was related to dropping and re-adding the viewport to the view manager?

**Comment by markschlosseratbentley** [comment]
> @markschlosseratbentley please document those actions in the PR description. Did you determine whether it was related to dropping and re-adding the viewport to the view manager?

@pmconne I added a link to the bug which contains repro steps for the simple display-test-app case.  Not sure about adding and dropping viewports - I can double check that next.

**Comment by pmconne** [comment]
@markschlosseratbentley please do - we ought to understand what's happening here.
Have you determined whether this workaround addresses the more pressing [related defect](https://bentleycs.visualstudio.com/iModelTechnologies/_workitems/edit/824046)?

**Comment by markschlosseratbentley** [comment]
> > @markschlosseratbentley please do - we ought to understand what's happening here. Have you determined whether this workaround addresses the more pressing [related defect](https://bentleycs.visualstudio.com/iModelTechnologies/_workitems/edit/824046)?
> 
> @pmconne Yes - as described on Teams, this code resolves the [related issue](https://bentleycs.visualstudio.com/iModelTechnologies/_workitems/edit/847343). (Not the exact same issue you linked, but we believe they are the same thing).

@pmconne Updated description of this PR with results of more detailed investigation.  Pushed more precise fix.

**Comment by pmconne** [comment]
Possible to write a unit test that would detect the issue prior to your fix and prove it's now fixed (and will remain so in future)?

**Comment by markschlosseratbentley** [comment]
> Possible to write a unit test that would detect the issue prior to your fix and prove it's now fixed (and will remain so in future)?

@pmconne Was thinking about that.  Not sure since it's so reliant on timing, but it may be possible.

**Comment by markschlosseratbentley** [comment]
> > Possible to write a unit test that would detect the issue prior to your fix and prove it's now fixed (and will remain so in future)?
> 
> @pmconne Was thinking about that. Not sure since it's so reliant on timing, but it may be possible.

@pmconne Test added.

**Review by pmconne — APPROVED** [review]

**Comment by markschlosseratbentley** [comment]
@calebmshafer This PR is stuck on license/cla - Waiting for status to be reported.  What's the recommended way to make that start again?

**Comment by pmconne** [comment]
Bypassed CLA check.

**Comment by markschlosseratbentley** [comment]
> > @calebmshafer This PR is stuck on license/cla - Waiting for status to be reported. What's the recommended way to make that start again?
> 
> @markschlosseratbentley normally a new commit will force it but that does mean you need to re-run all of them. Alternatively I normally go into cla-assistant and have it re-check the PRs but that's not really something that scales.
> 
> @skirby1996 we should look into whether we can have a GitHub bot that allows people to force a re-check...

Thanks @calebmshafer - I was definitely pushing several commits to this PR / branch, but somehow the CLA thing just got stuck anyway.

**Pull request merged**
