### PR TITLE
Promote placement and manipulation tool api release tags to beta

### PR DESCRIPTION
**Pull request by bbastings**

### CODE REVIEW

**Review by pmconne — APPROVED** [review]
@ben-polinsky we're going to want to add these 3 packages to the doc site.

**Comment by aruniverse** [comment]
@mergifyio backport release/4.0.x

**Comment by ben-polinsky** [comment]
> @ben-polinsky we're going to want to add these 3 packages to the doc site.

Sure. Want me to add the changes to this branch?

**Comment by bbastings** [comment]
> > @ben-polinsky we're going to want to add these 3 packages to the doc site.
> 
> Sure. Want me to add the changes to this branch?

Yes, please...I disabled auto-merge.

**Comment by ben-polinsky** [comment]
> > > @ben-polinsky we're going to want to add these 3 packages to the doc site.
> > 
> > 
> > Sure. Want me to add the changes to this branch?
> 
> Yes, please...I disabled auto-merge.

Done. My annotations are admittedly bland.

**Comment by ben-polinsky** [comment]
@pmconne @bbastings fixed most of the docs issues. Last one, I think:

`Invalid Link: "[CreateElementTool.targetModel]($editor-frontend)" in file "reference/core-frontend/imodelconnection/briefcaseeditortoolsettings/model"`

[Issue is here](https://github.com/iTwin/itwinjs-core/pull/5708/files#diff-1688dec24b2c7c577ef5779cf4f4d4db4fdd1c589db33c9dd0450587bbbcbd1fL236) - `targetModel` does not exist - wasn't sure if `targetModelId` was correct.

**Comment by bbastings** [comment]
> wasn't sure if `targetModelId` was correct.
targetModelId is correct

**Review by aruniverse — APPROVED** [review]

**Pull request merged**
