### PR TITLE
Add option for chunk traversal.

### PR DESCRIPTION
**Pull request by diegopinate**
Changed Elements chunk traversal perf improvement options.

### CODE REVIEW

**Comment by pmconne** [comment]
@diegopinate is this a backport of a prior PR? I could not find one.

**Comment by diegopinate** [comment]
> @diegopinate is this a backport of a prior PR? I could not find one.

No, this is a new one. I forgot to add the options. The native addon change added the new options, needed to add them to our def here and pass them to the native calls.

**Comment by diegopinate** [comment]
[@mergifyio](mailto:%60@mergifyio) backport master

**Comment by aruniverse** [comment]
> Why not submit PR to master first, then backport?

my fault; told him its faster to target a pr into the release branch then forward port it, to get a new patch release out faster

otherwise need to wait for pr to merge into master, bp created, then wait for that to merge

**Review by aruniverse — APPROVED** [review]

**Review by calebmshafer — APPROVED** [review]

**Comment by calebmshafer** [comment]
>  backport release/3.3.x

@diegopinate I think you'll want to backport to master

**Pull request merged**
