### PR TITLE
imodeljs-native@4.1.6

### PR DESCRIPTION
**Pull request by DanRod1999**
integrate new addon which will deliver node18 for mobile

### CODE REVIEW

**Review by aruniverse — APPROVED** [review]
lgtm; would be good to get @tcobbs-bentley verify and approve the mobile test app loads and doesnt crash on startup

**Comment by tcobbs-bentley** [comment]
@aruniverse I am in the process of testing now (with Steve's add-on updates).

However, in order to get display-test-app to work, I had to make two changes in itwinjs-core that I haven't yet submitted a PR for: update the minSdk from 24 to 28, and update the Gradle compile memory from 2GB to 4GB. (The latter change is probably only necessary when building with a debug add-on.) Should I commit those two changes to this branch?

**Comment by aruniverse** [comment]
> @aruniverse I am in the process of testing now (with Steve's add-on updates).
> 
> However, in order to get display-test-app to work, I had to make two changes in itwinjs-core that I haven't yet submitted a PR for: update the minSdk from 24 to 28, and update the Gradle compile memory from 2GB to 4GB. (The latter change is probably only necessary when building with a debug add-on.) Should I commit those two changes to this branch?

if you can, yes please

**Comment by aruniverse** [comment]
> > @aruniverse I am in the process of testing now (with Steve's add-on updates).
> > However, in order to get display-test-app to work, I had to make two changes in itwinjs-core that I haven't yet submitted a PR for: update the minSdk from 24 to 28, and update the Gradle compile memory from 2GB to 4GB. (The latter change is probably only necessary when building with a debug add-on.) Should I commit those two changes to this branch?
> 
> if you can, yes please

since the vite changes will require other changes for mobile, we can do that in a separate pr; so disregard my earlier comment

**Comment by tcobbs-bentley** [comment]
> since the vite changes will require other changes for mobile, we can do that in a separate pr; so disregard my earlier comment

After making various changes (that you don't want me to commit), I have verified that things work on Android. I'm getting a connection error on iOS, and I'm still trying to figure out why.

**Comment by tcobbs-bentley** [comment]
I'm unable to get display-test-app iOS working, but the iTwin Mobile SDK iOS sample app **does** work with add-on 4.1.6. I don't think there is anything wrong with this PR.

**Pull request merged**
