### PR TITLE
Layers could not be added through MapLayers widget when UserPreferences was not set. Fix various issues related to user preferences.

### PR DESCRIPTION
**Pull request by mdastous-bentley**
Fix the following issues:

1. When `MapLayersUI.iTwinConfig` was not defined, layers would refuse to add in the view. 
2. No longer display the User preferences options when  `MapLayersUI.iTwinConfig` is undefined.
3. If  `MapLayersUI.iTwinConfig`  has been defined, but saving preferences fails, still add layer to view and display an error message.
4. Make the 'iTwin' radio button checked by default, (typo in initial `settingsStorage `state value)

### CODE REVIEW

**Review by bsteinbk — APPROVED** [review]

**Comment by bsteinbk** [comment]
@calebmshafer when you have time I should be removed from this project/package as a codeowner. I am fine with reviewing UI changes for the next few month until my retirement, but someone else from Michel's team should be added to review map layer changes.

**Review by calebmshafer — APPROVED** [review]
LGTM

**Comment by calebmshafer** [comment]
> @calebmshafer when you have time I should be removed from this project/package as a codeowner. I am fine with reviewing UI changes for the next few month until my retirement, but someone else from Michel's team should be added to review map layer changes.

Sure, we should have more than one person that can review it though. @mdastous-bentley is there anyone else you'd want to be able to review this?

**Comment by mdastous-bentley** [comment]
@Mergifyio update

**Pull request merged**
