### PR TITLE
Make edit command and flatbuffer geometry apis beta

### PR DESCRIPTION
**Pull request by bbastings**

### CODE REVIEW

**Review by mgooding — COMMENTED** [review]
LGTM, but some description in NextVersion.md would be nice.

**Comment by bbastings** [comment]
> LGTM, but some description in NextVersion.md would be nice.

Wasn't sure a beta api was something we note in nextversion.md...

**Comment by pmconne** [comment]
> Wasn't sure a beta api was something we note in nextversion.md...

It is.

**Review by mgooding — APPROVED** [review]

**Comment by kckst8** [comment]
@bbastings, @karolis-zukauskas is working on some changes that we would like to propose next week when Keith returns. Can this wait until then? Is there urgency to promote these?

**Comment by bbastings** [comment]
> @bbastings, @karolis-zukauskas is working on some changes that we would like to propose next week when Keith returns. Can this wait until then? Is there urgency to promote these?

I thought we covered this last meeting...can I get some idea of what type of changes?

**Comment by kckst8** [comment]
> > @bbastings, @karolis-zukauskas is working on some changes that we would like to propose next week when Keith returns. Can this wait until then? Is there urgency to promote these?
> 
> I thought we covered this last meeting...can I get some idea of what type of changes?

Going to setup a mtg for @karolis-zukauskas to review next week

**Pull request closed without merging**
