### PR TITLE
maint: speed up local builds + esm NextVersion update

### PR DESCRIPTION
**Pull request by aruniverse**
So as per the discussion in this thread:
- dropped the `compile` command
- updated the `build` command to build only cjs (and whatever else necessary to run tests)
- added a `build:ci` command which will build both cjs & esm
  - this command is run on master and the publish/release ci
    - if there are issues building esm, we'll catch it then
  - moved webpacking frontends of test-apps here

Also add NextVersion.md update for ESM changes.

### CODE REVIEW

**Comment by aruniverse** [comment]
@Mergifyio update

**Comment by aruniverse** [comment]
> > Yea sure thing, i'll push that out in a second. There's a flag, "incremental", i can add so it behaves like the "build" command and use the build cache.
> > [rushjs.io/pages/advanced/incremental_builds](https://rushjs.io/pages/advanced/incremental_builds/) [rushjs.io/pages/configs/command-line_json](https://rushjs.io/pages/configs/command-line_json/)
> 
> Wonderful. Just a thought: maybe `rush build` should build only one (cjs?) and then have `rush build-ci` that builds both?

@calebmshafer thoughts? How easy would it be to update all our pipelines to run a separate build:ci script?

**Comment by calebmshafer** [comment]
@aruniverse can we add the "incremental" flag to the "rush compile" command line option in the `common/config/rush/command-line.json`?

**Comment by aruniverse** [comment]
> It seems to me that it should only be the final one that creates the npm packages that needs to build both. Why slow down every CI job (that are already painfully slow) building both ways?

While doing my initial esm pr, I noticed in some packages we were able to successfully build cjs but not esm. Sometimes if we have a dependency on a cjs module and import from it, our cjs build will succeed but the esm won't unless you enable [esModuleInterop](https://www.typescriptlang.org/tsconfig#esModuleInterop) in the tsconfig. And that option wasn't enabled in every pkg (or in the base tsconfig) we have because we'd have to update way too many files (on top of the ~800 files i initially touched). There was also a case where after enabling that option in some packages, both cjs and esm built fine, but some tests failed until that was disabled. So while it does add an additional 2 mins to our builds it's helpful so we can catch esm build/test failures before we publish in the the cicd.

But then again, we do run the cicd/releases nightly so we'd catch any issues before an official release.

**Pull request merged**
