### PR TITLE
fix scss deprecation warning

### PR DESCRIPTION
**Pull request by aruniverse**
Fixes:

image

### CODE REVIEW

**Comment by aruniverse** [comment]
> Were all the warnings for this single line ??? [iTwin/itwinjs-backlog#437](https://github.com/iTwin/itwinjs-backlog/issues/437)

Yes I believe so, but would be good for someone to do a full scss audit for the 3.5 release

**Review by raplemie — APPROVED** [review]
LGTM

**Comment by JiriJa** [comment]
Same problem ... agree ... would be good for someone to do a full scss audit for the 3.5 release


Výstřižek_441

**Comment by aruniverse** [comment]
> Same problem ... agree ... would be good for someone to do a full scss audit for the 3.5 release

@JiriJa , this will be fixed in our 3.4 release, which should be out in the next few days.

**Pull request merged**
