### PR TITLE
@bentley/imodeljs-native 3.1.3

### PR DESCRIPTION
**Pull request by pmconne**

### CODE REVIEW

**Comment by pmconne** [comment]
Awaiting fix for [enzyme-adapter-utils](https://github.com/wojtekmaj/enzyme-adapter-utils/issues/2).

**Comment by pmconne** [comment]
@khanaffan is this discrepancy in changeset size expected?
```
  1) IModelWriteTest
       changeset size and ec schema version change:

      AssertionError: expected 1357661 to equal 1357585
      + expected - actual
  ...10 lines omitted...
      + expected - actual

      -3902
      +3826

      at Context.<anonymous> (src\test\standalone\IModelWrite.test.ts:466:12)
```

**Comment by pmconne** [comment]
@grigasp @saskliutas 1 failing presentation test.
```
--[ FAILURE: presentation-full-stack-tests ]-------[ 4 minutes 42.6 seconds ]--


  189 passing (1m)
  1 pending
  1 failing

  1) Learning Snippets
       Specifications
         Shared attributes
           uses `relatedProperties` attribute:

  ...739 lines omitted...
      -      "valueFormat": "Struct"
      -    }
         }
       ]

      at Context.<anonymous> (src\learning-snippets\Content.test.ts:710:47)
```

**Review by bbastings — APPROVED** [review]

**Comment by khanaffan** [comment]
> @khanaffan is this discrepancy in changeset size expected?
> 
> ```
>   1) IModelWriteTest
>        changeset size and ec schema version change:
> 
>       AssertionError: expected 1357661 to equal 1357585
>       + expected - actual
>   ...10 lines omitted...
>       + expected - actual
> 
>       -3902
>       +3826
> 
>       at Context.<anonymous> (src\test\standalone\IModelWrite.test.ts:466:12)
> ```


It is in memory max size of changeset held by session extension. Though it should not arbitrary change. But I cannot tell what would have changed it. The changeset simply have less data bytes now then before for same same operation. May be `IModelJson.Writer.toIModelJson(geom)` generate smaller json. SQLite has not updated so we can rule out that. I have to investigate this one which might take time. So i can add it to backlog and look at it later.

**Review by kabentley — APPROVED** [review]

**Comment by pmconne** [comment]
> So i can add it to backlog and look at it later.

Thanks - can you be more specific about "later"? I don't see any native commits that really stick out either. Maybe one of @MichaelBelousov's changes?

**Comment by MichaelBelousov** [comment]
> Maybe one of @MichaelBelousov's changes

The geometry is still persisted the same in the imodel, but writing elements with geometry properties to Json (when they're in the memory pool) is now no longer writing geometry properties as an Xml string. If the Json encoding of an element affects change set size then maybe that changed it

**Comment by grigasp** [comment]
> @grigasp @saskliutas 1 failing presentation test.
> 
> ```
> --[ FAILURE: presentation-full-stack-tests ]-------[ 4 minutes 42.6 seconds ]--
> 
> 
>   189 passing (1m)
>   1 pending
>   1 failing
> 
>   1) Learning Snippets
>        Specifications
>          Shared attributes
>            uses `relatedProperties` attribute:
> 
>   ...739 lines omitted...
>       -      "valueFormat": "Struct"
>       -    }
>          }
>        ]
> 
>       at Context.<anonymous> (src\learning-snippets\Content.test.ts:710:47)
> ```

I honestly don't understand how this happened:
- This test was fixed in [commit 5cf5865f6cf6a6bb2bf2ad40269dadebbafd281b](https://github.com/iTwin/itwinjs-core/blame/5cf5865f6cf6a6bb2bf2ad40269dadebbafd281b/full-stack-tests/presentation/src/learning-snippets/Content.test.ts#L711). It's in this branch.
- The test is still fine in [commit 335dc708cd18c603f47f215049e0f764ca56e50b](https://github.com/iTwin/itwinjs-core/blob/335dc708cd18c603f47f215049e0f764ca56e50b/full-stack-tests/presentation/src/learning-snippets/Content.test.ts#L711).
- The test is reverted to a version prior to the fix in [merge commit 70d126c06e97d9dc9f30e6b7908e2ab38b49aaae](https://github.com/iTwin/itwinjs-core/commit/70d126c06e97d9dc9f30e6b7908e2ab38b49aaae) that comes right after [commit 335dc708cd18c603f47f215049e0f764ca56e50b](https://github.com/iTwin/itwinjs-core/blob/335dc708cd18c603f47f215049e0f764ca56e50b/full-stack-tests/presentation/src/learning-snippets/Content.test.ts#L711). However, the changeset doesn't show any changes for the test... It seems the history was rewritten or something like that happened.

In any case, cherry picked the fix again and now the test passes.

**Review by grigasp — APPROVED** [review]

**Comment by pmconne** [comment]
IModelWrite test failures were caused by [this PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/222260).

**Pull request closed without merging**
