### PR TITLE
Change RpcBriefcaseUtility.open to attempt to download a v2 checkpoint when failing to lazily open a v2 checkpoint

### PR DESCRIPTION
**Pull request by nick4598**
Before this PR, RpcBriefcaseUtility.open would immediately fall back to a v1 checkpoint if there was a failure to lazily open a v2 checkpoint. We will still eventually fall back to a v1 checkpoint, but only if we also fail to fully download a v2 checkpoint ( applying changesets if necessary).

I've added two properties to the DownloadRequest Interface:
     "downloadV2Only" prop, to give better control over the CheckpointManager.downloadCheckpoint call which falls back to v1 checkpoints under certain conditions.
     "dontApplyChangesets" prop, which when true will only download a checkpoint if no changesets need to be applied to it in order to satisfy the request.

### CODE REVIEW

**Review by pmconne — COMMENTED** [review]
Looking into integration test failures? They don't look like the typical flakiness.

**Comment by nick4598** [comment]
> 



> Looking into integration test failures? They don't look like the typical flakiness.

Yeah I think you're right. Just started looking at this, probably won't have anything until tomorrow.

**Comment by kabentley** [comment]
This isn't really the right thing for our backends to do. If there's no V2 checkpoint for the requested version, we should either fail or request that one be created. Backends should never apply changesets themselves.

**Comment by nick4598** [comment]
> This isn't really the right thing for our backends to do. If there's no V2 checkpoint for the requested version, we should either fail or request that one be created. Backends should never apply changesets themselves.

After our discussion during the v2 checkpoint scrum, it seems that the only change to be made here is to support the downloading of existing v2 checkpoints in a backend if there is no daemon to support the attach and open workflow. For now, I'll mark this PR as draft.

**Comment by nick4598** [comment]
> @nick4598 should we work to get this merged in? What's left to get this validated?

We should maybe just abandon this, because the new daemonless branch will also do this. Typically we'd only fail to lazily open a v2 checkpoint if we didn't have a daemon or a BLOCKCACHE_DIR defined I believe... in daemonless both those cases are taken care of.

**Comment by calebmshafer** [comment]
@nick4598 sounds good. Just closed the PR. Please the delete the branch if we're going to no longer need it.

**Pull request closed without merging**
