### PR TITLE
remove copyright linter

### PR DESCRIPTION
**Pull request by kabentley**
The copyright linter never works for me, so I have a script to delete the pre-commit hook that I have to remember to run before I commit.

But, it is a nearly useless thing to run every commit, particularly since it is so slow in the rare case that it works, and is only necessary when someone creates a new file. Someone can run this manually once a year to check any new files that have been created.

### CODE REVIEW

**Comment by pmconne** [comment]
Can you define "never works"?
Agree on it being annoying when a simple `git commit` frequently triggers a script to download and install some version of rush. (What's wrong with the version I already have installed?)

**Comment by kabentley** [comment]
Here's what i get when I attempt to git commit. It's possible that this is related to using CoSpaces. If i accidently forget to delete it, I'm in for a 30 second delay before i see:

Invoking "rush copyright:linter"
--------------------------------



[1mRush Multi-Project Build Tool 5.97.1[22m[36m - https://rushjs.io[39m
Node.js version is 18.16.0 (LTS)


Starting "rush copyright:linter"

Trying to acquire lock for pnpm-7.32.2
Acquired lock for pnpm-7.32.2
Found pnpm version 7.32.2 in C:\Users\keith.bentley\.rush\node-v18.16.0\pnpm-7.32.2

Symlinking "D:\dev\repos\itwinjs-core\common\temp\pnpm-local"
  --> "C:\Users\keith.bentley\.rush\node-v18.16.0\pnpm-7.32.2"
Acquiring lock for "common\autoinstallers\rush-lintstaged" folder...
Transforming D:\dev\repos\itwinjs-core\common\config\rush\.npmrc
  --> "D:\dev\repos\itwinjs-core\common\autoinstallers\rush-lintstaged\.npmrc"
Installing dependencies under D:\dev\repos\itwinjs-core\common\autoinstallers\rush-lintstaged...

Scope: all 14 workspace projects
 ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with repos\eslint-plugin\package.json

Note that in CI environments this setting is true by default. If you still need to run install in such cases, use "pnpm install --no-frozen-lockfile"

[31mERROR: The command failed with exit code 1[39m
2023-06-29 07:44:11.793 [info] > git config --get-all user.name [137ms]
2023-06-29 07:44:11.928 [info] > git config --get-all user.email [128ms]
2023-06-29 07:44:12.084 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/test-copyright refs/remotes/test-copyright [142ms]
2023-06-29 07:44:12.084 [info] > git config --get commit.template [149ms]
2023-06-29 07:44:12.260 [info] > git status -z -uall [170ms]

**Comment by kabentley** [comment]
But, again, the whole concept of "linting copyright" is a useless thing to enforce *every friggin commit*, particularly if it ties rush and git.

**Comment by pmconne** [comment]
> useless thing to enforce every friggin commit

Agree. If we want to make sure every source file on master has a valid copyright notice we could enforce that in PR validation.

**Comment by calebmshafer** [comment]
> > useless thing to enforce every friggin commit
> 
> Agree. If we want to make sure every source file on master has a valid copyright notice we could enforce that in PR validation.

@pmconne @kabentley not opposed to change this. However, we did start out with it in the PR rather than on every commit and that was too late of an indicator.  We did re-write this a while ago to ditch the linter version. Maybe we resurrect that PR so it's not as slow or annoying?

**Comment by kabentley** [comment]
> However, we did start out with it in the PR rather than on every commit and that was too late of an indicator (and wasted a lot of build time).

I don't understand why it's "too late" or why it wasted a lot of build time. How can it be more expensive than the linting we do on every line of source code?

> Maybe we resurrect that PR so it's not as slow or annoying.

No, philosophically this is just not something that should be checked at git commit time. Do it once a year when we update the copyright year in LICENSE.md and all is fine.

**Comment by kabentley** [comment]
@aruniverse @calebmshafer please either approve this PR or propose an alternative.

**Comment by calebmshafer** [comment]
@kabentley I'll push a change to make it happen on PR build but not locally. does that work?

**Comment by kabentley** [comment]
@calebmshafer can I assume that you will complete this PR when it's ready?

**Review by calebmshafer — APPROVED** [review]

**Comment by calebmshafer** [comment]
> @calebmshafer can I assume that you will complete this PR when it's ready?

@kabentley yes, good to go. Just set auto-complete.

**Pull request merged**
