### PR TITLE
Add a getter for sourceDbChanges in core-transformer

### PR DESCRIPTION
**Pull request by ViliusRuskys**
Add a getter for sourceDbChanges in core-transformer.

This is useful for applications consuming the core-transformer package. By accessing 'sourceDbChanges' you get the information on what elements were added/modified/deleted. Also, knowing the amount of elements changed will be useful for progress tracking.

### CODE REVIEW

**Review by MichaelBelousov — APPROVED** [review]

**Comment by MichaelBelousov** [comment]
@mergifyio backport release/3.7.x

**Comment by MichaelBelousov** [comment]
@aruniverse have you seen this doc pipeline error yet? https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=1979980&view=results
got it a couple times in a row here

**Comment by aruniverse** [comment]
> @aruniverse have you seen this doc pipeline error yet? [dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=1979980&view=results](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=1979980&view=results) got it a couple times in a row here

@calebmshafer correct me if im wrong, this pipeline doesnt work for forked repos?
cc @ben-polinsky

**Comment by ben-polinsky** [comment]
> > @aruniverse have you seen this doc pipeline error yet? [dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=1979980&view=results](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=1979980&view=results) got it a couple times in a row here
> 
> @calebmshafer correct me if im wrong, this pipeline doesnt work for forked repos? cc @ben-polinsky

Correct. I imagine we can be more specific in the pipeline to scope where we search for artifacts in this case.

**Comment by MichaelBelousov** [comment]
@ben-polinsky how can this PR proceed then? Do we need to wait for a fix or would you prefer I push the fork's branch as a real branch?

**Comment by ben-polinsky** [comment]
@MichaelBelousov I'll work on a fix now, but also might be quicker to push from a same repo branch. Up to you.

**Comment by MichaelBelousov** [comment]
> @MichaelBelousov I'll work on a fix now, but also might be quicker to push from a same repo branch. Up to you.

We can wait, thanks

**Comment by aruniverse** [comment]
> @MichaelBelousov I'll work on a fix now, but also might be quicker to push from a same repo branch. Up to you.

I think i would advocate for this; just because i havent seen a way to manually trigger the itwinjs builds from the fork

**Comment by ViliusRuskys** [comment]
Recreated the PR from a branch instead of a fork:
#5144

**Pull request closed without merging**
