### PR TITLE
@bentley/imodeljs-native 3.0.18

### PR DESCRIPTION
**Pull request by pmconne**

### CODE REVIEW

**Comment by pmconne** [comment]
@nick4598 @kabentley before I rummage around your changes, please feel free to push fix for removal/rename/refactor of DownloadV2Checkpoint.
```
src/workspace/CloudSqlite.ts:93:48 - error TS2339: Property 'DownloadV2Checkpoint' does not exist on type 'typeof IModelJsNative'.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            93     const downloader = new IModelHost.platform.DownloadV2Checkpoint({ ...db, ...props });
```

**Comment by pmconne** [comment]
@aruniverse @calebmshafer it appears that the addon package now uses type definitions from the version of core-common that are specified in its package.json instead of those specified by core-backend.
When did that change? It must have been relatively recently as previous addon builds did not exhibit these errors.

 Argument of type 'DynamicGraphicsRequest3dProps' is not assignable to parameter of type 'ElementGraphicsRequestProps'.                                                                                                                                                                                                                                         Type 'import("D:/j2/s/imodeljs/core/common/lib/cjs/tile/ElementGraphics").DynamicGraphicsRequest3dProps' is not assignable to type 'import("D:/j2/s/imodeljs/common/temp/node_modules/.pnpm/@itwin+core-common@3.0.0-extension.1_f2c3418fbeb77077b236020c30c9aae4/node_modules/@itwin/core-common/lib/cjs/tile/ElementGraphics").DynamicGraphicsRequest3dProps'.

**Comment by aruniverse** [comment]
> @aruniverse @calebmshafer it appears that the addon package now uses type definitions from the version of core-common that are specified in its package.json instead of those specified by core-backend. When did that change? It must have been relatively recently as previous addon builds did not exhibit these errors.
> 
> Argument of type 'DynamicGraphicsRequest3dProps' is not assignable to parameter of type 'ElementGraphicsRequestProps'. Type 'import("D:/j2/s/imodeljs/core/common/lib/cjs/tile/ElementGraphics").DynamicGraphicsRequest3dProps' is not assignable to type 'import("D:/j2/s/imodeljs/common/temp/node_modules/.pnpm/@iTwin+core-common@3.0.0-extension.1_f2c3418fbeb77077b236020c30c9aae4/node_modules/@itwin/core-common/lib/cjs/tile/ElementGraphics").DynamicGraphicsRequest3dProps'.

+ @wgoehrig 

I'm not too familiar with the native addon side (yet, id like to be one day) to be of much help here. But one thing that does stand out is it looks like it's pulling in an outdated ver of core coming from the extension pre-release we did, due to how we have the peer deps setup. 

Paulius mentioned pinning down peer deps in this thread, https://github.com/iTwin/itwinjs-core/pull/2741#discussion_r753154387, which might fix what you're seeing.

**Comment by nick4598** [comment]
> @nick4598 @kabentley before I rummage around your changes, please feel free to push fix for removal/rename/refactor of DownloadV2Checkpoint.
> 
> ```
> src/workspace/CloudSqlite.ts:93:48 - error TS2339: Property 'DownloadV2Checkpoint' does not exist on type 'typeof IModelJsNative'.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            93     const downloader = new IModelHost.platform.DownloadV2Checkpoint({ ...db, ...props });
> ```

Pushed the change.

**Comment by pmconne** [comment]
> I'm not too familiar with the native addon side (yet, id like to be one day) to be of much help here. But one thing that does stand out is it looks like it's pulling in an outdated ver of core coming from the extension pre-release we did, due to how we have the peer deps setup.
> 
> Paulius mentioned pinning down peer deps in this thread, [#2741 (comment)](https://github.com/iTwin/itwinjs-core/pull/2741#discussion_r753154387), which might fix what you're seeing.

I'll work around it for now by casting to `any` - one of those errors is caused by the definition of `TreeFlags` having been updated on the imodel02 branch, which the addon can't see until we publish a new core-common, which can't happen until this addon is published.

**Pull request merged**
