### PR TITLE
 @bentley/imodel-native 3.6.4

### PR DESCRIPTION
**Pull request by pmconne**
Also updated script to work on both macOS and linux @aruniverse fyi in case you run into same problem again elsewhere.

### CODE REVIEW

**Review by MichaelBelousov — APPROVED** [review]

**Comment by pmconne** [comment]
@types/yargs 17.0.19 => 17.0.20 made a breaking change.
```

--[ FAILURE: @itwin/workspace-editor ]-----------------------[ 4.39 seconds ]--

src/WorkspaceEditor.ts(604,7): error TS2554: Expected 2-6 arguments, but got 1.
src/WorkspaceEditor.ts(610,7): error TS2554: Expected 2-6 arguments, but got 1.
src/WorkspaceEditor.ts(616,7): error TS2554: Expected 2-6 arguments, but got 1.
src/WorkspaceEditor.ts(622,7): error TS2554: Expected 2-6 arguments, but got 1.
src/WorkspaceEditor.ts(628,7): error TS2554: Expected 2-6 arguments, but got 1.
src/WorkspaceEditor.ts(638,7): error TS2554: Expected 2-6 arguments, but got 1.
src/WorkspaceEditor.ts(643,7): error TS2554: Expected 2-6 arguments, but got 1.
src/WorkspaceEditor.ts(648,7): error TS2554: Expected 2-6 arguments, but got 1.
src/WorkspaceEditor.ts(653,7): error TS2554: Expected 2-6 arguments, but got 1.
src/WorkspaceEditor.ts(661,7): error TS2554: Expected 2-6 arguments, but got 1.
src/WorkspaceEditor.ts(666,7): error TS2554: Expected 2-6 arguments, but got 1.
src/WorkspaceEditor.ts(671,7): error TS2554: Expected 2-6 arguments, but got 1.
src/WorkspaceEditor.ts(679,7): error TS2554: Expected 2-6 arguments, but got 1.
src/WorkspaceEditor.ts(684,7): error TS2554: Expected 2-6 arguments, but got 1.
src/WorkspaceEditor.ts(689,7): error TS2554: Expected 2-6 arguments, but got 1.
src/WorkspaceEditor.ts(694,7): error TS2554: Expected 2-6 arguments, but got 1.
src/WorkspaceEditor.ts(699,7): error TS2554: Expected 2-6 arguments, but got 1.
src/WorkspaceEditor.ts(704,7): error TS2554: Expected 2-6 arguments, but got 1.
src/WorkspaceEditor.ts(709,7): error TS2554: Expected 2-6 arguments, but got 1.
src/WorkspaceEditor.ts(714,7): error TS2554: Expected 2-6 arguments, but got 1.
```

**Review by markschlosseratbentley — APPROVED** [review]

**Comment by pmconne** [comment]
> [revert massive lockfile changes](https://github.com/iTwin/itwinjs-core/pull/4942/commits/50c7064b2f5db15a33a2f84e4dfaf440bdafd108)

@arun why?

**Comment by pmconne** [comment]
core-backend integration tests failed one test then seg-faulted during CloudSqlite test.
```
  ChangedElements
    ✔ Create ChangedElements Cache and process changesets (1446ms)
    ✔ Create ChangedElements Cache and process changesets while rolling Db (876ms)
    1) Create ChangedElements Cache and process changesets while rolling Db without caching

  ChangeSummary
    ✔ Attach / Detach ChangeCache file to closed imodel (636ms)
    ✔ Extract ChangeSummaries (4261ms)
    ✔ Extract ChangeSummary for a model with no changesets (1978ms)
    ✔ Extract ChangeSummary for single changeset (2157ms)
    ✔ Extracting ChangeSummaries for a range of changesets (3900ms)
    ✔ Subsequent ChangeSummary extractions (3894ms)
    ✔ Query ChangeSummary content (4327ms)
    - Create ChangeSummaries for changes to parent elements
    - should be able to extract the last change summary right after applying a change set
    ✔ Detaching and reattaching change cache (3463ms)
    ✔ Create change summaries for all change sets (4042ms)
    ✔ Create change summaries for just the latest change set (2806ms)
    ✔ Create change summaries for an invalid range of change sets (677ms)

  CloudSqlite
Segmentation fault (core dumped)
Azurite Blob service is closing...
Azurite Blob service successfully closed
ERROR: "test:integration:core" exited with 139.
ERROR: "test:integration:azurite" exited with 1.
##[error]Bash exited with code '1'.
```

**Comment by pmconne** [comment]
@EarlinLutz @dassaf4 3 failing geometry-core tests
```
  3 failing

  1) ReOrientFacets
       isConvex:
     TypeError: cluster.at is not a function
      at Function.dihedralAngleSummary (src/polyface/PolyfaceQuery.ts:97:66)
      at Context.<anonymous> (src/test/polyface/PolyfaceQuery.test.ts:878:39)
      at processImmediate (internal/timers.js:464:21)

  2) ReOrientFacets
       isConvexWithBoundary:
     TypeError: cluster.at is not a function
      at Function.dihedralAngleSummary (src/polyface/PolyfaceQuery.ts:97:66)
      at Context.<anonymous> (src/test/polyface/PolyfaceQuery.test.ts:926:41)
      at processImmediate (internal/timers.js:464:21)

  3) ReOrientFacets
       isConvexWithAllPlanar:
     TypeError: cluster.at is not a function
      at Function.dihedralAngleSummary (src/polyface/PolyfaceQuery.ts:97:66)
      at Context.<anonymous> (src/test/polyface/PolyfaceQuery.test.ts:945:41)
      at processImmediate (internal/timers.js:464:21)
```

**Comment by pmconne** [comment]
The `at` method of `Array` is only supported in versions of Node >= 16. I am running 14, which we claim to support.
@calebmshafer I guess we're not testing against 14 in CI.
@dassaf4 @EarlinLutz I'll take a crack at adjusting your code.

**Comment by pmconne** [comment]
Seg-fault in CloudSqlite test is reproducible; ChangedElements test failure is not.

**Review by dassaf4 — APPROVED** [review]
Array.at removal approved. A bit of native syntax crept in. Thanks, @pmconne.

**Comment by aruniverse** [comment]
> @calebmshafer I guess we're not testing against 14 in CI? 

We have [regression testing setup](https://dev.azure.com/bentleycs/iModelTechnologies/_build?definitionId=4320) but guess no one is actually looking at this :/

**Comment by kabentley** [comment]
i will investigate the CloudSqlite test

**Comment by orgads** [comment]
> @types/yargs 17.0.19 => 17.0.20 made a [breaking change](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63694).

Reported https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/63990

Not sure if it's the same issue you face.

**Comment by kabentley** [comment]
https://github.com/iTwin/imodel-native/pull/121

**Pull request merged**
