### PR TITLE
@bentley/imodeljs-native 3.5.5

### PR DESCRIPTION
**Pull request by nick4598**

### CODE REVIEW

**Review by wgoehrig — APPROVED** [review]

**Comment by pmconne** [comment]
Why is this targeting imodel02 instead of master?

**Comment by nick4598** [comment]
> Why is this targeting imodel02 instead of master?

great question

**Review by pmconne — APPROVED** [review]

**Comment by pmconne** [comment]
@grigasp FYI tests appear to hang here.
```
==[ presentation-full-stack-tests ]==============================[ 47 of 77 ]==

Invoking: npm run -s test 
Backend PID: 2336


  Diagnostics
    ✔ includes diagnostics if request takes longer than minimum duration (269ms)
    ✔ doesn't include diagnostics if request takes less time than minimum duration (81ms)
    ✔ doesn't report request diagnostics if not requested when manager diagnostics requested (87ms)
    ✔ doesn't report manager diagnostics if not requested when request diagnostics requested (92ms)
    ✔ reports with only requested diagnostics (98ms)

  Learning Snippets
    Diagnostics
      ✔ gets backend per-request diagnostics (261ms)
      ✔ gets backend per-manager diagnostics (113ms)

  NativePlatform
    ✔ throws on closed imodel
    ✔ throws on empty options
    ✔ throws on empty request id
    ✔ throws on not handled request id

  PresentationManager
    Property value formatting
      ✔ formats property with default kind of quantity format when it doesn't have format for requested unit system (281ms)
      ✔ formats property using default format when it doesn't have format for requested unit system (139ms)
      ✔ formats property using provided format when it has provided format and default format for requested unit system (93ms)
    getElementProperties
      ✔ returns properties for some elements of class 'PhysicalObject (224ms)
    Cancel request
      ✔ cancels 'getNodes' request

  ReadWrite
    Handling read-write operations
Error | BeSQLite | Busy retry failed, returning BE_SQLITE_BUSY error. 
      1) handles schema import during nodes request
```

**Comment by grigasp** [comment]
> @grigasp FYI tests appear to hang here.
> 
> ```
> ==[ presentation-full-stack-tests ]==============================[ 47 of 77 ]==
> 
> Invoking: npm run -s test 
> Backend PID: 2336
> 
> 
>   Diagnostics
>     ✔ includes diagnostics if request takes longer than minimum duration (269ms)
>     ✔ doesn't include diagnostics if request takes less time than minimum duration (81ms)
>     ✔ doesn't report request diagnostics if not requested when manager diagnostics requested (87ms)
>     ✔ doesn't report manager diagnostics if not requested when request diagnostics requested (92ms)
>     ✔ reports with only requested diagnostics (98ms)
> 
>   Learning Snippets
>     Diagnostics
>       ✔ gets backend per-request diagnostics (261ms)
>       ✔ gets backend per-manager diagnostics (113ms)
> 
>   NativePlatform
>     ✔ throws on closed imodel
>     ✔ throws on empty options
>     ✔ throws on empty request id
>     ✔ throws on not handled request id
> 
>   PresentationManager
>     Property value formatting
>       ✔ formats property with default kind of quantity format when it doesn't have format for requested unit system (281ms)
>       ✔ formats property using default format when it doesn't have format for requested unit system (139ms)
>       ✔ formats property using provided format when it has provided format and default format for requested unit system (93ms)
>     getElementProperties
>       ✔ returns properties for some elements of class 'PhysicalObject (224ms)
>     Cancel request
>       ✔ cancels 'getNodes' request
> 
>   ReadWrite
>     Handling read-write operations
> Error | BeSQLite | Busy retry failed, returning BE_SQLITE_BUSY error. 
>       1) handles schema import during nodes request
> ```

Can't repro locally.
- did you get the hang locally?
- debug addon build?
- windows?
- flaky?

**Comment by pmconne** [comment]
@grigasp It occurred once, during CI job. I think on Linux but might have been Windows. No repro on rerun.

**Comment by grigasp** [comment]
> @grigasp It occurred once, during CI job. I think on Linux but might have been Windows. No repro on rerun.

Thanks. Filed an issue: https://github.com/iTwin/itwinjs-backlog/issues/488.

**Pull request merged**
