### PR TITLE
Omit terrain skirts if clip mask is transparent

### PR DESCRIPTION
**Pull request by markschlosseratbentley**
Otherwise they show through the transparent portions, looking ugly.
Note: this does **not** address [this defect](https://bentleycs.visualstudio.com/iModelTechnologies/_workitems/edit/646372) which was initially misreported. That defect is about applying transparency overrides to elements used to produce the mask; we don't have an efficient way to detect and deal with that.

### CODE REVIEW

**Review by Ellord207 — APPROVED** [review]
I was not able to produce the original issue again.

I tested by running the following code, which was taken from the [sample showcase](https://github.com/imodeljs/frontend-sample-showcase/blob/d175770aafd1291ff91197dd36325b0a0acc830f/src/api/viewSetup.ts#L98).
```
        const getModelIds = async (iModel: IModelConnection, ...modelNames: string[]): Promise<Id64Set> => {
          const ids = new Set<string>();
          if (!iModel.isClosed) {
            const query = `SELECT ECInstanceId FROM Bis:PhysicalPartition${modelNames.length > 0 ? ` WHERE codeValue IN ('${modelNames.join("','")}')` : ""}`;
            for await (const row of iModel.query(query)) {
              ids.add(row.id);
            }
          }
          return ids;
        };
        const imodel = this.viewport.iModel;
        if (this.viewport.view.isSpatialView() && imodel.name === "Stadium") {
          const displayStyle = this.viewport.view.displayStyle;
          const modelsForMasking = await getModelIds(imodel, "SS_MasterLandscape.dgn, LandscapeModel");
          displayStyle.changeBackgroundMapProps({
            planarClipMask: PlanarClipMaskSettings.createForModels(modelsForMasking).toJSON(),
            // transparency: 0.01, // Temporary fix due to how the planar clip and transparency interact.
          });
          const excludedModelIds = await getModelIds(imodel,
            "SS_Master",
            "SS_Master_Structural.dgn, 3D Metric Design",
            "LandscapeDetails.dgn, 3D Metric Design",
            "Stencil Model-4-LandscapeModel, SS_MasterLandscape, SS_MasterLandscape.dgn, Road_Marking",
          );
          excludedModelIds.forEach((id) => (this.viewport.view as SpatialViewState).modelSelector.dropModels(id));
        }
```

I had inserted this into the viewer toolbar.

I was able to obverse the clipping plane applied correctly, without seeing tile skirts cross the model.

**Comment by markschlosseratbentley** [comment]
> I was not able to produce the original issue on this branch.
> 
> I tested by running the following code, which was taken from the [sample showcase](https://github.com/imodeljs/frontend-sample-showcase/blob/d175770aafd1291ff91197dd36325b0a0acc830f/src/api/viewSetup.ts#L98).
> 
> ```
>         const getModelIds = async (iModel: IModelConnection, ...modelNames: string[]): Promise<Id64Set> => {
>           const ids = new Set<string>();
>           if (!iModel.isClosed) {
>             const query = `SELECT ECInstanceId FROM Bis:PhysicalPartition${modelNames.length > 0 ? ` WHERE codeValue IN ('${modelNames.join("','")}')` : ""}`;
>             for await (const row of iModel.query(query)) {
>               ids.add(row.id);
>             }
>           }
>           return ids;
>         };
>         const imodel = this.viewport.iModel;
>         if (this.viewport.view.isSpatialView() && imodel.name === "Stadium") {
>           const displayStyle = this.viewport.view.displayStyle;
>           const modelsForMasking = await getModelIds(imodel, "SS_MasterLandscape.dgn, LandscapeModel");
>           displayStyle.changeBackgroundMapProps({
>             planarClipMask: PlanarClipMaskSettings.createForModels(modelsForMasking).toJSON(),
>             // transparency: 0.01, // Temporary fix due to how the planar clip and transparency interact.
>           });
>           const excludedModelIds = await getModelIds(imodel,
>             "SS_Master",
>             "SS_Master_Structural.dgn, 3D Metric Design",
>             "LandscapeDetails.dgn, 3D Metric Design",
>             "Stencil Model-4-LandscapeModel, SS_MasterLandscape, SS_MasterLandscape.dgn, Road_Marking",
>           );
>           excludedModelIds.forEach((id) => (this.viewport.view as SpatialViewState).modelSelector.dropModels(id));
>         }
> ```
> 
> I had inserted this into the viewer toolbar.
> 
> I was able to obverse the masking applied correctly, without seeing tile skirts cross the model.

@Ellord207 
Nathan - were you able to reproduce the issue without my changes here?

**Review by Ellord207 — CHANGES_REQUESTED** [review]
After attempting to reproduce on master, I was incorrectly testing.

After attempting again, I am able to reproduce the original issue on this branch.

**Comment by pmconne** [comment]
> After attempting again, I am able to reproduce the original issue on this branch.

Supply repro steps please.

**Comment by Ellord207** [comment]
> Supply repro steps please.

I gave mark a link to a share with the code and iModel I was able to reproduce this on.  I will do the same for you.

The bug is visible when a mesh is affected by a planar clip mask, and a feature appearance with a transparency (such as not being selected by emphasize elements) and the background map is enabled with depth buffer.

I selected an iModel with a large, flat mesh at ground level (Stadium).  Applied a planar clip mask using the previously mentioned mesh, and enabled the background map with depth buffer.  Then added a feature override provider that adds a transparency to all elements.

**Comment by markschlosseratbentley** [comment]
@Ellord207 

I dug into your sample code in order to see why this PR is not working.  I initially thought I needed to check if a planarClipMask was being applied which had transparency, and disable map skirts in that case.

However, your code applies a planarClipMask and then applies transparency using feature overrides.

1) If no planarClipMask is applied, and only feature override transparency is applied, skirts are disabled properly.
2) Once a planarClipMask is combined with feature override transparency, skirts are not disabled.

I am having some trouble figuring out where to check for this combination in `MapTileTreeReference::treeOwner()`

@pmconne @RBBentley Do either of you have suggestions how to get that information in `MapTileTreeReference:.treeOwner()`?

**Comment by pmconne** [comment]
@markschlosseratbentley in general we cannot determine if the viewport's feature overrides are going to make the mask geometry transparent.

@Ellord207 why are you applying transparency using FeatureOverrideProvider instead of PlanarClipMaskSettings.transparency?

**Comment by pmconne** [comment]
@markschlosseratbentley as far as I can tell based on commented-out code, @Ellord207 was using feature overrides as a workaround for the skirts displaying when planar clip mask specified transparency. You have fixed that. I think this PR is ready (after `rush change` etc).

**Comment by markschlosseratbentley** [comment]
> @markschlosseratbentley as far as I can tell based on commented-out code, @Ellord207 was using feature overrides as a workaround for the skirts displaying when planar clip mask specified transparency. You have fixed that. I think this PR is ready (after `rush change` etc).

@pmconne After speaking to @Ellord207 yesterday, I believe his workaround was actually the commented-out portion in the background map props, to make the map tile tree realize transparency was affecting it:

```
displayStyle.changeBackgroundMapProps({
            planarClipMask: PlanarClipMaskSettings.createForModels(modelsForMasking).toJSON(),
            // transparency: 0.01, // Temporary fix due to how the planar clip and transparency interact.
          });
```

I believe the original problem he faced was setting transparency via feature overrides and applying a planarClipMask still resulted in skirts rendering, so he had to apply a very small transparency to the background map props to disable them.
@Ellord207 is this correct?

**Comment by Ellord207** [comment]
> @Ellord207 why are you applying transparency using FeatureOverrideProvider instead of PlanarClipMaskSettings.transparency?

I'm emulating how I originally caused this bug, by enabling Emphasize selected elements after applying a planar clip mask.  besides, PlanarClipMaskSettings.transparency affects the clipped geometry, in this case, the map.  Not the elements of the model.
 By setting the background map transparency, as seen in the commented out line in the changeBackgroundMapProps call, that is my work around to the skirts issue.

**Comment by Ellord207** [comment]
> I believe the original problem he faced was setting transparency via feature overrides and applying a planarClipMask still resulted in skirts rendering, so he had to apply a very small transparency to the background map props to disable them.
> @Ellord207 is this correct?

Yes, this is correct.

**Comment by pmconne** [comment]
@Ellord207 Ok, as I stated: "in general we cannot determine if the viewport's feature overrides are going to make (some, all, or none of) the mask geometry transparent."

**Comment by Ellord207** [comment]
> @Ellord207 Ok, as I stated: "in general we cannot determine if the viewport's feature overrides are going to make (some, all, or none of) the mask geometry transparent."

@pmconne, do you think a comment in the planar clip masking for the background map API explaining the bug, and its workaround would be appropriate?

**Comment by pmconne** [comment]
@Ellord207 I don't know. @markschlosseratbentley has solved the bug as described in the initial defect. Your bug is a different one.

**Comment by Ellord207** [comment]
> @Ellord207 I don't know. @markschlosseratbentley has solved the bug as described in the initial defect. Your bug is a different one.

I know nothing about the bug in the defect and have never seen it.

The one I reported and demo originally was not the one in the defect.  I didn't read it carefully when it was created, assuming I had been understood.  I will not make that mistake again.

**Comment by pmconne** [comment]
@Mergifyio update

**Review by pmconne — APPROVED** [review]

**Review by RBBentley — APPROVED** [review]

**Comment by pmconne** [comment]
Awaiting completion of ImageTests run.

**Pull request merged**
