### PR TITLE
Reproject reality tiles

### LINKED ISSUE #4036: Adjust distant reality data tiles to match earth curvature
For very large reality datasets than span many kilometers, the data will vertically shift the farther the data is from the reality data's center.

Some numbers:
- 2.3 kilometers away from center; shift can be 0.44 meters
- 13.6 kilometers away from center; shift can be 13.6 meters

We use an EcefLocation computed at the center of the reality data.  This represents a plane which approximates the surface of the earth at the center of the reality data.  The farther from that location we get, the more it will shift.

To solve this, each tile should reproject itself based on a nearer EcefLocation, or based on how far it is from the nearest EcefLocation.

### PR DESCRIPTION
**Pull request by pmconne**
Fixes #4036.

Previously we would only reproject reality tiles if they had a `RealityTileRegion` defined, which effectively meant only if they originated from the OpenStreetMap Buildings tileset.
If we don't reproject, then points in the reality model shift further from the surface of the Earth as distance from the center of the iModel's ECEF location increases.

Now, we reproject all reality tiles onto the surface of the Earth using the center of the tile's range.
This adds some extra work:
- We must perform an asynchronous query per group of child tiles to do the reprojection; and
- We must push a transform when drawing each tile.

If this measurably impacts user experience, we could try to come up with a heuristic to determine whether the loss of accuracy is large enough to warrant doing this extra work, on a per-tile or per-reality model basis (e.g., distance from iModel's ECEF center).

TODO
- [x] Analyze ImageTests results
- [x] Figure out what to do about ImageTests differences

### CODE REVIEW

**Comment by pmconne** [comment]
ImageTests shows 80 major differences against previous run.
- Helsinki: definitely fixed - control points now align
- Big E** point cloud. Delaware Waterfront, Redmond - vertical shift - all views have ground bias applied - perhaps bias was meant to counteract ECEF inaccuracies? Big E** definitely looks worse -- elevated too high above ground.
- Philadelphia - vertical shift - no bias applied. Most views look arguably improved (less clipping of reality model into map - especially StreetLevel)
- quarry, NasaLaunchPad, LanscapeDemo - slight vertical shift.

**Comment by AlainRobertAtBentley** [comment]
The Helsinki results indicate that this fixes positional issues. Concerning the other different datasets it is not possible to determine if it is an amelioration or not based solely on the ImageTest results. Can you remind how to obtain the datasets so we can analyze them in viewers and apps?

**Comment by pmconne** [comment]
@AlainRobertAtBentley See https://github.com/iTwin/itwinjs-backlog/issues/443

**Comment by pmconne** [comment]
The BigE** point cloud is no longer in use by the user and almost certainly it and/or its iModel's GCS are still wrong.

**Review by markschlosseratbentley — APPROVED** [review]

**Comment by pmconne** [comment]
All attempts to test against user's data in PROD failed in various disappointing ways.

**Comment by pmconne** [comment]
@Mergifyio backport release/3.4.x

**Pull request merged**
