### PR TITLE
imodeljs-native@4.1.13

### PR DESCRIPTION
**Pull request by DanRod1999**

### CODE REVIEW

**Review by tcobbs-bentley — APPROVED** [review]

**Review by aruniverse — COMMENTED** [review]
why did you run extract api??

**Review by pmconne — APPROVED** [review]
Probs revert extract-api. api-extractor can never make up its mind what order it wants things in.

**Comment by DanRod1999** [comment]
> why did you run extract api??

its part of our [instructions](https://dev.azure.com/bentleycs/iModelTechnologies/_wiki/wikis/iModelTechnologies.wiki?anchor=integrating-a-patch-addon-into-a-release-branch&pagePath=/iModel%20Technology/imodel%252Dnative/Creating%20a%20new%20imodel%252Dnative%20addon/Integrating%20a%20new%20imodel%252Dnative%20addon)
can i remove it?

**Comment by pmconne** [comment]
> > why did you run extract api??
> 
> its part of our [instructions](https://dev.azure.com/bentleycs/iModelTechnologies/_wiki/wikis/iModelTechnologies.wiki?anchor=integrating-a-patch-addon-into-a-release-branch&pagePath=/iModel%20Technology/imodel%252Dnative/Creating%20a%20new%20imodel%252Dnative%20addon/Integrating%20a%20new%20imodel%252Dnative%20addon) can i remove it?

If PR validation is working, everything from `rush build` to `rush change` can be removed.

**Review by aruniverse — APPROVED** [review]

**Pull request merged**
