### PR TITLE
Add simple UI for picking hub iModels

### PR DESCRIPTION
**Pull request by tcobbs-bentley**
Note: I split DtaConfiguration into four subtypes so that I could create strongly typed accessor functions to access fields of three different types in the app's main configuration object. This let me get rid of my code where I passed that configuration object to various points in the source that didn't otherwise have access to it.

So, for example, `getConfigurationString` has a parameter of `key: keyof DtaStringConfiguration`, and since `DtaStringConfiguration` only contains string configuration values, its return value is can be `string | undefined` while remaining strongly typed. If DtaConfiguration weren't split, then the parameter would have to be `key: keyof DtaConfiguration`, and that would rely on the user only using a key that corresponds to a string value.

### CODE REVIEW

**Comment by tcobbs-bentley** [comment]
@calebmshafer Here is the simple hub iModel picking UI. If you're OK with this (possibly/probably after review comments and updates), then once this goes through, I will remove test OIDC and service auth from DTA as a separate PR.

**Comment by tcobbs-bentley** [comment]
@aruniverse Caleb said that you would be better to look at this. Can you take a look?

**Review by aruniverse — APPROVED** [review]
changes look fine to me, did not get to run since my machine is in a bad state atm

@markschlosseratbentley can you verify this doesnt break any existing dta workflows?

**Review by markschlosseratbentley — APPROVED** [review]
I tested these changes on display-test-app (both desktop and iOS).  The old functionality to open iModels and the new hub download functionality both work.

**Review by tsouthen — APPROVED** [review]

**Review by toddsouthenbentley — APPROVED** [review]

**Pull request merged**
