### PR TITLE
Entity is not an EntityProps.

### PR DESCRIPTION
**Pull request by pmconne**
Far too many bugs result from people passing an instance of a subclass of Entity to functions expecting an EntityProps.
In most cases, while those two base types are compatible the types derived from each (e.g., SubCategory and SubCategoryProps) are not compatible.
Functions like `insertElement` and `updateElement` call `toJSON` if the input is an Element instead of an ElementProps. Bugs ensue if subclasses fail to implement toJSON.

Add a discriminator field `isInstanceOfEntity` to Entity and EntityProps, with incompatible types (`true` vs `never | undefined`).
Adjust all code that was previously relying on type compatibility to explicitly call `toJSON`.

This is a breaking API change affecting only backend code. It is extremely useful for detecting bugs in existing code.

### CODE REVIEW

**Comment by pmconne** [comment]
@calebmshafer This is a breaking API change. It affects only backend code that detects and prevents a broad class of bugs in existing code. @kabentley and I would like it included in 3.0. Do you object?

**Comment by pmconne** [comment]
Force-merging; everything passed except macOS which is hung in ECSqlStatement core-backend tests.

**Comment by pmconne** [comment]
@Mergifyio backport release/3.0.x

**Comment by calebmshafer** [comment]
> This is a breaking API change affecting only backend code. It is extremely useful for detecting bugs in existing code.

@pmconne just saw this now... I don't like adding another breaking change to the list as many people have already started testing out the RC we put out last week which was supposed to include the final set of breaking changes.

This will effect any editing apps, transformers, and connectors that have already started their upgrade process and we'll need to announce that we have changed it.

This has to be the last change we make that breaks the API, especially since this was never on any list. Any future breaking changes will need to be considered for 4.0.

**Pull request merged**
