### PR TITLE
Increase amount of retries when downloading v2 checkpoints and sleep between retries. 

### PR DESCRIPTION
**Pull request by nick4598**
Relevant discussion post: https://github.com/iTwin/itwinjs-core/discussions/3897

Although our previous fix to increase the number of retries between downloads seems to have lowered the frequency of the problem, it seems to still exist. 

It may be better to expose a way for the user to increase the number of retries from the BridgeRunner, but I'm not sure if its worth the time or not.

I also figured since we are dealing with a transient error, it may be beneficial for us to sleep in between retries to give time for the connectivity issues to pass.

Let me know your thoughts

### CODE REVIEW

**Comment by pmconne** [comment]
If you go this route (it's a temp workaround until we have a better solution right?) consider using [exponential backoff](https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/).

**Comment by nick4598** [comment]
> If you go this route (it's a temp workaround until we have a better solution right?) consider using [exponential backoff](https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/).

Yep, temp workaround. 

I took the "full jitter" approach from [here](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/)

Not sure if we need jitter in our case or not though.

**Review by pmconne — APPROVED** [review]

**Comment by kabentley** [comment]
@nick4598 What causes this problem? Do we know? 

Also, why is this guy downloading his iModel repeatedly? This should be a one-shot thing per computer. What does he seem to download every "sync"?

**Comment by nick4598** [comment]
> @nick4598 What causes this problem? Do we know?
> 
> Also, why is this guy downloading his iModel repeatedly? This should be a one-shot thing per computer. What does he seem to download every "sync"?

I was able to reproduce this error message with the daemon by turning off azurite while running a test (probably downloading or uploading blocks I believe). So I assume its an inability to communicate or get a response from azure , but I don't know for sure. The error message comes from curl.

Thats a good question, I don't know. Wouldn't he have to redownload the new checkpoint/ briefcase if there is one before he syncs? Or at the least some new blocks

**Comment by kabentley** [comment]
> I was able to reproduce this error message with the daemon by turning off azurite while running a test (probably downloading or uploading blocks I believe). So I assume its an inability to communicate or get a response from azure , but I don't know for sure. The error message comes from curl.

OK, but why? And why does retrying work? Is it taking so long his token expires?

> Thats a good question, I don't know. Wouldn't he have to redownload the new checkpoint/ briefcase if there is one before he syncs? Or at the least some new blocks

He should pull and apply changesets. That's what "briefcases" are all about. It's like re-cloning a git repository instead of pulling.

**Comment by nick4598** [comment]
> OK, but why? And why does retrying work? Is it taking so long his token expires?

I don't have a good answer. If we had curl verbose logging on at the time of the error, its possible we may get some more detailed information, since there are quite a few places where curl can return with a CURLE_RECV_ERROR (which translates to the error we see, "failure when receiving data from the peer"). Theres definitely some drawbacks to having that on at all for users though..

> 
> He should pull and apply changesets. That's what "briefcases" are all about. It's like re-cloning a git repository instead of pulling.

It seems like the imodel-bridge code uses BriefcaseManager.downloadBriefcase which throws an error if the file already exists on disk. Maybe that is the reason he appears to be re-cloning each time? Is that the right function to be using?

**Comment by kabentley** [comment]
>  Is that the right function to be using?

That gets a new briefcase. You mean that call that for every run? @swwilson-bsi @jffmarker?

**Comment by nick4598** [comment]
For more context, we are referencing this discussion: https://github.com/iTwin/itwinjs-core/discussions/3897

The user posted a snippet of his code in that thread.

**Comment by jffmarker** [comment]
> > Is that the right function to be using?
> 
> That gets a new briefcase. You mean that call that for every run? @swwilson-bsi @jffmarker?

Skimming the 2.x code, the only `BriefcaseManager` call is to `downloadBriefcase` (we can use an existing briefcase ID if provided). In cloud environments, we start with a clean VM each job, so yes, each job has to get a new briefcase on disk.
@jchick-bentley @swwilson-bsi

**Pull request merged**
