### PR TITLE
fix: Updated CSS variables for desktop toolbar width/height to 40px for square icons

### PR DESCRIPTION
**Pull request by cortneysmithbentley**
Changed width and height variables for the toolbar to be 40px, which matches the toolbar items and will create 1:1 square icon sizes.

### CODE REVIEW

**Review by NancyMcCallB — APPROVED** [review]

**Comment by pmconne** [comment]
@cortneysmithbentley is this a backport of a previous PR? I couldn't find one.

**Comment by NancyMcCallB** [comment]
> @cortneysmithbentley is this a backport of a previous PR? I couldn't find one.

I didn't notice that she was trying to commit to the 3.3 branch.
@cortneysmithbentley , you'll have to make the change on master and then backport it.

**Comment by pmconne** [comment]
@Mergifyio backport master

**Comment by cortneysmithbentley** [comment]
Oh I'm sorry @pmconne & @NancyMcCallB  -- I didn't see that I was tagged in those comments, I just saw that it was approved so I merged it. I will commit any future changes to master.

**Pull request merged**
