### PR TITLE
Fix assertion on valid case in IModelExporter.exportElement.

### PR DESCRIPTION
**Pull request by GytisCepk**
Scenario:
Passing object containing an `id` property to `mapId64` function.

Problem:
`isId64String` is executed first and `assert(Id64.isValidId64(arg)` fires an error due to `arg` not being a string.

### CODE REVIEW

**Review by GerardasB — APPROVED** [review]

**Review by GerardasB — CHANGES_REQUESTED** [review]
We should get rid of that assertion in a type-guard and just return `false` instead..

**Review by GerardasB — APPROVED** [review]

**Comment by MichaelBelousov** [comment]
> We should get rid of that assertion in a type-guard and just return `false` instead..

I'm not actually sure I agree with this. It's a more expensive check and the `assert` only happens with the NODE_ENV environment variable set to `development` while building the typescript. Definitely the order was incorrect, but the assert was meant to catch the assumption that the programmer only calls `mapId64` with Id strings from the imodel, not necessarily allow mapping of any strings.

How did you run into this assert @GytisCepk . I'll  be able to check all callsites in a bit. The assumption I'm mentioning should probably be added to a `@note` in the `mapId64` jsdoc comment

**Comment by GytisCepk** [comment]
> How did you run into this assert @GytisCepk . I'll be able to check all callsites in a bit. The assumption I'm mentioning should probably be added to a `@note` in the `mapId64` jsdoc comment

Assertion fails when calling `TemplateModelCloner.placeTemplate3d`. Example of `idContainer` value passed to `mapId64` (this causes assert to throw an error):
`RelatedElement {id: '0x17e', relClassName: 'BisCore:ElementOwnsChildElements'}`.

Ping me directly and I'll send a call stack or steps to reproduce.

**Comment by MichaelBelousov** [comment]
> Assertion fails when calling TemplateModelCloner.placeTemplate3d. Example of idContainer value passed to mapId64 (this causes assert to throw an error):

Really this is my bad for adding an assert and not building with NODE_ENV=development... I actually don't know of anyone who does but maybe I added this before I knew that `assert` only occurred in debug builds? I believe we should keep the assert but move it after the test, and return the test result after the assert.

**Comment by GytisCepk** [comment]
> I'm not actually sure I agree with this. It's a much more expensive check (i should check how expensive but the transformer does this a lot) and the `assert` only happens with the NODE_ENV environment variable set to `development` while building the typescript. Definitely the order was incorrect, but the assert was meant to catch the assumption that the programmer only calls `mapId64` with Id strings from the imodel, not necessarily allow mapping of any strings.

I'm might be missing something, but I'm not sure how `assert` helps us here. If `Id64.isValidId64` is the expensive operation, it will still be executed in non-development environments. Only difference is that `Id64.isValidId64` result will not be evaluated.

Something like this would probably work:
`assert(() => Id64.isValidId64(arg))`

**Comment by MichaelBelousov** [comment]
You're completely right, I managed to use it as if it were a macro... so it has been running on all this time. Let me check locally why the tests don't run into this when exporting schemas with nav props.

**Comment by MichaelBelousov** [comment]
so the result should look like:
```typescript
const isId64String = (arg: any): arg is Id64String => {
  const isStr = typeof arg === "string";
  assert(() => !isStr || Id64.isValidId64(arg));
  return isStr;
};

**Pull request merged**
