### PR TITLE
Upgrade to webpack 5.97.1

### PR DESCRIPTION
**Pull request by pmconne**
@mathieu-lemuzic wants to use `dynamicImportInWorker` introduced in https://github.com/webpack/webpack/pull/17281.
Anyway, we're out of date.

### CODE REVIEW

**Comment by pmconne** [comment]
@khanaffan looks like flaky test (passed on Linux, failed on Mac)
```
  1) Merge conflict & locking
       pull/merge causing update conflict - update causing local changes (with no lock):
     Error: Failed to throw error with message: "UPDATE/DELETE before value do not match with one in db or CASCADE action was triggered."
      at assertThrowsAsync (src/test/standalone/MergeConflict.test.ts:49:9)
      at async Context.<anonymous> (src/test/standalone/MergeConflict.test.ts:229:5)
```

**Comment by pmconne** [comment]
Failed on Windows, passed on Mac and Linux:
```
9 passing (8s)
13 failing
1) OptionalDependenciesPlugin
     should work without optional dependencies:
    AssertionError: expected value to match snapshot OptionalDependenciesPlugin should work without optional dependencies 1
    + expected - actual
     "(() => {
     var exports = {};
    -exports.id = 792;
    -exports.ids = [792];
    +exports.id = 179;
    +exports.ids = [179];
     exports.modules = {
     
     /***/ "./lib/test/assets/optional-dependencies-plugin-test/node_modules/foo/bar.js":
     /***/ (() => {
    
    at Context.<anonymous> (lib\test\OptionalDependenciesPlugin.test.js:28:94)
2) OptionalDependenciesPlugin
     should ignore optional dependency in try/catch:
    AssertionError: expected value to match snapshot OptionalDependenciesPlugin should ignore optional dependency in try/catch 1
    + expected - actual
     "(() => {
     var exports = {};
    -exports.id = 792;
    -exports.ids = [792];
    +exports.id = 179;
    +exports.ids = [179];
     exports.modules = {
     
     /***/ "./lib/test/assets/optional-dependencies-plugin-test/node_modules/foo/index.js":
     /***/ (() => {
    
    at Context.<anonymous> (lib\test\OptionalDependenciesPlugin.test.js:38:94)
3) OptionalDependenciesPlugin
     should ignore critical dependency:
    AssertionError: expected value to match snapshot OptionalDependenciesPlugin should ignore critical dependency 1
    + expected - actual
     "(() => {
     var exports = {};
    -exports.id = 792;
    -exports.ids = [792];
    +exports.id = 179;
    +exports.ids = [179];
     exports.modules = {
     
     /***/ "./lib/test/assets/optional-dependencies-plugin-test/node_modules/foo/index.js":
     /***/ (() => {
    
    at Context.<anonymous> (lib\test\OptionalDependenciesPlugin.test.js:48:94)
4) OptionalDependenciesPlugin
     should ignore non-call use of require:
    AssertionError: expected value to match snapshot OptionalDependenciesPlugin should ignore non-call use of require 1
    + expected - actual
     "(() => {
     var exports = {};
    -exports.id = 792;
    -exports.ids = [792];
    +exports.id = 179;
    +exports.ids = [179];
     exports.modules = {
     
     /***/ "./lib/test/assets/optional-dependencies-plugin-test/node_modules/foo/index.js":
     /***/ (() => {
    
    at Context.<anonymous> (lib\test\OptionalDependenciesPlugin.test.js:58:94)
5) RequireMagicCommentsPlugin
     should transform requires with comment via custom handler:
    AssertionError: expected value to match snapshot RequireMagicCommentsPlugin should transform requires with comment via custom handler 1
    + expected - actual
     "(() => {
     var exports = {};
    -exports.id = 792;
    -exports.ids = [792];
    +exports.id = 179;
    +exports.ids = [179];
     exports.modules = {
     
     /***/ "./lib/test/assets/require-magic-comments-plugin-test/node_modules/bar/index.js":
     /***/ (() => {
    
    at Context.<anonymous> (lib\test\RequireMagicCommentsPlugin.test.js:30:94)
6) RequireMagicCommentsPlugin
     should work with external comments and addExternalPrefix handler:
    AssertionError: expected value to match snapshot RequireMagicCommentsPlugin should work with external comments and addExternalPrefix handler 1
    + expected - actual
     "(() => {
     var exports = {};
    -exports.id = 792;
    -exports.ids = [792];
    +exports.id = 179;
    +exports.ids = [179];
     exports.modules = {
     
     /***/ "./lib/test/assets/require-magic-comments-plugin-test/test.js":
     /***/ ((__unused_webpack_module, __unused_webpack_exports, __webpack_require__) => {
    
    at Context.<anonymous> (lib\test\RequireMagicCommentsPlugin.test.js:40:94)
7) RequireMagicCommentsPlugin
     should work with external comments and resolve not converted:
    AssertionError: expected value to match snapshot RequireMagicCommentsPlugin should work with external comments and resolve not converted 1
    + expected - actual
     "(() => {
     var exports = {};
    -exports.id = 792;
    -exports.ids = [792];
    +exports.id = 179;
    +exports.ids = [179];
     exports.modules = {
     
     /***/ "./lib/test/assets/require-magic-comments-plugin-test/node_modules/bar/index.js":
     /***/ (() => {
    
    at Context.<anonymous> (lib\test\RequireMagicCommentsPlugin.test.js:51:94)
8) RequireMagicCommentsPlugin
     should work with external comments and resolve converted:
    AssertionError: expected value to match snapshot RequireMagicCommentsPlugin should work with external comments and resolve converted 1
    + expected - actual
     "(() => {
     var exports = {};
    -exports.id = 792;
    -exports.ids = [792];
    +exports.id = 179;
    +exports.ids = [179];
     exports.modules = {
     
     /***/ "./lib/test/assets/require-magic-comments-plugin-test/node_modules/bar/index.js":
     /***/ (() => {
    
    at Context.<anonymous> (lib\test\RequireMagicCommentsPlugin.test.js:63:94)
9) RequireMagicCommentsPlugin
     should work with external comments with resolve not converted and addExternalPrefix handler:
    AssertionError: expected value to match snapshot RequireMagicCommentsPlugin should work with external comments with resolve not converted and addExternalPrefix handler 1
    + expected - actual
     "(() => {
     var exports = {};
    -exports.id = 792;
    -exports.ids = [792];
    +exports.id = 179;
    +exports.ids = [179];
     exports.modules = {
     
     /***/ "./lib/test/assets/require-magic-comments-plugin-test/test.js":
     /***/ (() => {
    
    at Context.<anonymous> (lib\test\RequireMagicCommentsPlugin.test.js:73:94)
10) RequireMagicCommentsPlugin
     should work with external comments with resolve converted and addExternalPrefix handler:
    AssertionError: expected value to match snapshot RequireMagicCommentsPlugin should work with external comments with resolve converted and addExternalPrefix handler 1
    + expected - actual
     "(() => {
     var exports = {};
    -exports.id = 792;
    -exports.ids = [792];
    +exports.id = 179;
    +exports.ids = [179];
     exports.modules = {
     
     /***/ "./lib/test/assets/require-magic-comments-plugin-test/test.js":
     /***/ ((__unused_webpack_module, __unused_webpack_exports, __webpack_require__) => {
    
    at Context.<anonymous> (lib\test\RequireMagicCommentsPlugin.test.js:84:94)
11) RequireMagicCommentsPlugin
     should work with copyfile comments and addCopyFileSuffix handler:
    AssertionError: expected value to match snapshot RequireMagicCommentsPlugin should work with copyfile comments and addCopyFileSuffix handler 1
    + expected - actual
     "(() => {
     var exports = {};
    -exports.id = 792;
    -exports.ids = [792];
    +exports.id = 179;
    +exports.ids = [179];
     exports.modules = {
     
     /***/ "./lib/test/assets/require-magic-comments-plugin-test/bar.txt?BeWebpack-COPYFILE}":
     /***/ ((module, __unused_webpack_exports, __webpack_require__) => {
    
    at Context.<anonymous> (lib\test\RequireMagicCommentsPlugin.test.js:95:114)
12) RequireMagicCommentsPlugin
     should work with copyfile comments, addCopyFileSuffix, and resolve converted:
    AssertionError: expected value to match snapshot RequireMagicCommentsPlugin should work with copyfile comments, addCopyFileSuffix, and resolve converted 1
    + expected - actual
     "(() => {
     var exports = {};
    -exports.id = 792;
    -exports.ids = [792];
    +exports.id = 179;
    +exports.ids = [179];
     exports.modules = {
     
     /***/ "./lib/test/assets/require-magic-comments-plugin-test/bar.txt?BeWebpack-COPYFILE}":
     /***/ ((module, __unused_webpack_exports, __webpack_require__) => {
    
    at Context.<anonymous> (lib\test\RequireMagicCommentsPlugin.test.js:108:114)
13) RequireMagicCommentsPlugin
     should work with copyfile comments, addCopyFileSuffix, and resolve not converted:
    AssertionError: expected value to match snapshot RequireMagicCommentsPlugin should work with copyfile comments, addCopyFileSuffix, and resolve not converted 1
    + expected - actual
     "(() => {
     var exports = {};
    -exports.id = 792;
    -exports.ids = [792];
    +exports.id = 179;
    +exports.ids = [179];
     exports.modules = {
     
     /***/ "./lib/test/assets/require-magic-comments-plugin-test/bar.txt?BeWebpack-COPYFILE}":
     /***/ ((module, __unused_webpack_exports, __webpack_require__) => {
    
    at Context.<anonymous> (lib\test\RequireMagicCommentsPlugin.test.js:120:114)
turned error code: 13
i
```

**Review by aruniverse — APPROVED** [review]

**Comment by aruniverse** [comment]
We are dropping our custom webpack pkgs in 5.0, I will open a separate PR to do that, and once thats merged it should unblock you here.

**Comment by pmconne** [comment]
Blocked pending #7469.

**Comment by khanaffan** [comment]
> @khanaffan looks like flaky test (passed on Linux, failed on Mac)
> 
> ```
>   1) Merge conflict & locking
>        pull/merge causing update conflict - update causing local changes (with no lock):
>      Error: Failed to throw error with message: "UPDATE/DELETE before value do not match with one in db or CASCADE action was triggered."
>       at assertThrowsAsync (src/test/standalone/MergeConflict.test.ts:49:9)
>       at async Context.<anonymous> (src/test/standalone/MergeConflict.test.ts:229:5)
> ```

looking into it.

**Pull request merged**
