### PR TITLE
Support snapping to secondary iModels

### PR DESCRIPTION
**Pull request by pmconne**
Fixes https://github.com/iTwin/itwinjs-backlog/issues/1209.

imodel-native: https://github.com/iTwin/imodel-native/pull/877

Allow a TileTreeReference to provide a transform from the world coordinates of the viewport's iModel to those of some other iModel (the one identified by `HitDetail.sourceIModel`). This propagates through `readPixels` to `HitDetail.transformToSourceIModel`. AccuSnap forwards the transform if present when making the snap request to `sourceIModel`.

To test, enhance `dta imodel attach` to apply a transform to draw the attached iModel in the correct location. Previously it applied no transform, so the attached iModel would draw in an unexpected location but snapping would appear to work.

### CODE REVIEW

**Comment by pmconne** [comment]
@bbastings is the world-to-view matrix in `SnapRequest` going to do unexpected things? It's obtained from the viewport, whose definition of "world coords" comes from a different iModel than the one we're snapping to.

**Comment by bbastings** [comment]
> @bbastings is the world-to-view matrix in `SnapRequest` going to do unexpected things? It's obtained from the viewport, whose definition of "world coords" comes from a different iModel than the one we're snapping to.

It's used to compare against the snap aperture. If world doesn't reflect the position of the element geometry in the view it's going to be an issue when the camera is on for certain. Checks like deciding is a snap is hot snap, or even choosing the "best" snap won't be correct.

**Comment by pmconne** [comment]
> Maybe you can use Matrix4d.createTransform from your display transform so you can use Matrix4d.multiplyMatrixMatrix? Matrix4d hurts my brain...might need help from Oslo.

Yeah, I did that. Testing with nearest snap, at some view orientations it will mostly track the surface interiors, though it tends to more eagerly jump to the edges than it would normally. At other view orientations it also jumps to the edges.

I don't see anything else in the snap request that would need a transform applied.

**Comment by bbastings** [comment]
Here's my brute force attempt at something:

let worldToView = hitVp.worldToViewMap.transform0; // Nitpick: this is a Matrix4d, don't call it worldToViewMap...
const toIModel = thisHit.transformToSourceIModel;

if (toIModel) {
  const frustum = hitVp.getWorldFrustum();
  frustum.transformBy(toIModel, frustum);
  const worldToNpcMap = frustum.toMap4d();
  if (worldToNpcMap) {
    const worldToViewMap = Map4d.createIdentity();
    worldToViewMap.setFrom(hitVp.viewingSpace.calcNpcToView().multiplyMapMap(worldToNpcMap));
    worldToView = worldToViewMap.transform0;
  }
}

Did this in notepad, buyer beware...

**Comment by pmconne** [comment]
> Here's my attempt at something:

Seems to behave roughly the same as what I had previously.
Actual change:
```ts
     const toIModel = thisHit.transformToSourceIModel;
-    let worldToViewMap = hitVp.worldToViewMap.transform0;
+    let worldToViewMap = hitVp.worldToViewMap;
     if (toIModel) {
-      const toIModelMap = Matrix4d.createTransform(toIModel);
-      worldToViewMap = toIModelMap.multiplyMatrixMatrix(worldToViewMap);
+      const frustum = hitVp.getWorldFrustum();
+      frustum.transformBy(toIModel, frustum);
+      const worldToNpcMap = frustum.toMap4d();
+      if (worldToNpcMap) {
+        const worldToViewMap = Map4d.createIdentity();
+        worldToViewMap.setFrom(hitVp.viewingSpace.calcNpcToView().multiplyMapMap(worldToNpcMap));
+      }
     }

     const testPoint = toIModel?.multiplyPoint3d(thisHit.testPoint) ?? thisHit.testPoint;
@@ -710,7 +715,7 @@ export class AccuSnap implements Decorator {
       id: thisHit.sourceId,
       testPoint,
       closePoint,
-      worldToView: worldToViewMap.toJSON(),
+      worldToView: worldToViewMap.transform0.toJSON(),
```

**Review by bbastings — APPROVED** [review]

**Comment by pmconne** [comment]
@grigasp fyi flaked out on linux:
```
--[ FAILURE: presentation-full-stack-tests ]--------[ 1 minute 41.2 seconds ]--


  330 passing (2m)
  1 failing

  1) PresentationManager
       Cancel request
         cancels 'getNodes' request:
     AssertionError: expected promise to be rejected with 'PresentationError' but it was fulfilled with [ { key: { version: 2, …(5) }, …(3) } ]
```

**Pull request merged**
